Sage-Bionetworks-IT/organizations-infra

- templates/accounts.yaml
Sumo logic user is no longer needed now that we've changed cloudtrail
and config logging to our logcentral account.
> Remove sumo logic user

- templates/accounts.yaml
giving auditors direct access to our account is a bad practice.
setup cross account access would be better.
> remove auditor policy

- .travis.yml
sceptre validation cannot be run because the `validate` command does
not run the cmd hooks to download the actual CF templates from S3
bucket.
> remove sceptre validation

- sceptre/itsandbox/package.json
- sceptre/lerna.json
- sceptre/organizations/package.json
- sceptre/package.json
- sceptre/sandbox/package.json
- sceptre/scicomp/package.json
Curl failures causes lerna build to fail.  Also it was difficult
to run all sceptre deploys in one VM due to assuming of roles.
Assuming roles is easier when done in separate environments.
> remove lerna

- sceptre/admincentral/config/prod/synapse-stack-dev-vpn-routes.yaml
I changed the synapsedev VPC and got a new peering connection. This PR just adds the routes in AdminCentral (and should also remove the existing routes which are now blackholes).
> Redeployed VPC so new PCX

- sceptre/synapseprod/templates/SynapseCMK-template.json
All I really did was add permissions for SES, no idea why it thinks everything changed...
This is already deployed on prod, just keeping this updated (not run by infra).
diff ~/dev/prod_cmk_github.json ./SynapseCMK-template.json 
177a178,182
>                                 },
>                                 {
>                                     "Effect": "Allow",
>                                     "Action": "ses:*",
>                                     "Resource": "*"
> Add SES permissions

- sceptre/scipool/templates/sc-s3-launchrole.yaml
Setting up S3 same region access restriction requires creating
custom bucket policies. Allow the role that creates the bucket
permissions to create those policies.
> [SC-240] Allow S3 Launch role to create policies

- sceptre/scipool/templates/sc-s3-launchrole.yaml
Allow SCS3LaunchRole to create and Delete Lambda function, which is necessary for restricting S3 Bucket downloads to the same AWS region.
> grant SCS3LaunchRole Lambda Create/Delete permissions

- sceptre/admincentral/config/prod/synapse-stack-prod-vpn-routes.yaml
This PR sets up the routes from 10.1.0.0/16 to the new Synapse prod VPC on 10.20.0.0/16 using the PCX setup by the Synapse VPC stackBuilder (similar to what we did for the dev stack).
> Add config for Synapse prod stack

- sceptre/sageit/config/prod/gha-svc-account.yaml
This PR creates service role for for GHA to deploy a portal in the 'sageit' account. Trimmed down the permissions to S3 and CFront (needs to sync a build to S3 and create an invalidation'.
> GHA svc account to deploy a portal

- sceptre/scipool/config/develop/docker-runner-efs.yaml
- sceptre/scipool/config/prod/docker-runner-efs.yaml
- sceptre/scipool/config/strides/docker-runner-efs.yaml
Setup an elastic file system (EFS) to support a lambda to run
docker containers.  Lambdas have a hard storage limit of 512MB
so we create an EFS for the docker to attach to. This will provide
user apps with expanded storage.
> [SC-306] Setup EFS for lambda

- org-formation/300-account-defaults/_tasks.yaml
EBS encryption  needs to be disabled in order to build public image because
packer can no longer start unencrypted boot images
https://github.com/hashicorp/packer/issues/9529
> Disable EBS encryption for imagecentral account

- sceptre/synapsedev/templates/SynapseCMK-template.json
[IT-1039] This PR gives the idp roles access to the keys. This is necessary to be able to delete a Synapse stack when logged in thru JC at the console. This is prelim work to move away from IAM users to service accounts for the dev stacks.
[IT-1039]: https://sagebionetworks.jira.com/browse/IT-1039
> IT-1039: Give idp roles access to keys

- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-notebook.yaml
- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-workflows.yaml
- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud.yaml
- sceptre/scipool/templates/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/templates/sc-product-s3-private-enc.yaml
- sceptre/scipool/templates/sc-product-s3-synapse.yaml
* removed warning, it was a cfn-lint bug that has been fixed.
* add comments to reasons why we ignore the cfn-lint errors
> Update cfn-lint ignores

- org-formation/040-budgets/README.md
- org-formation/040-budgets/_tasks.yaml
- org-formation/040-budgets/_tasks.yml
- org-formation/_tasks.yaml
Setup a AWS account budget notification. This will allow us to configure
a budget on an account with tags.  Notifications are sent when an account
exceeds the budget.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/286
> [IT-1101] Setup budget notifications

- sceptre/scicomp/config/prod/maintenance.yaml
This change adds a stack from `aws-infra` which defines an SSM scheduled maintenance task that runs in the account and targets instances with the `prod-default` tag on them.
Passes pre-commit
> Add scheduled maintenance task

- sceptre/synapsedev/templates/SynapseCMK-template.json
[PLFM-5619]: Adding various permissions to get the beanstalk stack enabled for platform updates
This is already deployed in dev account, just keep this synced.
Will add to prod config.
> PLFM-5619: Add permissions to enable platform autoupdates

- org-formation/010-scps/_tasks.yaml
- org-formation/organization.yaml
Re organize accounts and org units to separate dev and prod accounts.
Update SCPs on OUs and accounts.  This brings in more inline with AWS best
practice for organizations[1]
[1] https://docs.aws.amazon.com/whitepapers/latest/organizing-your-aws-environment/recommended-ous.html
> [IT-1101] re-org OUs and SCPs

- org-formation/005-types/_tasks.yaml
- org-formation/010-scps/_tasks.yaml
- org-formation/200-baseline/_tasks.yaml
- org-formation/300-account-defaults/_tasks.yaml
- org-formation/600-access/_tasks.yaml
- package.json
The CI build job takes 20 mins to create a single AWS which seems really slow.
Attempt to make it faster by running more CI deployments in parallel.
The benefit of this is that it should make deployments faster, the
drawback is that it will make logs more difficult to read because logs
will be all jumpbled up.
The strategy is to run in parallel only on CI deployment, when manually
running deployments the concurrent executors can be set to 1 to get more
sane logs.
> improve ofn performance

- sceptre/sandbox/config/prod/park-my-cloud.yaml
Sandbox provisioner has been deprecated.  Users have full access to the
EC2 console to start/stop/restart their instances so we no longer
need PMC for sandbox account.
> [SC-148] Remove parkmycloud from sandbox

- org-formation/010-scps/_tasks.yaml
Instead of applying region restriction at the ORG root, move
it to member OUs so that it targeted to specific AWS accounts.
This will remove region restriction from Synapse and Bridge accounts.
> [PLFM-6685] re-org region restriction

- org-formation/600-access/_tasks.yaml
I'm creating service users and roles for the workflows-nextflow-prod and workflows-nextflow-dev accounts that I provisioned in #130 and #136 so I can set up the CI in the associated sceptre provisioner [repository](https://github.com/Sage-Bionetworks-Workflows/aws-workflows-nextflow-infra). 
----
To validate files run: `pre-commit run --all-files`
> Create CI service accounts for Nextflow Prod and Dev accounts

- org-formation/010-scps/_tasks.yaml
Applying a SCP to the org root OU means applying it to all OUs
and all accounts in the org.  Sometimes you may want to apply
to all OUs but not all accounts.  This PR separates applying
of SCP from root OU and all OUs.  This will make it more
flexible for us to shift SCPs around.
Also one of the AWS organization best practice is to apply SCP
guardrails to individual OUs.
> decouple root OU from all OUs.

- org-formation/010-scps/_tasks.yaml
- org-formation/040-budgets/_tasks.yaml
- org-formation/060-cloudtrail/_tasks.yaml
- org-formation/080-aws-config-inventory/_tasks.yml
- org-formation/200-baseline/_tasks.yaml
- org-formation/300-account-defaults/_tasks.yaml
- org-formation/600-access/_tasks.yaml
Pinning versions makes it safer to update shared templates.  This only
pins org-formation usage of the shared templates.  We should make Sceptre
use pinned versions as well but will save that for a separate PR.
> pin shared template versions

- org-formation/040-budgets/_tasks.yaml
- org-formation/060-cloudtrail/_tasks.yaml
- org-formation/080-aws-config-inventory/_tasks.yml
Cloudformation termination protection doesn't really work with CI/CD
setup.  Protection from removal is done in GH reviews.
> Remove termination proctection

- org-formation/600-access/_tasks.yaml
This is to setup a AWS service user/role to deploy CFN templates to
the iAtlas AWS account.
> Setup CI service user/role for iAtlas account

- sceptre/admincentral/config/prod/essentials.yaml
- sceptre/imagecentral/config/prod/essentials.yaml
- sceptre/itsandbox/config/prod/essentials.yaml
- sceptre/logcentral/config/prod/essentials.yaml
- sceptre/organizations/config/prod/essentials.yaml
- sceptre/sageit/config/prod/essentials.yaml
- sceptre/sandbox/config/prod/essentials.yaml
- sceptre/scicomp/config/prod/essentials.yaml
- sceptre/scipool/config/develop/essentials.yaml
- sceptre/scipool/config/prod/essentials.yaml
- sceptre/scipool/config/strides/essentials.yaml
- sceptre/securitycentral/config/prod/essentials.yaml
- sceptre/synapsedev/config/prod/essentials.yaml
- sceptre/synapsedw/config/prod/essentials.yaml
- sceptre/synapseprod/config/prod/essentials.yaml
- sceptre/transit/config/prod/essentials.yaml
Removal of AWS config in PR https://github.com/Sage-Bionetworks/aws-infra/pull/296
removed OperatorEmail parameter therefore we need to update
the deployment to match.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/296
> [IT-1101] Remove OperatorEmail from essentials stack

- org-formation/060-cloudtrail/_tasks.yaml
Update to use newer version of cloudwatch template to create log group.
The new template requires passing in LogGroupName parameter.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/297
> update cloudwatch template

- org-formation/700-aws-sso/_tasks.yaml
Setup to allow users in the JC aws-sadnbox-admins and aws-sandbox-developers
groups access to the AWS sandbox account.
> [IT-1178] Setup SSO group access to AWS Sandbox account

- org-formation/700-aws-sso/_tasks.yaml
Setup to allow users in the JC aws-scicomp-viewers and aws-scicomp-developers
groups access to the AWS scicomp account.
> [IT-1178] Setup SSO group access to AWS Scicomp account

- org-formation/700-aws-sso/_tasks.yaml
Setup to allow users in the JC aws-mobilehealth-dataengineering-admins group
access to the AWS MobileHealthDataEngineeringAccount.
> [IT-1178] Setup SSO group access to AWS mobile health data engineering account

- org-formation/700-aws-sso/_tasks.yaml
Setup to allow users in the JC bridge admin, developer and iOS developer
groups access to AWS bridge dev and bridge prod accounts.
> [IT-1178] Setup SSO access to AWS synapse accounts

- org-formation/300-account-defaults/_tasks.yaml
Create a VPC peering request role to allow account to automatically accept
peering requests . We did this same thing in sceptre with essentials.yaml[1]
[1] https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/essentials.yaml#L92
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/304
> [IT-1205] deploy VPC request authorizer role

- org-formation/070-guard-duty/GuardDutyExternalConnect.yaml
- org-formation/070-guard-duty/_tasks.yaml
- sceptre/strides/config/prod/guardduty.yaml
- sceptre/strides/templates/guardduty.yaml
Setup guardduty member in AWS strides account sending it's finding
to the master securitycentral account.  We setup with sceptre because
strides is no in our ORG therefore it cannot be managed by
org-formation.
> Guardduty for strides account

- org-formation/organization.yaml
We are resetting AWS account names. If we change the name in the
organization.yaml file ofn will try to rename the account and fail.
To get in sync we need to stop ofn from managing the account name.
Once accounts names have been manually updated we can go back and
add the corresponding names into organization.yaml again.
> [IT-1148] remove account names

- org-formation/700-aws-sso/_tasks.yaml
The existing Bridge prod SAML policy restricts develops from being able to
delete RDS and Dynamo DB tables[1].  This change adds that restriction.
[1] https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/sceptre/bridge/templates/iam-policies.yaml#L30-L56
> [IT-1178] Update Bridge prod SSO policy

- org-formation/700-aws-sso/_tasks.yaml
The current Scicomp SAML integration setup has a custom policy[1] for
the viewers, it's a viewer job function policy[2] and view other things
role.  We setup Scicomp SSO to match.
[1] https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/sceptre/scicomp/templates/jumpcloud-idp.yaml#L74-L85
[2] https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html#security-iam-awsmanpol-jobfunction-updates
> [IT-1178] Update Scicomp SSO viewer policy

- sceptre/scipool/config/develop/sc-kms-key.yaml
- sceptre/scipool/config/prod/sc-kms-key.yaml
We switch to using AWS SSO and removed SAML integration therefore
the SAML roles are gone.  We replace with the AWS generated SSO role.
We need to hard code the value because the SSO role is created by
the organizations account where AWS SSO runs.
> Update jumpcloud SAML role to SSO role

- package.json
Running ofn perform-tasks command in parallel fails intermittently
when creating new accounts.  We try to run ofn in single task
mode to see if it makes a difference.
> Update org-formation run commmand

- sceptre/scipool/config/develop/lambda-sc-cost-meter.yaml
- sceptre/scipool/config/prod/lambda-sc-cost-meter.yaml
- sceptre/scipool/config/strides/lambda-sc-cost-meter.yaml
Remove the lamba-sc-cost-meter[1], we've decided to not go with the
experimental AWS marketplace integration to keep track of customer
spend.
[1] https://github.com/Sage-Bionetworks-IT/lambda-sc-cost-meter
> Remove cost meter lambda

- org-formation/700-aws-sso/_tasks.yaml
Packer will create EC2 instances so it to make AMIs.  The AMI librarian
needs to be able to start SSM sessions to EC2 instances on the
ImageCentral account to allow debugging the instances.
> Update AMI Librarian access

- sceptre/imagecentral/templates/service-accounts.yaml
The service account needs to be able to query for the latest AMI
ID which is in the SSM.  This gives the service account access to
SSM parameters.
> Update imagecnetral service account access

- sceptre/scipool/config/develop/sc-product-assoc-ec2-linux-docker.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/templates/sc-product-ec2-linux-docker.j2
Create an EC2 docker product for the Service Catalog.  The product
will be placed into the EC2 portfolio.
Note: This PR only installs into scipooldev for testing.
Depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/247
> [SC-251] EC2 Docker product

- sceptre/scipool/config/develop/sc-kms-key.yaml
- sceptre/scipool/config/prod/sc-kms-key.yaml
- sceptre/scipool/config/strides/sc-kms-key.yaml
- sceptre/scipool/templates/sc-kms-key.yaml
Following least privilege best practice, Instead of giving a role access
to the KMS key we give specific users access to the key.
> Give specific users access to kms keys

- sceptre/scipool/templates/sc-enduser-iam.yaml
Allow SC users to use the SSM start-session and AWS-StartSSHSession
command to start a session with a specific command. This, for example,
will let the user start a session with the `bash` shell instead of the default `sh`
shell.  The command would be..
```
aws ssm start-session --target <INSTANCE_ID> \
--document-name AWS-StartInteractiveCommand
--parameters command="bash -l"
```
more info here: https://aws.amazon.com/blogs/mt/limit-ssm-interactive-session-commands-by-users/
The AWS-StartSSHSession allows users to start an SSH session with
which will allow users to secure copy from local machine and their instance.
more info here: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html
documentation update here: …
> [SC-251] allow SSM AWS-StartInteractiveCommand & AWS-StartSSHSession docs

- sceptre/scipool/templates/sc-enduser-iam.yaml
The SC user gets access denied when attempting to start a session
with SSM dcouments.  The problem was due to the SC user policy.
Mixing SSM document with the policy to restrict users to instances
does not work due to the resource tag condition on the policy.
We need to split the policy up so that the condition does not
apply to the SSM documents.
This PR also allows users to start an command on an instance without
having to open a shell to it by starting the session with
AWS-StartNonInteractiveCommand document.
> [SC-251] Fix SSM document policy

- sceptre/scipool/templates/sc-enduser-iam.yaml
Allow SC end user role access to AWS-StartPortForwardingSession
document.
```
➜  ~ aws ssm start-session  \
--target i-0f83034f048d33a16 \
--document-name AWS-StartPortForwardingSession \
--parameters '{"portNumber":["80"],"localPortNumber":["9090"]}'
An error occurred (AccessDeniedException) when calling the StartSession
operation: User: arn:aws:sts::237179673806:assumed-role/ServiceCatalogEndusers/3377358
is not authorized to perform: ssm:StartSession on resource:
arn:aws:ssm:us-east-1::document/AWS-StartPortForwardingSession
```
> [SC-251] Access to SSM AWS-StartPortForwardingSession doc

- org-formation/700-aws-sso/_tasks.yaml
When permissionSetArn is passed to aws-sso.yaml template the
sessionDuration parameter is ignored.  It will use the sesion
duration defined in the shared permission set that is passed into
the template.
The AWS Admin session timeout is too short. Increase it to 8 hrs.
> Increase SSO admin's session timeout

- sceptre/scipool/templates/sc-enduser-iam.yaml
Give SC users the ability to list and get info about SSM documents[1]
(i.e. AWS-StartInteractiveCommand,  AWS-StartPortForwardingSession,
etc..).  Also give SC users the ability to list running instances so
they can get the instance ID[2]
[1] https://docs.aws.amazon.com/cli/latest/reference/ssm/describe-document.html
[2] https://docs.aws.amazon.com/cli/latest/reference/ssm/describe-instance-information.html
> Update SC end user policy for SSM

- sceptre/scipool/config/develop/cfn-cr-sc-product-provider.yaml
- sceptre/scipool/config/prod/cfn-cr-sc-product-provider.yaml
- sceptre/scipool/config/strides/cfn-cr-sc-product-provider.yaml
Deploy the  cfn-cr-sc-product-provider[1] to allow us to
automate updating of product versions.  The main use case
for this custom resource is so that we can automate the
deprecation of products.
[1] https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-product-provider
> [SC-304] deploy cfn-cr-sc-product-provider

- sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud.yaml
- sceptre/scipool/config/prod/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/prod/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-notebook.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-workflows.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud.yaml
- sceptre/scipool/config/strides/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/strides/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/strides/sc-product-s3-synapse.yaml
- sceptre/scipool/templates/sc-product-ec2-linux-docker.j2
- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-notebook.j2
- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-workflows.j2
- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud.j2
- sceptre/scipool/templates/sc-product-ec2-windows-jumpcloud.j2
- sceptre/scipool/templates/sc-product-s3-private-enc.j2
- sceptre/scipool/templates/sc-product-s3-synapse.j2
AWS cloudformation does not support product deprecation so we've been
doing it manually however that's been an error prone process.  This PR
uses the cloudformation product provider custom resource[1] to
automatically deprecate all versions of a product except for the latest
version.  Users will only be allowed to provision with the latest version
of a product in production environments which prevents confusion and
users provisioning with old version that may have bugs in them.
[1] https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-product-provider
depends on #227
> [SC-304] Deprecate product versions

- .github/workflows/aws-deploy.yaml
We need to apply the workaround to dis-associate and re-associate
SC actions on every deploy to all products.  We missed doing this
in PR #228
Also fixed references to strides account
> [SC-304] apply actions workaround to docker product

- sceptre/scipool/templates/sc-product-ec2-linux-docker.j2
- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-notebook.j2
- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-workflows.j2
- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud.j2
- sceptre/scipool/templates/sc-product-ec2-windows-jumpcloud.j2
- sceptre/scipool/templates/sc-product-s3-private-enc.j2
- sceptre/scipool/templates/sc-product-s3-synapse.j2
The lambda for UpdateProductVersions will not run if there aren't
any changes for the resource.  That's how cloudformation
idempotency works.
The problem is that when a new version of a product is added the
UpdateProductVersions lambda does not execute which means that
the previous version of the product will not get deprecated.
In this case we need to force a change to the resource so that
CFN will execute the lambda on every deployment.  That will make
sure that all previous versions of a product is deprecated.
> [SC-304] force update version on every deploy

- sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-workflows.yaml
Do we add the new versions to the `develop` stack group first and if that deploys fine, perform the same change for `prod` and `strides` in a separate PR?
> Leverage new 5-TB limit in Docker and Workflows EC2 SC products

- org-formation/700-aws-sso/_tasks.yaml
Fix build error..
ERROR: Resource PermissionSet failed because Resource handler
returned message: "Model validation failed
(#/Name: expected maxLength: 32, actual: 52)"
> shorten permissionSetName

- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-workflows.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud.yaml
Based on feedback, we intend to maintain support for the Docker and RStudio
products and deprecate the Workflows and General products.  The Docker
product is just the General Product + Docker, and the Workflow product
can be supported through Docker images.
> [SC-350] Deprecate general EC2 and workflow products

- org-formation/070-guard-duty/_tasks.yaml
Enable Guardduty on the BMGF KI account and send security findings to
securitycentral account.
depends on #246
> [SC-307] setup AWS guardduty for BMGF KI account

- sceptre/admincentral/templates/VPCPeer.yaml
Update python version to accomodate this linter error..
W2531 EOL runtime (python2.7) specified. Runtime is EOL since 2021-07-15 and updating
will be disabled at 2021-09-30. Please consider updating to python3.8
sceptre/admincentral/templates/VPCPeer.yaml:123:7
> Update python version of VPC peering lambda

- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-workflows.j2
- sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud.j2
The General EC2 and Workflow EC2 products have been deprecated with
PR #241, now we don't even want them to be visible to SC users.
> [SC-354] Hide deprecated products

- sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud.yaml
This is a potential fix for missing actions buttons.
Evidence shows that missing actions are only hapenning with
general Linux EC2 products.  My theory is that the Sub in the
product description is causing a new version of the product to be created
on every deploy which would cause the association between actions
and product versions to become out of sync.
> [SC-345] Fix missing actions

- .github/workflows/aws-deploy.yaml
The latest release of Sceptre (v2.6.0)[1] includes the sceptre-file-resolver[2]
and the sceptre-cmd-resolver[3] as core resolvers so we no longer need to install
those in a separate step.
[1] https://github.com/Sceptre/sceptre/blob/master/CHANGELOG.md#260-20210729
[2] https://pypi.org/project/sceptre-file-resolver/
[3] https://pypi.org/project/sceptre-cmd-resolver/
> Update Sceptre install

- org-formation/700-aws-sso/_tasks.yaml
We want Tower users to have some limited view access into the production account. This PR creates a role bound to an inline policy that is a subset of the permissions in the `ViewOnlyAccess` AWS-managed policy. 
If there's a preference for a customer managed policy over the current inline policy, I just need an example to follow. 
@tthyer: I'm assuming that we don't need to maintain separate JumpCloud user groups for the production and develop `TowerViewer` roles. Do you agree?
> Add TowerViewer SSO role

- org-formation/700-aws-sso/_tasks.yaml
The failure seems to indicate that we missed passing in
masterAccountId.  This attempts to fix that error.
> Fix SSO setup for tower viewer user

- org-formation/700-aws-sso/_tasks.yaml
fix this https://github.com/Sage-Bionetworks-IT/organizations-infra/runs/3488456389?check_suite_focus=true#step:8:779
```
ERROR: Resource PermissionSet failed because 1 validation error detected: Value 'Invalid PermissionsPolicy JSON {
"Version": "2012-10-17",
"Statement": [
{
"Sid": "TowerViewOnlyAccess",
"Action": [
"autoscaling:Describe*",
"batch:ListJobs",
"cloudformation:List*",
..
..
```
> Remove errant comma

- sceptre/scipool/templates/sc-enduser-iam.yaml
Give users access to the EC2 monitoring metrics in the AWS console.
> [SC-347] Allow access to EC2 monitoring info

- sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/bmgfki/sc-product-ec2-linux-jumpcloud-notebook.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud.yaml
Update service catalog EC2 products to allow provisioning
x2gd, g4dn and i3en instances.
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/257
> [SC-360] Update EC2 products

- org-formation/700-aws-sso/_tasks.yaml
The TowerViewer SSO group was getting added to organizations account.
Fix so that it only appears in nextflow accounts
> fix TowerViewer group permission

- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-notebook.yaml
Forgot to update the notebook product in PR #288  this is to add
the new EC2 instances to the SC notebook product.
> [SC-360] Add x2gd, g4dn and i3en instance types to notebook product

- sceptre/scipool/config/bmgfki/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/bmgfki/sc-product-s3-synapse.yaml
- sceptre/scipool/config/develop/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/develop/sc-product-s3-synapse.yaml
- sceptre/scipool/config/prod/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
- sceptre/scipool/config/strides/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/strides/sc-product-s3-synapse.yaml
Update S3 product version to retain bucket on SC product termination
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/259
> [SC-326] Update S3 product version

- sceptre/scipool/config/bmgfki/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/bmgfki/sc-product-s3-synapse.yaml
- sceptre/scipool/config/develop/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/develop/sc-product-s3-synapse.yaml
- sceptre/scipool/config/prod/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
- sceptre/scipool/config/strides/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/strides/sc-product-s3-synapse.yaml
Update S3 bucket product to enable S3 intelligent tiering
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/261
> [SC-363] update SC S3 bucket product

- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
This PR updates the R-Studio notebook product to use a new packer-generated AMI which incorporates an increase in the limit of concurrently open files allowed by the Linux o/s.
> SC-318 using new AMI in R-Studio notebook product

- .github/workflows/aws-deploy.yaml
Remove the sceptre identity resolver.  This was probably used once
upon a time however there currently is no evidence that we still
need it anynore.
> Remove sceptre identity resolver

- sceptre/bridge/config/develop/essentials.yaml
- sceptre/bridge/config/develop/iam-policies.yaml
- sceptre/bridge/config/prod/AccountAlertTopics.yaml
- sceptre/bridge/config/prod/BridgeServer2-vpc.yaml
- sceptre/bridge/config/prod/bootstrap.yaml
- sceptre/bridge/config/prod/bridge.yaml
- sceptre/bridge/config/prod/essentials.yaml
- sceptre/bridge/config/prod/iam-policies.yaml
- sceptre/bridge/config/prod/peer-vpn-BridgeServer2-vpc.yaml
- sceptre/bridge/config/prod/peer-vpn-bridge-prod.yaml
- sceptre/bridge/config/prod/rotate-credentials.yaml
- sceptre/bridge/config/prod/tgw-spoke-BridgeServer2-vpc.yaml
- sceptre/sageit/config/staging/staging-csbc-pson-s3web.yaml
Sceptre has template handlers[1] now so we can abandon the use of
hooks in favor of the http template handler to get templates
from our shared template repository. This updates some of the one
we missed from previous updates
[1] https://sceptre.cloudreach.com/dev/docs/template_handlers.html#template-handlers
> [IT-1331] replace hooks with template handler

- sceptre/admincentral/config/prod/cfn-s3objects-macro.yaml
- sceptre/sageit/config/prod/cfn-s3objects-macro.yaml
- sceptre/sandbox/config/prod/cfn-s3objects-macro.yaml
- sceptre/scicomp/config/prod/cfn-s3objects-macro.yaml
- sceptre/scipool/config/bmgfki/cfn-s3objects-macro.yaml
- sceptre/scipool/config/develop/cfn-s3objects-macro.yaml
- sceptre/scipool/config/prod/cfn-s3objects-macro.yaml
- sceptre/scipool/config/strides/cfn-s3objects-macro.yaml
The cfn-s3-objects-macro[1] was recently fixed and a new version was released.
It's better to pin to a known good version[2] than using master.
[1] https://github.com/Sage-Bionetworks-IT/cfn-s3objects-macro
[2] https://bootstrap-awss3cloudformationbucket-19qromfd235z9.s3.amazonaws.com/index.html#cfn-s3objects-macro/
> Update and pin the cfn-s3-objects-macro

- org-formation/050-costs/_tasks.yaml
- org-formation/_tasks.yaml
- sceptre/strides/config/prod/anomaly-detector-service.yaml
Setup AWS cost anomaly detection on every account to get notifications
of unforeseen cost changes.  Notifications are sent to account owner email
lists.  This will hopefully help prevent situations where accounts are racking
up big costs without anybody knowing.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/325
> [IT-1478] deploy cost anomaly detector services

- org-formation/600-access/_tasks.yaml
Our collaborators needed admin access to get the iAtlas app going.
They have successfully done that with PR
https://github.com/Sage-Bionetworks/iAtlas-infra/pull/19
Now we can restrict their access so that only our CI can make updates
to the account again.
> Reduce iAtlas collaborator access

- .github/workflows/aws-deploy.yaml
Updating to the latest version of Sceptre (version 2.7.0) which
contains the template handlers feature.
> update to latest version of sceptre

- sceptre/scipool/config/bmgfki/PyPlate.yaml
- sceptre/scipool/config/develop/PyPlate.yaml
- sceptre/scipool/config/prod/PyPlate.yaml
- sceptre/scipool/config/strides/PyPlate.yaml
Install the cloudformation PyPlate macro[1] which will allow more
flexibility in our cloudformation templates.  Essentially it
will allow us to manipulate input parameters.
[1] https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/CloudFormation/MacrosExamples/PyPlate/README.md
> [SC-306] Install CFN PyPlate macro

- sceptre/scipool/config/bmgfki/docker-runner-efs-vpc.yaml
- sceptre/scipool/config/develop/docker-runner-efs-vpc.yaml
- sceptre/scipool/config/prod/docker-runner-efs-vpc.yaml
- sceptre/scipool/config/strides/docker-runner-efs-vpc.yaml
This reverts PR #102.  We are no longer using lambda therefore
we no longer need EFS.
> Remove VPC for EFS

- sceptre/scipool/templates/sc-enduser-iam.yaml
We setup batch to send cron job logs to cloudwatch logs therefore we
need to give SC users read only access to cloudwatch logs so they view
logs from their jobs.
> [IT-306] Give SC users access to cloudwatch logs

- sceptre/strides/config/prod/bootstrap-cross-account-role.yaml
There is a CFN template deployed into org-sagebase-strides account
however it's not in CI/CD.  We add the CFN template here to make
it consistent and to allow us to automate those AWS resources.
> import cfn template for strides

- sceptre/strides/templates/aws-config.yaml
AWS Config from strides account wasn't logging to logcentral
account due to missing permissions.  We also need to give
strides account permissions to write to the central s3 config
bucket in logcentral account.
We are following the pattern established by org-formation which
does work as expected. org-formation patter is defined in
[ConfigurationRecorderRole](https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/Config/config.yaml)
> [IT-1549] Fix AWS config logging to logcentral account

- org-formation/070-guard-duty/_tasks.yaml
- org-formation/600-access/_tasks.yaml
We need to setup some snowflake infra for the
org-sagebase-strides-ampad-workflows account because it's not
under our org account.  This sets up master member configuration
for guard duty, AWS config, and cloudtrail.
> [IT-1536] Setup org-sagebase-strides-ampad-workflows AWS Account

- sceptre/bridge/templates/bridge.yaml
PR Checklist:
[X] Describe and explain your intentions for this change - We recently increased our SMS spending threshold from $30 to $90. This corresponding change increases our alarm from $24 to $72.
> increase SMS alarm from $24 to $72

- org-formation/700-aws-sso/_tasks.yaml
- sceptre/strides/templates/jumpcloud-idp.yaml
Sometimes the Service Catalog community manager wants to submit support tickets
to AWS because they have questions regarding the SC account that they
manage.  This will give all SC community managers access to submit AWS
support tickets.
> Give SC community manager access to AWS support

- org-formation/organization.yaml
We have deployed more granular budget alerts on the AWS account here:
https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/tree/main/config/common
As a result, it's no longer useful to have a budget alert set in organizations-infra. It's better for us to adjust alerts in one place as our expectations for monthly costs change.
> Remove budget alerts in favor of granular alerts

- org-formation/600-access/_tasks.yaml
- sceptre/strides-ampad-workflows/config/prod/workflows-nextflow-ci-service-account.yaml
I'll be deploying to the `strides-ampad-workflows` AWS account from our [nextflow-infra](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra) repository. This CI service account will be used by the [GitHub Actions workflow](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/blob/bgrande/WORKFLOWS-85/test-sandbox-tower-project/.github/workflows/aws-deploy.yaml) to deploy infrastructure for running Nextflow workflows in `strides-ampad-workflows`.
> Deploy CI service account for STRIDES AMP-AD acct

- sceptre/strides-ampad-workflows/config/prod/workflows-nextflow-ci-service-account.yaml
I copy-pasted the GitHub URL and changed it to the S3 bucket, but `templates/` isn't part of the key in S3.
> Remove `templates/` from S3 URL

- org-formation/organization.yaml
Add account ID info to the organizations definition to more
easily identify accounts.
> Update org-formation with account id info

- sceptre/scipool/config/develop/sc-portfolio-scheduled-jobs.yaml
- sceptre/scipool/config/develop/sc-product-scheduled-jobs.yaml
- sceptre/scipool/config/develop/sc-scheduled-jobs-launchrole.yaml
- sceptre/scipool/config/develop/sc-tag-options.yaml
- sceptre/scipool/templates/sc-portfolio-scheduled-jobs.yaml
- sceptre/scipool/templates/sc-product-scheduled-jobs.yaml
- sceptre/scipool/templates/sc-scheduled-jobs-launchrole.yaml
Add a scheduled jobs product to the service catalog.  Setup the product
in a new portfolio with a separate role so we can conditionally give
different users access to this product.
depends on PR https://github.com/Sage-Bionetworks/service-catalog-library/pull/264 https://github.com/Sage-Bionetworks/service-catalog-library/pull/266
> [SC-306] SC scheduled jobs product

- sceptre/scipool/templates/sc-enduser-iam.yaml
With the addition of a batch product users should be able
to view their batch jobs ocnce it's been provisioned.  This
gives all SC end users permission to view batch jobs using
the AWS console.
> [SC-306] Allow SC users to view jobs

- sceptre/scipool/config/develop/sc-product-scheduled-jobs.yaml
This includes changes in
PR https://github.com/Sage-Bionetworks/service-catalog-library/pull/267
which will make the parameters in the service catalog
Scheduled jobs product a required field.
> [SC-306] update SC scheduled jobs product

- sceptre/scipool/config/bmgfki/sc-tag-options-external.yaml
- sceptre/scipool/config/bmgfki/sc-tag-options.yaml
- sceptre/scipool/config/develop/sc-tag-options-external.yaml
- sceptre/scipool/config/develop/sc-tag-options.yaml
- sceptre/scipool/config/prod/sc-tag-options-external.yaml
- sceptre/scipool/config/prod/sc-tag-options.yaml
- sceptre/scipool/config/strides/sc-tag-options-external.yaml
- sceptre/scipool/config/strides/sc-tag-options.yaml
- sceptre/scipool/templates/sc-tag-options.j2
Add a service catalog CostCenter tag.  It is a required tag so users
will need to pick one cost center from the list when provisioning SC
products.  The source of the cost center tags are in the
aws-infra repo[1].
[1] https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/tags/SageFinancialProgramCodes.json
> [SC-373] Add a cost center tag option

- sceptre/scipool/config/bmgfki/sc-tag-options-external.yaml
- sceptre/scipool/config/bmgfki/sc-tag-options.yaml
- sceptre/scipool/config/develop/sc-tag-options-external.yaml
- sceptre/scipool/config/prod/sc-tag-options-external.yaml
- sceptre/scipool/config/strides/sc-tag-options-external.yaml
- sceptre/scipool/config/strides/sc-tag-options.yaml
- sceptre/scipool/templates/sc-tag-options.j2
Tag options were failing to deploy because internal and external tag
option configurations shared the same CFN template.  This caused
the template to deploy duplicate tag options.
To fix this issue we change the template to optionally create the
tag options.  If it's not specified then don't create them.  This
allows us to completely remove the CostCenter tags from BMGFKI and
STRIDES service catalog accounts.  This also allows us to remove
the cost center tags for extnernal users.
> [SC-373] Fix tag options

- sceptre/sandbox/config/prod/cfn-explode-macro.yaml
This macro was installed for testing.  We've determined that
it is not useful and it's not used anywhere so we are removing it.
> Remove explode macro

- sceptre/scipool/config/develop/sc-product-scheduled-jobs.yaml
Update scheduled jobs product.  The update adds a step to
tag batch resources when a user provisions the scheduled jobs
product
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/273 and https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/359
> [SC-379] Update scheduled jobs product

- sceptre/scipool/config/prod/sc-product-scheduled-jobs.yaml
Add parameters to trigger the product provider lambda to deprecate old
versions of the Scheduled Jobs product
> deprecate old versions

- sceptre/scipool/templates/sc-scheduled-jobs-launchrole.yaml
The role used to deploy the scheduled jobs products requires more access
because it deploys a batch trigger lambda nested inside of the product.
AWS recommends providing more extensive permissions[1] when deploying
lambdas.
[1] https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-permissions.html
> [SC-306] Update SC launch role for Scheduled Jobs product

- sceptre/scipool/config/bmgfki/cfn-cr-sc-actions-provider.yaml
- sceptre/scipool/config/develop/cfn-cr-sc-actions-provider.yaml
- sceptre/scipool/config/prod/cfn-cr-sc-actions-provider.yaml
- sceptre/scipool/config/strides/cfn-cr-sc-actions-provider.yaml
Make the service catalog pin to a specific version of
the cfn-cr-sc-actions-provider[1] lambda
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-actions-provider/pull/16
[1] https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-actions-provider
> Pin cfn-cr-sc-actions-provider

- sceptre/scipool/config/bmgfki/lambda-budgets.yaml
- sceptre/scipool/config/develop/lambda-budgets.yaml
- sceptre/scipool/config/prod/lambda-budgets.yaml
- sceptre/scipool/config/strides/lambda-budgets.yaml
Make the service catalog pin to a specific version of
the lambda-budgets[1] lambda
depends on https://github.com/Sage-Bionetworks-IT/lambda-budgets/pull/12
[1] https://github.com/Sage-Bionetworks-IT/lambda-budgets
> Pin lambda-budgets

- sceptre/scipool/config/bmgfki/cfn-cr-alb-rule.yaml
- sceptre/scipool/config/develop/cfn-cr-alb-rule.yaml
- sceptre/scipool/config/prod/cfn-cr-alb-rule.yaml
- sceptre/scipool/config/strides/cfn-cr-alb-rule.yaml
Make the service catalog pin to a specific version of
the cfn-cr-alb-rule[1] custom resource
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-alb-rule/pull/7
[1] https://github.com/Sage-Bionetworks-IT/cfn-cr-alb-rule
> Pin cfn-cr-alb-rule

- sceptre/bridge/templates/bridge.yaml
Our SMS usage has increased from $90 to $120. We need to increase the alarm threshold proportionately. See https://sagebionetworks.jira.com/browse/BRIDGE-3197
PR Checklist:
> increase SMS alarm from $72 to $96

- org-formation/700-aws-sso/_tasks.yaml
Give our security auditor access to the Sage Organizations
account with the auditor access role.
> Update security auditor access

- sceptre/sageit/config/prod/vpn-sageit-org-redirector.yaml
The Sage VPN was recreated.  We update the redirect to point to the new
location.  The new location is at https://self-service.clientvpn.amazonaws.com/endpoints/cvpn-endpoint-0343fb9e37fbbd1f0
depends on PR https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/375
> [IT-1235] Setup redirect for new AWS Sage VPN

- org-formation/070-guard-duty/_tasks.yaml
Run the AWS guardduty service on all accounts and have them
report back to the guardduty hub (logcentral).
> [IT-1621] Enable aws guard duty on all accounts

- org-formation/070-guard-duty/_tasks.yaml
Guardduty got into a broke state due to PR #380.
The problem was that we aded ItProdOU to the list of accounts
That OU contained securitycentral which should not be added as
a guardduty member because it's already the guardduty master.
This change uses `*` to adds all accounts and excludes securitycentral
which will essentially enable guardduty for all accounts going
forward.
Note: in order to get guardduty out of the bad state it had to be
completely reset.
> Fix Guardduty

- org-formation/710-tgw/vpc.yaml
The PR #390 to update AZ for SubnetD returned the following error.
```
ERROR: Resource SubnetD failed because CIDR Block must change if
Availability Zone is changed and VPC ID is not changed
```
Attempt to fix by bumping the SubnetD CIDR range. New setup
is..
* 10.100.1-99.x would be non public vpcs
* 10.100.100.x would be a public vpc internal range
> Fix update

- org-formation/710-tgw/vpc.yaml
- org-formation/720-client-vpn/_tasks.yaml
We are playing a game of wack-a-mole when attempting to update
the public subnet for the VPN because AWS has a hard time
updating all the dependencies on the subnet configuration.
In an attempt to start with a clean slate we are going to
delete the public subnet and recreate it.
> Remove public subnet

- org-formation/710-tgw/vpc.yaml
- org-formation/720-client-vpn/_tasks.yaml
The aws documentation[1] suggests that we need to associate the AWS
VPN to public subnets instead of private subnets to allow
internet traffic.  This re-enables the TGW and VPN setup and update
the VPN to use public subnets.
[1] https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/scenario-internet.html
> Setup VP for full tunnel

- org-formation/720-client-vpn/_tasks.yaml
- org-formation/720-client-vpn/vpn.njk
To setup VPN to access internet traffic we need to provide a
route between the VPN and the internet as described in the
AWS documentation[1].  This will allow a full VPN tunnel to
access the internet.
[1] https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/scenario-internet.html
> [IT-1234] Enable VPN full tunnel

- .github/workflows/aws-deploy.yaml
- package.json
Make org-formation deploy stacks in parallel.  Some things, like
guardduty, needs to be deployed in parallel becuase it requires
syncronysation (invite/accept) between accounts.
Note: We have seen issues when parallelism is enabled when creating new
accounts[1] so we set to only 10 to see if new account creation still
fails.
[1] related to issue https://github.com/org-formation/org-formation-cli/issues/192
> CFN Deploy stacks in parallel

- org-formation/720-client-vpn/vpn.njk
If split tunnel is enabled then internet traffic will not go thru the VPN
therefore we only need to setup a route from the VPN to the internet if
full tunnel is enabled.
> [IT-1234] Set condition on VPN full tunnel

- org-formation/710-tgw/_tasks.yaml
There can be multiple VPCs in an AWS account.  To setup TGW
routing to multiple VPCs we map a group of VPCs to a TGW spoke
group. This sets up routes from the TGW to VPCs in the
2nd spoke group.
> [IT-1234] Setup group b TGW spokes

- org-formation/600-access/_tasks.yaml
We believe our GenUI consultant, Jon Ryser, no longer works
on the iAtlas project so removing his access to the iAtlas
AWS account.
> [IT-1683] Remove collaborator access

- org-formation/700-aws-sso/_tasks.yaml
- sceptre/scicomp/config/prod/cloudwatch-cross-account-sharing.yaml
We do not use the support writer role therefore we should
not keep it around.
> Remove unused role

- org-formation/600-access/_tasks.yaml
This creates a service account/role pair for CI to deploy
agora resources into org-sagebase-agora-prod AWS account
> [IT-1663] Setup agora service user

- org-formation/700-aws-sso/_tasks.yaml
- sceptre/scicomp/config/prod/cloudwatch-cross-account-sharing.yaml
The PowerUserAccess job function policy gives our SSO roles the
ability to assume other roles in an AWS account.  Since our JC
users are mapped to SSO roles this would allow our JC users to
potentially escalate their privileges by assuming a more
privileged role.
We want our IDP to be the source of truth for access to AWS.  This
setup is a security hole because it allows the role to circumvent
how we manage AWS access in JC.  To prevent this from happening we add
an explict deny to not allow our JC users to assume other roles.
> [IT-1671] Prevent users from escalating privileges

- org-formation/700-aws-sso/_tasks.yaml
We initially denied `iam:PassRole` but that's wrong, as pointed
out by @ahayden we should be denying on `sts:AssumeRole`
> [IT-1671] Deny assume role

- .github/workflows/aws-deploy.yaml
- .github/workflows/validate.yaml
We use github actions to deploy cloudformation to AWS.  This deployment
is currently setup to run in parallel when multiple PRs are merged at
the same time.  Parallel infrastructure deployments to AWS do not work therefore
we want to turns off github action parallel deployments to AWS.
This separates the GH action to two workflows.  The deployment
workflow will only run if there is a merge to the master branch and
the validate workflow passes.
> Prevent parallel AWS deployments

- org-formation/organization.yaml
The best practice to setting up IPAM[1] is to set it up in a separate
aws account so we can delgate specific groups to admin and monitoring
it.  This PR is to create a new AWS account for the IPAM service.
[1] https://docs.aws.amazon.com/vpc/latest/ipam/enable-integ-ipam.html
> [IT-1708] Create new AWS account

- org-formation/075-security-hub/_tasks.yaml
We are moving the security hub service to the organizations account
and delegating administrating to securitycentral account.
Note: delegation happens after setting this up and it can only be
done manually thru the AWS console or CLI
> [IT-607] Move security hub service

- org-formation/710-tgw/_tasks.yaml
- org-formation/710-tgw/tgw-spoke-synapse.njk
AWS requires setting up a route to the TGW VPC in each route table
to allow VPN access to each subnet group (RED, GREEN, BLUE, and
ORANGE)
> [IT-1234] Setup additional routes for synapse

- org-formation/720-client-vpn/vpn.njk
Using an index for resource names is not good because it's not
gauranteed to be in the same order on the next deployment.  This
can cause AWS to do many replacements which may force users to
reconnect to the VPN.  We change to more static naming convention
to make it consistent across deployments.
> [IT-1234] Fix VPN resource names

- org-formation/720-client-vpn/_tasks.yaml
- org-formation/720-client-vpn/vpn-auth-routes.njk
- org-formation/720-client-vpn/vpn.yaml
Authorization and route configurations will change often however
the VPN should not.  We de-couple the two so it will make it
easier to fix auth and route configurations if they ever get
messed up.
> [IT-1234] Decouple VPN from configuring VPN auth and routes

- org-formation/300-account-defaults/_tasks.yaml
The idea behind adding this KMS key was to use it to encrypt
secrets before kicking off automation.  It seems like we never
actually used it.
> remove unused kms key

- org-formation/720-client-vpn/_tasks.yaml
- org-formation/720-client-vpn/vpn.yaml
The existing configuration did not allow windows clients to access
to the internet after connecting to the VPN.  AWS support says that
we need to configure the DNS servers in order for windows to connect
to the internet.  This sets the DNS configurations as specified in
the VPC docs[1]
[1] https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html
> [IT-1234] Fix VPN configuration

- org-formation/600-access/_tasks.yaml
Setup a service user/role pair to allow CI to deploy resources
to the Agora Dev account.
depends on #443
> [IT-1663] Setup service role for Agora dev account

- org-formation/200-baseline/_tasks.yaml
This is to update the password policy to be more strict.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/343
> Update password policy

- org-formation/700-aws-sso/_tasks.yaml
Create a viewer plus permission set that can be re-used by multiple
SSO configurations.
> Refactor viewer-plus permission

- sceptre/scipool/templates/alb-notebook-access-logsbucket.yaml
[ x ] The org should need only a cross account S3 logger access for the AWS ALB main account from a single region
[ x ] Passes pre-commit
> Limit ALB logging bucket cross account to single region

- sceptre/bridge/config/develop/sumologic-role.yaml
- sceptre/bridge/config/prod/sumologic-role.yaml
Add SumoLogic roles to the Bridge account so we can migrate from key-based authentication to role-based authentication.
PR Checklist:
> IT-426 add SumoLogic role to Bridge

- sceptre/bridge/templates/aws-default-vpc.yaml
- sceptre/bridge/templates/bridge.yaml
We use the transit gateway to route traffic between the hub
and spoke VPCs. To allow access to resources in a spoke VPC we need
to give the hub VPC access to the resources. This adds an SG ingress
to resources provisioned in our spoke VPCs which will allow VPN users
access to the resources in the spoke VPCs.
> [IT-1234] AWS Security group for TGW

- sceptre/sandbox/config/prod/s3-gateway-vpc-endpoint.yaml
- sceptre/scicomp/config/prod/s3-computevpc-gateway-endpoint.yaml
- sceptre/scicomp/config/prod/s3-snowflakevpc-gateway-endpoint.yaml
- sceptre/scipool/config/bmgfki/s3-gatespoolvpc-gateway-endpoint.yaml
- sceptre/scipool/config/develop/s3-cesspoolvpc-gateway-endpoint.yaml
- sceptre/scipool/config/prod/s3-internalpoolvpc-gateway-endpoint.yaml
- sceptre/scipool/config/strides/s3-stridespoolvpc-gateway-endpoint.yaml
We have added the s3 gateway endpoint to the VPC templates in
PR https://github.com/Sage-Bionetworks/aws-infra/pull/324 therefore
we we don't need to deploy the gateway in a spearate template
> Remove S3 gateway endpoint

- org-formation/710-tgw/_tasks.yaml
- org-formation/720-client-vpn/_tasks.yaml
Needed to give access to build-system-ops. This VPC was built with infra so put in spokeB.
> IT-1234: Add synapse-ops-vpc-v2

- org-formation/600-access/_tasks.yaml
Setup a service account for the AWS account used for testing
Sceptre.  This credential is used in the sceptre-aws repo[1]
[1] https://github.com/Sceptre/sceptre-aws
> [IT-1736] Role for AWS sceptre account

- sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud.yaml
- sceptre/scipool/config/develop/sc-product-ec2-windows-jumpcloud.yaml
Update scipool products to allow access from new AWS VPN.
This PR updates for scipool dev env only.  We update dev then will
update prod in a separate PR
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/275
> [IT-1234] Update scipool products

- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud.yaml
Revert updates to sc-product-ec2-linux-jumpcloud-workflows and
sc-product-ec2-linux-jumpcloud products because there are no updated
versions for these.  We no longer support these products
> Revert updates

- sceptre/admincentral/config/prod/peering-sandcastlevpc.yaml
This PR tests step2, in admincentral remove the routes to spoke, the peering etc. 
Don't merge until #477 is in.
> IT-1874: Remove routes to spoke, pcx etc. for sandcastle

- sceptre/bridge/templates/bridge.yaml
Remove SumoLogic user from Bridge account to finish migration from key-based authentication to role-based authentication.
PR Checklist:
> IT-426 Remove SumoLogic User from Bridge account

- org-formation/650-identity-providers/_tasks.yaml
- org-formation/650-identity-providers/github-oidc-provider.njk
- org-formation/_tasks.yaml
This is to configure Github OpenID connect in AWS[1].  This allows
us to use github actions to deploy cloud resources to AWS
without having to give github our AWS credentials.
[1] https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
> [IT-1934] Make github access to aws more secure

- .github/workflows/validate.yaml
Running the linter caused the following error..
`ModuleNotFoundError: No module named 'jinja2-ansible-filters'`
Go back to a working jinja2-lint version due to issue https://github.com/drm/jinja2-lint/issues/18
> Fix jinj2 linter

- .github/workflows/aws-deploy.yaml
Make github actions use the OIDC role that was setup by PR #492
and remove credentials from github.
depends on #492
> [IT-1934] Use OIDC role to deploy templates

- .github/workflows/aws-deploy.yaml
Setup github action to assume the org role that has cross account
access to assume one a role in one of it's child accounts. Then
use the child account's role to deploy templates.
depends on #495
> [IT-1934] Use OIDC role to deploy cfn to all accounts

- .github/workflows/aws-deploy.yaml
Setup github action to use the OIDC role in member accounts to deploy
cloudformation templates.  This sets up OIDC for all accounts
except for strides which is not in the organization.
depends on #492 #498
> [IT-1934] Use OIDC role

- .github/workflows/aws-deploy.yaml
Assume a role with a role session name to allow us to easily audit
our CI deployments to AWS.
> Add an AWS role-session-name to deployment

- .github/workflows/aws-deploy.yaml
Setup github action CI to use the OIDC role in strides accounts to
deploy cloudformation templates.
depends on #502
> [IT-1934] Make github use OIDC role

- .github/workflows/aws-deploy.yaml
Setup github action CI use the OIDC role in strides account
to deploy cloudformation templates.  We forgot this when doing
PR #503
depends on #502
> [IT-1934] Github action use OIDC

- org-formation/300-account-defaults/_tasks.yaml
fix build error..
```
ERROR: error updating CloudFormation stack it-kms-key in account 728882028485 (us-east-1). 
ERROR: Resource Key failed because Resource handler returned message: "Policy contains a statement with one or more invalid principals. (Service: Kms, Status Code: 400, Request ID: ccaa095c-a641-460a-a81d-c8d3ca6e7e11)" (RequestToken: 2ad6d323-faf7-6e21-2bec-81f34c2124b7, HandlerErrorCode: InvalidRequest).
```
We cannot rely on the custom role/OrganizationFormationBuildAccessRole to
exist on accounts since it may likely get removed by the account owner.
The more reliable role is the "OrganizationAccountAccessRole"[1] because that's
the one that is automatically created by AWS upon AWS account creation.
[1] https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_a …
> update ItKmsKey access

- org-formation/700-aws-sso/_tasks.yaml
Setup SaturnCloudDev account integration with jumpcloud IDP.
This will allow jumpcloud groups `aws-saturncloud-dev-admins`
and `aws-saturncloud-dev-developers` access to SaturnCloudDev
AWS account.
> [IT-1960] Setup SSO for SaturnCloudDev account

- org-formation/600-access/_tasks.yaml
- org-formation/600-access/saturncloud-iam-role.yaml
For privacy and security reasons we are evaluating saturn cloud[1]
enterprise in our own AWS account.  One of the requirements to running
saturn cloud in our AWS account is to create a role that allows
them access to our account.
[1] https://dev.saturncloud.io/
[2] https://dev.saturncloud.io/docs/enterprise/installation/#option-b-create-the-iam-role-yourself
> [IT-1960] Create access role for saturn cloud

- sceptre/admincentral/config/prod/peering-nlpsandbox.yaml
After removing the routes in nlpsandbox, this PR removes the routes on admicentral side, as well as the peering and lambda used to accept the peering on nlp side.
> PLFM-1874: NLP-2-remove-peering

- org-formation/300-account-defaults/_tasks.yaml
This PR removes the peering authorizer role (used to accept peering in target account). Originally targeted at nlpsandbox but after looking at other accounts listed I think it can be removed everywhere.
Depends on #517
> it-1874-remove-peering-authorizer-role

- sceptre/synapsedev/templates/SynapseCMK-template.json
This PR adds permissions required to execute the Synapse repo build in the instance profile (as opposed to specifying credentials to the build). Note: not deployed by the infra.
> PLFM-7337: Add athena permission for builds

- org-formation/705-ipam/_tasks.yaml
- org-formation/705-ipam/ipam.yaml
- org-formation/_tasks.yaml
Setup the AWS IP address manager in the IPAM account, which
is a delgate account[1] in the Sage organizations.  This will
allow giving a separate set of groups/users access to the
accoun to manage IPs.
[1] https://docs.aws.amazon.com/vpc/latest/ipam/enable-integ-ipam.html
> [IT-1708] Setup IP address manager

- .github/workflows/aws-deploy.yaml
- package.json
Add an additional `print-task` step in CI to validate templates.
The `print-task` command will generate templates with inputs which
may find failures that the `validate` command may not
> step to validate cfn templates

- sceptre/admincentral/config/prod/synapse-stack-dev-vpn-routes.yaml
This PR removes the routes from admincentral to the current synapsedev VPC.
> IT-1874: Remove routes to new/current synapsedev VPC

- sceptre/admincentral/config/prod/synapse-stack-prod-vpn-routes.yaml
This PR removes the routes to the new synapse prod (10.20.0.0/16). Note: the pcx is already gone.
> IT-1874: Remove routes to synapseprod

- org-formation/010-scps/_tasks.yaml
Prevent users from disabling cloudtrail and cloudwatch in their
personal accounts.
> Enable SCPs for PersonalAccountsOU

- org-formation/_scp.yaml
- org-formation/organization.yaml
Setup a service control policy to prevent all accounts from registering
domains, except for the org-sagebase-sageit account. For security and
consolidation IT want to control the domains that are created at Sage.
> [IT-1974] SCP to deny registering domains

- org-formation/_scp.yaml
- org-formation/organization.yaml
Prevent accounts from circumventing Jumpcloud access
by restricting AWS console access to IAM users.
The only users that are allowed are service users.
> [IT-1983] SCP to deny adding human users

- .pre-commit-config.yaml
- sceptre/sageit/templates/admodeladexplorer-redirector.yaml
* Update pre-commit linter with the auto updater
* Fix a problem that cfn linter found
```
AWS CloudFormation Linter................................................Failed
- hook id: cfn-python-lint
- exit code: 2
E3002 Invalid Property Resources/RedirectFct/Properties/FunctionMetadata
sceptre/sageit/templates/admodeladexplorer-redirector.yaml:125:7
```
> Update pre-commit linters

- org-formation/060-cloudtrail/_tasks.yaml
- org-formation/060-cloudtrail/cloudtrail-trail.yaml
This is a follow on to PR #522 which only partially refactored
the cloudtrail for encryption.  The policies in that PR were
not quite correct.
This PR will do the following to finish it:
* Enable KMS key to encrypt the cloudtrail trail
* Fix policies to allow cloudtrail to correctly access
the S3 bucket
* Fix policies to allow cloudtrail and users to access the KMS key
> [IT-1904] Fix policies for cloudtrail

- org-formation/040-budgets/cur.yaml
We are seeing a permissions issue deploying the cost report stack,
revert the bucket policy to Public, which worked in a test stack.
PR Checklist:
> Revert CUR bucket to Public

- org-formation/040-budgets/cur.yaml
AWS automatically applies a bucket policy to buckets used for cost
and usage reports, and will refuse to write the report if the policy
has changed.
Also make sure that the cost report depends on the policy for good measure.
The expected bucket policy can be found at
https://docs.aws.amazon.com/cur/latest/userguide/cur-s3.html
PR Checklist:
[x] Describe and explain your intentions for this change
[x] Setup pre-commit and run the validators (info in README.md)
> Cost report bucket policy must match what AWS expects

- sceptre/admincentral/config/prod/cfn-s3objects-macro.yaml
- sceptre/sageit/config/prod/cfn-s3objects-macro.yaml
- sceptre/sandbox/config/prod/cfn-s3objects-macro.yaml
- sceptre/scicomp/config/prod/cfn-s3objects-macro.yaml
- sceptre/scipool/config/bmgfki/cfn-s3objects-macro.yaml
- sceptre/scipool/config/develop/cfn-s3objects-macro.yaml
- sceptre/scipool/config/prod/cfn-s3objects-macro.yaml
- sceptre/scipool/config/strides/cfn-s3objects-macro.yaml
This updates the cloudformation S3Objects Macro[1] in our AWS accounts
with fixes to work for python 3.8
depends on https://github.com/Sage-Bionetworks-IT/cfn-s3objects-macro/pull/9
> [IT-1801] deploy updated cfn-s3-objects-macro

- org-formation/600-access/_tasks.yaml
The AWS account DnT-Dev needs a service account user for CI. This adds it.
> Add CI service account for DnT-Dev

- sceptre/scipool/templates/sc-scheduled-jobs-launchrole.yaml
We need to give the SC launch role access to the secrets
manager to allow it to update secrets that are passed in
from the service catalog wizard.
> [IT-1931] Allow SC launch role access to secrets manager

- sceptre/scipool/config/bmgfki/sc-product-s3-synapse.yaml
- sceptre/scipool/config/develop/sc-product-s3-synapse.yaml
- sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
- sceptre/scipool/config/strides/sc-product-s3-synapse.yaml
Remove bucket ACL setting in service catalog s3 products
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/281
> [IT-2075] Update S3 products

- sceptre/scipool/config/bmgfki/cfn-cr-sc-bucket-policy.yaml
- sceptre/scipool/config/develop/cfn-cr-sc-bucket-policy.yaml
- sceptre/scipool/config/prod/cfn-cr-sc-bucket-policy.yaml
- sceptre/scipool/config/strides/cfn-cr-sc-bucket-policy.yaml
Update the service catalog bucket policy generator lambda to support
non ACL based buckets.
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-bucket-policy/pull/7
> [IT-2075] Update bucket policy generator lambda

- org-formation/600-access/_tasks.yaml
We gave our Gen UI collaborator access to our AWS org-sagebase-agora-dev
account to help migrate the Agora app there.  Now that it's done we
are removing their access.
> Remove Agora collaborator access

- sceptre/admincentral/templates/iam-policies.yaml
We are getting an error when runing `sam validate` using the
current CFN policy..
```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListPolicies
operation: User: arn:aws:sts::XXXXX4268:assumed-role/service-accounts-CfnDeployerServiceRole-1OJK3OAN1IAI/botocore-session-1661992869
is not authorized to perform: iam:ListPolicies on resource: policy path / because no
identity-based policy allows the iam:ListPolicies action
```
Update the CFN deployer policy to allow running the command
to validate sam templates
> Update CFN deployer policy

- org-formation/040-budgets/_tasks.yaml
- org-formation/_parameters.yaml
Now that we have a template in S3 for the cost report lambda,
deploy it to the same account as the cost report bucket.
> [IT-1046] Deploy cost report lambda

- org-formation/040-budgets/_tasks.yaml
Event bridge does not support suffix matching of event details, only prefix matching. This won't work for our needs, roll back the lambda while triggering is reworked.
> [IT-1046] Roll back cost report lambda

- org-formation/300-account-defaults/_tasks.yaml
- org-formation/_parameters.yaml
Deploy the ebs cleanup lambda to all member accounts under the `organizations` account.
Depends on: Sage-Bionetworks-IT/lambda-ebs-cleanup#1
> [IT-2051] Add EBS cleanup lambda to organizations accounts

- org-formation/040-budgets/_tasks.yaml
- org-formation/040-budgets/cur.yaml
Add the cost report lambda to the budgets tasks, and trigger the lambda with S3 notifications for files written by AWS Billing.
Depends on: Sage-Bionetworks-IT/lambda-cost-reports#4
> [IT-1046] Deploy cost reports lambda with S3 notifications

- org-formation/600-access/_tasks.yaml
This PR should give external collaborator access to the iAtlas account.
> IT-2142: Give cross account access to external dev

- org-formation/organization.yaml
This PR is related to IT-1729 and IT-2089
We want to setup a few new system management services:
* AWS instance scheduler service[1]
* AWS centralized patching service[2]
These services will manage instances across multiple AWS accounts so we need a central account to deploy these apps to.  I propose we create a new account called `org-sagebase-sysmancentral` for these types of services.  That way we can scope their access to systems operators.
[1] https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/welcome.html
[2] https://aws.amazon.com/blogs/mt/scheduling-centralized-multi-account-multi-region-patching-aws-systems-manager-automation/
> Create a system manager account

- sceptre/synapsedev/config/prod/vpc.yaml
This PR is trial run for using the parameter, the security group should be removed and the corresponding securityHub finding should go away.
> IT-2002: Remove bastion security group from sageVPC in synapsedev account

- sceptre/synapsedw/config/prod/vpc.yaml
- sceptre/synapseprod/config/prod/vpc.yaml
Same as https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/581 for prod and dw accounts.
Depends on Sage-Bionetworks/aws-infra#355
> IT-2002: Remove bastion sg from infra vpc in synapsepro and dw

- .github/workflows/aws-deploy.yaml
There is a new obsolete stack feature[1] in sceptre v3.2.0 that allows us to setup automated deletion of stacks in our CI/CD pipeline.
Add a `--prune` flag to allow sceptre to automatically delete stacks when they are marked as `obsolete`.
[1] https://docs.sceptre-project.org/3.2.0/docs/faq.html?highlight=prune#my-ci-cd-process-uses-sceptre-launch-how-do-i-delete-stacks-that-aren-t-needed-anymore
> Update sceptre to automatically remove CFN stacks

- sceptre/synapsedev/config/prod/vpc.yaml
This PR is part of the effort to remover references to 10.1.0.0/16 in security groups.
Depends on sage-bionetworks/aws-infra#356
> IT-2030: update vpc.yaml in synapsedev

- org-formation/organization.yaml
The idea behind identity-central is to have an AWS account that’s basically a shell account containing only IAM users and nothing else.  The purpose is to allow these IAM users to access resources in other AWS accounts but not resources in the identity-central account. Identity-central would be integrated with our Jumpcloud IDP so that we can manage AWS IAM users via Jumpcloud.
> [IT-1967] Create an identity central account

- org-formation/090-systems-manager/_tasks.yaml
The patching configuration was set to only scan for patches, we change it to install patches on instances.  Also changed setting to reboot instance after patching if needed. Instance are marked as non-compliant until a subsequent reboot and scan
> [IT-2089] Update patching configs

- org-formation/090-systems-manager/_tasks.yaml
The multi-account patch manager will assume a role in each member account then execute patching on each account.  Therefore the resource group needs to be defined in each account so that the patch manager can use the resource group to identify the resources that it needs to patch.
> [IT-2089] Create the resource group in all member accounts

- org-formation/700-aws-sso/_tasks.yaml
Create an integrated Jumpcloud role to allow identity-central users to access S3 buckets in other accounts.  This role was tested in PR #597 and it worked as expected.
depends on #602
> [IT-1967] identity-central role for external collaborators

- org-formation/050-costs/_tasks.yaml
- org-formation/050-costs/categories.yaml
- org-formation/050-costs/program-code-rules.json
Replace our CUR ETL lambda with Cost Category rules. The purpose of the lambda is simply to collate our CostCenter and CostCenterOther tags, along with a fallback account mapping, into a single meaningful value. This can also be done with Cost Categories, which would allow us to use Cost Explorer for auditing/inspecting the resulting data.
The included rules were built using the online rules builder and copying the resulting JSON. Automatically updating the rules when program codes change will be challenging, but might be possible using a custom CloudFormation macro.
> [IT-2124] Add a Cost Category for Program Codes

- org-formation/090-systems-manager/patch-resource-group.yaml
We apply tags to EC2 to identify which EC2s need patching.  The problem
is that the tags are also propogated to the EC2s attached volumes.
This means that the patch group query will return EBS volumes for
patching which will fail.  We narrow the scope of the query so that
only instances are returned to the patch manager to run patch update on.
> [IT-2089] narrow resource group for patching

- sceptre/scicomp/config/prod/computevpc.yaml
This PR removes access from 10.1.0.0/16 in computevpc-VpnSecurityGroup-16YU33HUVTTRL SG. Same as previous ones.
> IT-2030: Update scicomp/computevpc

- sceptre/scipool/config/bmgfki/gatespoolvpc.yaml
- sceptre/scipool/config/prod/internalpoolvpc.yaml
- sceptre/scipool/config/strides/stridespoolvpc.yaml
This PR updates the VPCs in scipool/prod to 4.10 to remove 10.1.0.0/16 from VpnSecGroup. Same as previous ones, should be last ones.
> IT-2030: Update VPC

- sceptre/scipool/config/bmgfki/cfn-cr-sc-bucket-policy.yaml
- sceptre/scipool/config/develop/cfn-cr-sc-bucket-policy.yaml
- sceptre/scipool/config/prod/cfn-cr-sc-bucket-policy.yaml
- sceptre/scipool/config/strides/cfn-cr-sc-bucket-policy.yaml
This updates the bucket lambda in the service catalog with changes
from https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-bucket-policy/pull/9
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-bucket-policy/pull/9
> Update bucket policy lambda

- org-formation/600-access/_tasks.yaml
The managed-policy template expects the PolicyDocument to be a JSON string, not a template snippet.
This has been manually verified with `npm run validate-tasks`
> [IT-1532] The Policy Document should be a JSON string

- org-formation/600-access/_tasks.yaml
Correctly set organization bindings to create cost explorer managed policies in all member accounts.
> Correct managed policy org binidngs

- org-formation/060-cloudtrail/cloudtrail-trail.yaml
AWS docs says the `ExpiredObjectDeleteMarker` cannot be specified with ExpirationInDays, ExpirationDate, or TagFilters[1]
This attempts to fix the failure from AWS:
```
The XML you provided was not well-formed or did not validate against
our published schema (Service: Amazon S3; Status Code: 400; Error Code:
MalformedXML; Request ID: 1GH83JZQPKJ8V54M; S3 Extended Request ID:
l/W7yBf+gvXSD+f/A/4OjMkonl5LuriZY4mckuIht3Z1CtFdGqw/x0PnqZ+xavaaYkq54urfPcE=; Proxy: null)
```
[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule.html#cfn-s3-bucket-rule-expiredobjectdeletemarker
> Fix S3 data lifecycle rule

- org-formation/organization.yaml
Reduce the cloudwatch retention period for cloudtrail to 90 days (our default) as suggested by our CISO.
In addition to cloudwatch we have the cloudtrail logs going to a central S3 bucket and have
setup on a lifecycle policy in PR #619
> [IT-2139] Update cloudwatch retention for cloudtrail

- org-formation/organization.yaml
Remove saturncloud account from org-formation control. This will also require a manual step to close the account[1]
[1] https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_close.html
depends on #627
> [IT-1960] Decommision saturncloud account

- sceptre/scipool/config/bmgfki/gatespoolvpc.yaml
- sceptre/scipool/config/develop/cesspoolvpc.yaml
- sceptre/scipool/config/develop/scheduledjobsvpc.yaml
- sceptre/scipool/config/prod/internalpoolvpc.yaml
- sceptre/scipool/config/prod/scheduledjobsvpc.yaml
- sceptre/scipool/config/strides/scheduledjobsvpc.yaml
- sceptre/scipool/config/strides/stridespoolvpc.yaml
Remove bastian ssh access from `internalpoolvpc` and `scheduledjobsvpc`, ssh access is still available from the vpn.
depends-on: https://github.com/Sage-Bionetworks/aws-infra/pull/361
> [IT-2221] Restrict ssh access to scipool prod

- org-formation/organization.yaml
Setup our organization accounts to Only allow using AWS in US regions. Deploying to regions outside of the US will need to be managed as an exception case.
> [IT-1766] Setup region restrictions

- org-formation/organization.yaml
AWS only allow attaching 5 SCPs per OU[1] to work around this quota
we need to move some SCPs to the root level.
* Group accounts definitions together
* Move common SCP to root OU
Note: this is a redo of PR #624
[1] https://docs.aws.amazon.com/organizations/latest/userguide/orgs_reference_limits.html
> [IT-1766] Refactor organization SCPs

- sceptre/scipool/templates/sc-kms-key.yaml
Enable key rotation for KMS key used for the Service Catalog in org-sagebase-scipooldev, org-sagebase-scipoolprod, org-sagebase-strides, and org-sagebase-bmgfki accounts
> [IT-2317] Enable KMS key rotation

- org-formation/800-redirects/README.md
- org-formation/800-redirects/_tasks.yaml
- org-formation/_tasks.yaml
- sceptre/bridge/templates/essentials.yaml
The SSO URL is difficult to remember so we are setting up an easier to remember URL to redirect to the SSO endpoint.
> [IT-1749] Setup redirect to SSO URL

- org-formation/060-cloudtrail/_tasks.yaml
- org-formation/060-cloudtrail/cloudtrail-trail.yaml
We setup multi-account cloudtrail in a management and member configuration. This requires enabling cloudtrail on every account.  We only setup encryption on the management account's cloudtrail.  This will enable KMS encryption to all member accounts as well.
> [IT-2327] Enable cloudtrail log encryption

- sceptre/admincentral/config/prod/essentials.yaml
- sceptre/imagecentral/config/prod/essentials.yaml
- sceptre/itsandbox/config/prod/essentials.yaml
- sceptre/logcentral/config/prod/essentials.yaml
- sceptre/organizations/config/prod/essentials.yaml
- sceptre/sageit/config/prod/essentials.yaml
- sceptre/sandbox/config/prod/essentials.yaml
- sceptre/scicomp/config/prod/essentials.yaml
- sceptre/scipool/config/bmgfki/essentials.yaml
- sceptre/scipool/config/develop/essentials.yaml
- sceptre/scipool/config/prod/essentials.yaml
- sceptre/scipool/config/strides/essentials.yaml
- sceptre/securitycentral/config/prod/essentials.yaml
- sceptre/strides-ampad-workflows/config/prod/essentials.yaml
- sceptre/strides/config/prod/essentials.yaml
- sceptre/synapsedev/config/prod/essentials.yaml
- sceptre/synapsedw/config/prod/essentials.yaml
- sceptre/synapseprod/config/prod/essentials.yaml
essentials.yaml is a legacy template we used to setup some essential resources in all accounts.  Some of those resources have been subsumed by orgformation deployments.  This is pulling in a new version of essentails.yaml to do some cleanup. Specifically it pulls in the following updates..
* https://github.com/Sage-Bionetworks/aws-infra/pull/362
* https://github.com/Sage-Bionetworks/aws-infra/pull/364
* https://github.com/Sage-Bionetworks/aws-infra/pull/365
> Update essentials resources

- sceptre/logcentral/config/prod/sumologic-role-s3cloudtrail.yaml
- sceptre/logcentral/config/prod/sumologic-role-s3config.yaml
These roles were setup to allow sumologic to ingest cloudtrail and config logs so that our security
engineer can use sumologic to query the logs. Requirements have changed and our previous
security guy has moved on therefore we don't really need this anymore.  Removing sumologic will
reduce cost and make the setup more simple.
> Remove sumologic role

- sceptre/synapsedev/templates/accounts.yaml
This PR adds permissions needed by developers (already added to test) and exports the policy to allow the SSO dev group to gain same right (more prep to replace IAM users by IAM service accounts).
> IT-2344: Add perms and export policy

- org-formation/720-client-vpn/vpn.yaml
The security group is applied to the VPC that VPN clients land on after authenticating. This VPC does not need to allow inbound connections since the only hosts on the subnet are VPN clients.
The routing table only has a configuration for local traffic, restrict the security group similarly.
> [IT-2248] Align Security Group with Routing Table.

- org-formation/organization.yaml
Hello,
I'm opening this PR to create a production AWS account. This production account paired with the development account will house all the ETL work required for the RECOVER project, such that all the work done in these accounts will be charged to the RECOVER grant.
See [PR #649](https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/649) for the PR creating the corresponding development account.
PR Checklist:
> [ETL-275] Add recover production account under ScienceProdOU

- org-formation/organization.yaml
Hello,
I'm opening this PR to create a development AWS account. This development account paired with the production account will house all the ETL work required for the RECOVER project, such that all the work done in these accounts will be charged to the RECOVER grant. 
See [PR #650](https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/650) for the PR creating the corresponding production account.
PR Checklist:
> [ETL-275] Add recover development account under ScienceDevOU

- org-formation/organization.yaml
We need to disable the SCP to restrict disabling guard duty because that is preventing our automation to setup GD when vending new AWS accounts.  When the automation creates new accounts it sets up GD and integrates it with the GD in the management account (securitycentral)
> Disable SCP to restrict guardduty changes

- org-formation/organization.yaml
We need to disable the SCP to restrict disabling aws config and cloudtrail because that is preventing our automation from setting up those services when we vend new AWS accounts.
> Disable SCP to restrict cloudtrail and config updates

- org-formation/080-aws-config-inventory/_tasks.yaml
This fixes AWS config deployment which was failing when vending new AWS accounts. Update aws config template with updated role name.  The AWS built in role name was deprecated and replaced with AWS_ConfigRole.
The build failed with following message..
```
Policy arn:aws:iam::aws:policy/service-role/AWSConfigRole does not exist or is not attachable
```
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/369
> Fix aws config deployment

- sceptre/scipool/config/bmgfki/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/develop/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/prod/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/strides/sc-product-ec2-windows-jumpcloud.yaml
This PR updates the dependency on sc-ec2-windows-jumpcloud.yaml to v1.1.44 (remove the user association step).
Depends on Sage-Bionetworks/service-catalog-library#288
> SC-404: Update dependency version

- org-formation/050-costs/_tasks.yaml
Deploy the initial version of our microservice for transforming chart of accounts data from mips. Once created, one of the listed admins will need to populate the following SSM secure parameters with appropriate mips credentials: `/lambda/mipsSecret/user`, `/lambda/mipsSecret/pass`.
> [IT-1655] Deploy initial mips microservice

- org-formation/060-cloudtrail/_tasks.yaml
- org-formation/080-aws-config-inventory/_tasks.yaml
We are required to keep 90 days of cloudtrail logs for quering[1] which is what we have setup in watchwatch.  This means that we no longer need sumologic for querying the entire history of cloudtrail logs.  This removes sumologic integration with AWS cloudtrail and AWS configs.
[1] https://sagebionetworks.jira.com/browse/IT-2139
> Remove sumologic integration

- org-formation/070-guard-duty/_tasks.yaml
Add a bucket policy that requires HTTPS when accessing the list of IPs for GuardDuty to ignore.
Depends on: Sage-Bionetworks/aws-infra#370
> [IT-2431] Require HTTPS for GuardDuty bucket

- org-formation/200-baseline/_tasks.yaml
Update the password policy template to ver 0.6.1 which contains
```
PasswordReusePrevention: 24
```
That parameter was added in commit [f24cb41d](https://github.com/Sage-Bionetworks/aws-infra/commit/f24cb41ded8a1bf909177f49cc98f494a4069b7d) which will prevent password reuse.
> [IT-2394] Update AWS password policy

- org-formation/700-aws-sso/_tasks.yaml
Hi,
This PR builds on top of now merged [#650](https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/650) and sets up access to the AWS account via JumpCloud.
Ideally, admin, developer and viewer roles are created.
A blank placeholder document (for the purpose of creating the initial PR and will be deleted later prior to merging) has been generated at _/.../org-formation/600-access/etl_275_blank_file.txt
PR Checklist:
> [ETL-275] Set up JumpCloud access for RECOVER Prod account

- org-formation/650-identity-providers/_tasks.yaml
**Purpose:** Setup OIDC integration with an IAM role that a certain GitHub repo’ can assume to allow GitHub to deploy to the Recover AWS account.
See [#673](https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/673) for the previous course of action leading to this decision. 
PR Checklist:
> [ETL-309] Add oidc integration for recover

- sceptre/synapsedev/templates/accounts.yaml
This PR is an attempt to create a service IAM account to support a developer user's stack. This should pass the SCP blocking creation of user profiles.
> Add service user for Leon's stack'

- org-formation/650-identity-providers/_tasks.yaml
- org-formation/650-identity-providers/github-oidc-provider-access.j2
- org-formation/650-identity-providers/oidc-provider-access.j2
- org-formation/650-identity-providers/oidc-provider.yaml
The current implementation of the template for github OIDC
creates multiple AWS::IAM::OIDCProvider with the same URL
which is not allowed in AWS.  This refactor will allow
us to decouple the creation of the OIDC provider with
setting up repos to access AWS using a single github OIDC
provider.
related to ETL-309
> Refactor GitHub OIDC

- sceptre/synapseprod/config/prod/vpc.yaml
This PR removes the infra VPC at 10.10.0.0/16 using the new 'obsolete' feature
Depends on #587
> It-2147: Remove old infra VPC

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
I re-introduced the dependency by having the function name == resource name and referencing the function in the policy definition. Now hardcoding the function name in both the function and the policy.
> IT-1756: Fix circular dependency

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
This PR suppresses the findings for CIS1.4 (rotate IAM keys < 90 days) for bootstrap accounts and any service accounts.
Human accounts (synapseprod/dev/dw) are being decomissioned and the associated findings will disappear as they are.
> IT-2308: Add suppress rule for CIS1.4

- org-formation/720-client-vpn/_tasks.yaml
The VPN server certificate expired which caused the AWS client VPN to fail to connect with message..
"Connection failed because of a TLS handshake error"
The certificate was manually generated and deploy from AWS instruction: https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-getting-started.html#cvpn-getting-started-certs
> Update Sage VPN certificate

- org-formation/720-client-vpn/_tasks.yaml
The current certificate was good for 2 years.  We created new one that's good for 5 years.  Use the 5 year certificate instead.
> replace VPN server certificate

- org-formation/650-identity-providers/_tasks.yaml
OIDC integration to allow the `schematic-infra` repo' to deploy to the D&T dev' account.
> DCA-51 adding OIDC integration for Schematic stack deployment

- org-formation/_platform_org_tags.yaml
- org-formation/organization.yaml
YAML does not allow multiple `>>:` occurrences at the same level, duplicate the CloudwatchCloudTrailLogRetentionPeriod key in the included file so that we only include a single file.
> bugfix: correctly apply platform account tags

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
This PR adds a bucket and a generatorId for cis-aws-foundations-benchmark/v/1.4.0/2.1.5.2 to the existing rule. We suppress findings about infra buckets being public in any account.
> IT-2429: Add rule to suppress findings for cf-templates bucket being public

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
This PR adds a generatorId for cis-aws-foundations-benchmark/v/1.4.0/3.7(Cloudtrail logs encryption) to be suppressed for all accounts. This is the same resolution as arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0/rule/2.7.
> IT-2427: Add generatorId

- org-formation/600-access/_tasks.yaml
- org-formation/700-aws-sso/_tasks.yaml
- sceptre/strides-ampad-workflows/templates/jumpcloud-idp.yaml
- sceptre/strides/templates/jumpcloud-idp.yaml
AWS has deprecated several IAM actions, including `aws-portal:*`, remove occurrences of `aws-portal:ViewUsage` from cost-explore policies because it is no longer needed, and replace occurrences of `aws-portal:ViewBilling` with appropriate actions from `billing`, `consolidatedbilling`, and `freetier`.
Also align strides community manager role with the org-formation role by granting billing access.
Announcement:
https://aws.amazon.com/blogs/aws-cloud-financial-management/changes-to-aws-billing-cost-management-and-account-consoles-permissions/
> [IT-2607] Remove deprecated `aws-portal:*` actions

- org-formation/700-aws-sso/_tasks.yaml
JSON does not allow trailing commas in lists.
ERROR: Resource PermissionSet failed because Resource handler returned message: "Invalid PermissionsPolicy JSON {
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"billing:GetBilling*",
"consolidatedbilling:Get*",
"consolidatedbilling:List*",
"cur:DescribeReportDefinitions",
"cur:PutReportDefinition",
"cur:DeleteReportDefinition",
"cur:ModifyReportDefinition",
"freetier:Get*",
],
"Resource": "*"
}
]
}.
> bugfix: correct JSON syntax

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
This PR suppresses the finding for CIS 2.1.5.1 (Block all on S3 at account level. I put it in the same rule as the ones that work at the bucket level, it should work because only that combo generatorId/resourceId should match, renamed the description accordingly. Not sure why other accounts did not get flagged (checked SecHub). Note: S3 behavior is changing to block all access by default so I'd expect this control to disappear in future version of CIS.
> IT-2428: Suppress CIS2.1.5.1 for securitycentral

- org-formation/800-redirects/_tasks.yaml
Create a friendly CNAME (finops-api.sageit.org) for the lambda-mips-api Cloudfront distribution.
depends on: Sage-Bionetworks-IT/lambda-mips-api#11 Sage-Bionetworks/aws-infra#372
> [IT-2594] Add finops-api.sageit.org DNS name

- sceptre/synapsedw/config/prod/bootstrap.yaml
- sceptre/synapsedw/config/prod/essentials.yaml
- sceptre/synapseprod/config/prod/bootstrap.yaml
- sceptre/synapseprod/config/prod/essentials.yaml
This PR should remove the BootstrapTravisUser from the synapseprod/synapsedw accounts, it also removes the VPC peering authorizer role from the accounts (IT-2636).
Note1: The BootstrapTravisUser has not been used in these accounts since 2020 (see IT-2635)
Note2: Per comments in bootstrap.yaml, the BootstrapTravisUser should be stripped from groups etc. prior to merging/deploying.
> IT-2308/2309: Update bootstrao/essentials version

- org-formation/050-costs/_tasks.yaml
- org-formation/800-redirects/_tasks.yaml
Give the sageit ACM cert to the mips cloudfront distribution, not to the CNAME record.
> [IT-2594] Move ACM certificate to Cloudfront

- org-formation/050-costs/_tasks.yaml
Cloudfront needs to be given an ACM certificate in the same account. Remove cross-account reference to ACM cert.
> [IT-2549] Remove ACM cert from mips microservice

- sceptre/synapsedw/config/prod/essentials.yaml
- sceptre/synapseprod/config/prod/essentials.yaml
This PR removes the parameter for the peering account to match the new version of the essentials.yaml template.
Missed in previous PR...
> IT-2308: Remove param

- org-formation/700-aws-sso/_tasks.yaml
This PR defines the 'application manager' roles which lets the creator of an application deployed to AWS monitor it and set up secrets.  The PR also deploys the role to the DnT dev and DCA prod accounts
> DCA-35: Add application manager role to D&T dev and DCA Prod accounts

- org-formation/700-aws-sso/_tasks.yaml
* fix typo
* org-formation requires `TemplatingContext` parameter when passing a nunjucks file[1].
[1] https://github.com/org-formation/org-formation-cli/blob/master/docs/task-files.md#templating
```
Note: If you want templating without passing in any data you must
set TemplatingContext: {} to trigger templating.
```
> Fix deployment failure

- package-lock.json
- package.json
CDK deployments report the following message..
```
AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap'
with a recent version of the CDK CLI.
```
Fix by updating the CDK and boostrap template.
> update AWS CDK version

- org-formation/650-identity-providers/_tasks.yaml
Allow github action from the Sage-Bionetworks/data_curator-infra repo to deploy to the AWS org-sagebase-dca-prod account.
> [DCA-34] Setup GH OIDC for data_curator-infra

- org-formation/650-identity-providers/_tasks.yaml
Allow github action from the Sage-Bionetworks/schematic-infra repo to deploy to the AWS org-sagebase-dca-prod account.
> [DCA-34] Setup GH OIDC for schematic-infra

- sceptre/imagecentral/config/prod/essentials.yaml
- sceptre/itsandbox/config/prod/essentials.yaml
- sceptre/logcentral/config/prod/essentials.yaml
- sceptre/sageit/config/prod/essentials.yaml
- sceptre/synapsedev/config/prod/essentials.yaml
This PR updates the version of essentials.yaml (which will cause the removal of the authorizer role as well as remove the permissions to the bootstrapTravisUser account). The AWS accounts in this PR should not be affected by the changes (i.e. no sign of the bootstrapTravisUser having run recently).
> IT-2636: Remove VPCAuthorizer role by updating essentials version

- sceptre/synapseprod/templates/accounts.yaml
This PR removes some IAM accounts from SynapseProd to resolve SecurityHub findings. A couple of other accounts will be put in compliance by updating the creds and rotating the access keys (and ultimately all will be replaced by SSO access).
> IT-2393: Remove IAM accounts

- org-formation/800-redirects/_tasks.yaml
Now that we have created a wildcard certificate for our application subdomain and are using it in our application, set up a CNAME redirect so that the application domain matches the certificate domain.
Depends on: https://github.com/Sage-Bionetworks/data_curator-infra/pull/29
> [DCA-37] Add CNAME for dca-test application

- org-formation/650-identity-providers/_tasks.yaml
For deployments where there is a more involved change to the infrastructure we may want to manage the deployment of that change to one account/environment (dev) before propogating it to other accounts (prod).
For this we setup multiple git branches (dev/stage/prod) to allow us to propogate the deployments which means we need to allow OIDC to deploy from multiple branches.
> [DCA-34] Allow deployment from multiple branches

- org-formation/650-identity-providers/github-oidc-provider-access.njk
The policy to allow multiple branches to access AWS was not correct. We fix it as documented in GH OIDC docs[1]
Note:
AWS does not support lists in `StringEquals` or `StringLike` conditions.
AWS supports matching either a single branch (i.e. main) or all branches
(i.e. *) per OIDC resource.  If we want to match multiple single branches
(i.e. dev/prod/etc..) we would need to deploy an OIDC resource for every
each branch.
[1] https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
> [DCA-34] fix github oidc role

- sceptre/imagecentral/config/prod/bootstrap.yaml
- sceptre/itsandbox/config/prod/bootstrap.yaml
- sceptre/logcentral/config/prod/bootstrap.yaml
- sceptre/sageit/config/prod/bootstrap.yaml
- sceptre/synapsedev/config/prod/bootstrap.yaml
This PR updates the bootstrap.yaml version, which removes the bootstrapTravisUser.
Depends on #732 to remove a dependency first.
> IT-2635: Update bootstrap version to remove boostrapTravisUser

- org-formation/100-shared-dns/README.md
- org-formation/100-shared-dns/_tasks.yaml
Once this certificate has been manually validated, it can be added to the mips microservice cloudfront distribution.
> [IT-2594] Create new certificate for *.sageit.org

- org-formation/050-costs/_tasks.yaml
Once the ACM certificate in the dependent PR has been manually
validated, attach it to the cloudfront distribution in front of our
finops api lambda.
Depends on: #726
> [IT-2594] Attach ACM cert to cloudfront

- org-formation/650-identity-providers/_tasks.yaml
- org-formation/650-identity-providers/github-oidc-provider-access.njk
This PR moves the parameter GitHubOrg to the templating context to fix the deployment issue.
> IT-2672: Move GitHubOrg to templating context

- org-formation/650-identity-providers/github-oidc-provider-access.njk
When passing in `branch: "*"` the jinja template generates this condition..
```
Condition:
StringEquals:
token.actions.githubusercontent.com:aud:
Ref: ClientIdList
StringLike:
token.actions.githubusercontent.com:sub:
- repo:Sage-Bionetworks/data_curator-infra:*
- repo:Sage-Bionetworks/data_curator-infra:ref:refs/tags/*
```
the condition `repo:Sage-Bionetworks/data_curator-infra:*` covers any branch or tag so the one for `ref:refs/tags/*` is not required.
> Fix policy template for GH OIDC

- org-formation/700-aws-sso/_tasks.yaml
An attempt to setup an IPAM viewer role in commit d7ebfee3 to allow read only access to the IP Address Manager did not work. This is another attempt except this time we provide access with the viewer plus role.
> Create an IPAM viewer plus role in SSO

- org-formation/700-aws-sso/_tasks.yaml
Commit 8bb7131d2 attempted to give the SsoViewerPlus role read only access to the IP address manager however it did not provide enought permissions.  To view IPAM the role also needs access to `EC2:Get*` actions[1]
[1] https://docs.aws.amazon.com/AWSEC2/latest/APIReference/operation-list-ipam.html
> Update SSO viewer plus role

- org-formation/650-identity-providers/_tasks.yaml
This PR sets up OIDC for the scicomp-provisioner repo. To be used for moving provisioning from TravisCI to GHA.
> IT-2673: OIDC for scicomp-provisioner repo

- sceptre/synapsedev/templates/SynapseCMK-template.json
- sceptre/synapseprod/templates/SynapseCMK-template.json
This PR adds permissions to the deployment role. Note: this does not get deployed by infra (see PFLM-7725 to fix that).
The key rotation did not get deployed so I removed it to be in sync with deployed, will put it back after PLFM-7725 is done.
> PLFM-7700: Add wafv2:* perms

- org-formation/050-costs/categories.yaml
A similar cost category was created manually, copy the JSON string from the existing category to automate its creation.
> [IT-2370] Create 'Owner Email' cost category

- org-formation/050-costs/categories.yaml
The JSON editor in the AWS console for editing cost category rules provides a context Rules key that we don't want to copy.
> Remove duplicate Rules key

- org-formation/650-identity-providers/_tasks.yaml
Add OIDC integration to deploy Genie-BPC Shiny application from GitHub to AWS
> IT-2426: Add OIDC integration to deploy Genie-BPC Shiny application

- org-formation/800-redirects/_tasks.yaml
DNS records are managed in the SageIT account.
> Create cname stack in correct account

- org-formation/100-shared-dns/README.md
- org-formation/100-shared-dns/_tasks.yaml
Prepare for having two finops lambdas under the same domain by creating a zone and wildcard cert for `finops.sageit.org`, replacing the secondary wildcard certificate for `sageit.org`.
> [IT-2594] Rename host for lambda-mips-api

- org-formation/800-redirects/_tasks.yaml
We don't have the ability to point the different genie applications (dev and prod) at different datasets, and running both on the same dataset would be problematic. Remove the dev application stack (which has already been manually deleted).
> Remove Genie-BPC dev stack

- org-formation/650-identity-providers/_tasks.yaml
PR Checklist:
[x] Describe and explain your intentions for this change
See [IT-2744](https://sagebionetworks.jira.com/browse/IT-2744)
[SageAccountWeb](https://github.com/Sage-Bionetworks/SageAccountWeb) had its deployments configured by AWS credentials that were manually supplied to the repo.
That repository has been moved, to [synapse-web-monorepo](https://github.com/Sage-Bionetworks/synapse-web-monorepo), so it needs to be reconfigured. Rather than a manual reconfiguration, I'm trying to get this direct OIDC  integration set up. The current deployment script is [here](https://github.com/Sage-Bionetworks/synapse-web-monorepo/blob/main/.github/workflows/deploy-sage-account-web.yml).
This is my first pass, but I don't really …
> IT-2744 - Add GitHub OIDC integration for synapse-web-monorepo

- org-formation/050-costs/_tasks.yaml
- org-formation/800-redirects/_tasks.yaml
The mips-api lambda template does not support deploying multiple stacks to the same account. Roll forward through the error, using the new dns name for the lambda.
> Remove duplicate mips-api deploy

- org-formation/600-access/_tasks.yaml
The previous attempt (#773, #774) created a user, a role and the permission for the user to assume the role. For Redash, the permissions need to be directly on the user. This PR uses the service-user.yaml template which does just that...
> IT-2752: Need service-user instead of service-account

- org-formation/650-identity-providers/_tasks.yaml
To run load balancing experiments in DCA-130 we would like to deploy a 'simple Shiny' application.  This PR allows the `simple-shiny-infra` repo' to deploy the app' to the DnT account.
> DCA-130:  Enable simple-shiny-infra to deploy to dnt-dev account

- org-formation/800-redirects/_tasks.yaml
For DCA-130 we create two experimental variations of DCA:
(1) Has two (not one) task instances behind the ALB;
(2) Has  two task instances behind the ALB and enables session stickiness.
This PR creates CNAMES for the experimental stacks.
> DCA-130 Adding CNAMES for two experimental DCA deployments

- org-formation/700-aws-sso/_tasks.yaml
This PR creates an AWS admin group in the SynapseDev account (currently we have an admin group that spans the OU). This is to be used by devs in the dev account as we discover which permissions should be added to the developer group.
Also reduced the target of the existing group to SynapseProd only (should rename/replace later for clarity).
> PLFM-7774: Add synapsedev-specific admin group

- org-formation/700-aws-sso/_tasks.yaml
This PR fixes the deployment error. The groups apply to accounts, not OUs.
> PLFM-7774: Account, not OU

- org-formation/700-aws-sso/_tasks.yaml
This PR is a followup to #803, remove the existing shared synapse admin group and replace it with one specific to synapseprod.
> PLFM-7774: Followup - create synapseprod-specific admin group

- sceptre/synapsedev/config/prod/testCMK.yaml
- sceptre/synapsedev/templates/testCMK.json
This is a test PR to create a key in the SynapseDev account that should be accessible by the old AWSIAMAdminRole (to be deleted), myself logged in as SSO and the infra (the deployment should fail if the deployer would not be able to manage the key). If it works, the changes will be merged back in the original script used to deploy the Synapse master key, and that script will be added to the infra
> IT-2651: Test key access by infra

- org-formation/050-costs/_tasks.yaml
Deploy our new lambda for generating cost category rules, deprecating our custom transform macro.
depends on: #775 Sage-Bionetworks-IT/lambda-finops-cost-rules#3 Sage-Bionetworks-IT/lambda-mips-api#13
> [IT-2460] Deploy lambda-finops-cost-rules

- org-formation/700-aws-sso/_tasks.yaml
As part of the DccValidator-Prod account set-up, connect the JumpCloud `aws-dccvalidator-prod-application-managers` group to AWS.
> IT-2770 Set up JumpCloud access to DccValidator-Prod account for application manager

- org-formation/800-redirects/_tasks.yaml
The definition of the DccValidator CNAME fails to build, with an error that the target host zone is not valid.  As an experiment, let's try routing dccvalidator CNAME to Genie application (a different target host zone).
> try routing dccvalidator CNAME to Genie application

- org-formation/800-redirects/_tasks.yaml
IT-2770 As an experiment, try hardcoding GENIE LB CNAME instead of hardcoding the dccvalidator CNAME, which fails.
> IT-2770 try hardcoding GENIE LB CNAME

- org-formation/800-redirects/_tasks.yaml
Now that we've loosened the constraint on the template to match the actual limit, try creating our longer CNAME with the updated template.
> Test longer host name with fixed template

- org-formation/800-redirects/_tasks.yaml
Now that we have [this](https://github.com/Sage-Bionetworks/aws-infra/pull/381) fix we can restore the correct DNS target.
> IT-2770: Restore DNS target for dccvalidator

- org-formation/100-shared-dns/README.md
- org-formation/800-redirects/README.md
Migrate some instructions for CDK certificate and DNS setup from confluence to github.
> [IT-2750] Move CDK admin instructions to org-formation

- org-formation/050-costs/_tasks.yaml
- org-formation/050-costs/categories.yaml
This reverts commit 8eaca408cf6ab9e1cb447144927ab2ffd9563a04.
The change is failing with:
```
ValidationError: Template format error: Parameter 'ProgramCodeRulesJSON' default value '<very long json string>' length is greater than 4096.
```
According to `wc` the string has over 42k characters:
```
wget -qO- https://cost-rules.finops.sageit.org/program-codes | wc
0    3952   42983
```
Revert using the lambda for getting the parameter value.
> Revert "[IT-2460] Migrate from custom transform to lambda  (#809)"

- org-formation/050-costs/_tasks.yaml
The accounts are tagged with AccountOwner tags for this value, so add that to the list.
> Add AccountOwner as an owner-email tag name

- org-formation/050-costs/_tasks.yaml
- org-formation/050-costs/categories.yaml
Switch from hard-coded inherit rules to our rule-generating lambda so that we also add account-tag rules for the category.
> [IT-2369] Use lambda for Owner Email category

- org-formation/700-aws-sso/_tasks.yaml
Give 'application managers' read-only access to Certificate Manager to allow them to configure the CNAME for their CDK-based application.
> IT-2754: Give 'application managers' read-only access to Certificate Manager

- org-formation/650-identity-providers/_tasks.yaml
This PR sets up an OIDC role in the SynapseProd account to allow deployment of the synapse-oauth-signin artifacts to S3 buckets from the synapse-monorepo GH repo.
> PORTALS-2622: Add OIDC for SynapseProd from synapse-monorepo

- sceptre/scipool/templates/sc-s3-launchrole.yaml
Allow the service catalog role to tag the lambda created for restricting region downloads.
> [SC-406] Add needed "lambda:TagResource" permission

- org-formation/700-aws-sso/_tasks.yaml
PLFM-7740
This gives a group, authenticated through JumpCloud, access to the Synapse prod' account, but only for the purpose of running Athena queries related to the Synapse data warehouse.  I.e. the only accessible data source is `AwsDataCatalog`, the only accessible database is `datawarehouse` and the only accessible Work Group is the `primary` workgroup.
> PLFM-7740: Add role to let users access Athena in Synapse prod account

- org-formation/700-aws-sso/_tasks.yaml
Accidentally deployed for all accounts instead of just the Synapse prod account.
> PLFM-7740 fixed account binding

- org-formation/650-identity-providers/_tasks.yaml
Allow dccvalidator_AMP-AD-infra repo' to deploy to AWS using OIDC integration.
> IT-2827: Allow dccvalidator_AMP-AD-infra repo' to deploy to AWS

- .gitignore
- org-formation/800-redirects/_tasks.yaml
Adding CNAME forwarding for AMP-AD dccvalidator/dccmonitor:
dccvalidator-amp-ad-dev.app.sagebionetworks.org
dccmonitor-amp-ad-dev.app.sagebionetworks.org
> IT-2827 Adding CNAME forwarding for AMP-AD dccvalidator/dccmonitor

- org-formation/800-redirects/_tasks.yaml
Adding CNAME forwarding for PROD instances of AMP-AD dccvalidator/dccmonitor
dccvalidator-amp-ad.app.sagebionetworks.org
dccmonitor-amp-ad.app.sagebionetworks.org
> IT-2827: Adding CNAME forwarding for PROD instances of AMP-AD dccvalidator/dccmonitor

- org-formation/650-identity-providers/README.md
- org-formation/650-identity-providers/_tasks.yaml
- org-formation/650-identity-providers/github-oidc-provider-access.njk
Our current GH OIDC template only sets up GH OIDC for a single repository in an GH org.  This causes lots of duplication in the orgf _task.yaml file.  This update will allow setting up OIDC for multiple repos and branches which will allow us to reduce the number of entries in the _task.yaml file.
> [IT-2768] make OIDC template support multi repos

- .github/workflows/main.yaml
- org-formation/650-identity-providers/_tasks.yaml
The deployment for a few of the older AWS accounts could 
not be updated due to a dependency with the essentials stack.
This is a temporary fix to exclude those repos from updating
which will fix the build to give us more time to fix the problem.
> Temporary fix for GithubOidcSageBionetworksIt

- org-formation/650-identity-providers/github-oidc-provider-access.njk
There was a bug in PR #859 where we were setting '*' condition for branches incorrectly.  According to the AWS docs[1], granting access to all branches does not include the refs.
"The following example condition limits access to the defined GitHub organization and repository, but grants access to any branch within the repository"
```
"Condition": {
"StringLike": {
"token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
"token.actions.githubusercontent.com:sub": "repo:GitHubOrg/GitHubRepo:*"
}
}
```
[1] https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html
> Fix github OIDC configuration

- org-formation/650-identity-providers/_tasks.yaml
- org-formation/700-aws-sso/_tasks.yaml
Apparently the AWS built in `Administrator` policy does not provide global access to KMS keys. Getting the following error when attempting to update tags on KMS keys..
```
AWS::KMS::Key UPDATE_FAILED Resource handler returned message:
"Access denied for operation 'UntagResource'."
```
To allow a role to make changes to KMS keys we need to attach the AWSKeyManagementServicePowerUser[1] policy
[1] https://docs.aws.amazon.com/kms/latest/developerguide/aws-managed-policies.html
> Allow SSO admins and GH action access to KMS keys

- sceptre/scipool/config/bmgfki/sc-tag-options-external.yaml
- sceptre/scipool/config/bmgfki/sc-tag-options.yaml
- sceptre/scipool/config/develop/sc-tag-options-external.yaml
- sceptre/scipool/config/prod/sc-tag-options-external.yaml
- sceptre/scipool/config/strides/sc-tag-options-external.yaml
- sceptre/scipool/config/strides/sc-tag-options.yaml
The deployment is failing with message..
```
"An error occurred (ValidationError) when calling the UpdateStack operation:
[/Resources] 'null' values are not allowed in templates"
```
Passing in a value for CostCenters fixes this problem.
> Fix tag option stacks

- sceptre/scipool/config/bmgfki/sc-tag-options-external.yaml
- sceptre/scipool/config/bmgfki/sc-tag-options.yaml
- sceptre/scipool/config/develop/sc-tag-options-external.yaml
- sceptre/scipool/config/prod/sc-tag-options-external.yaml
- sceptre/scipool/config/strides/sc-tag-options-external.yaml
- sceptre/scipool/config/strides/sc-tag-options.yaml
This reverts commit f82730158217b558ce1c29cbc81b072add225fca. 
revert because duplicate tags are not allowed.
```
develop/sc-tag-options-external NOPROGRAM000000CostCenterTag
AWS::ServiceCatalog::TagOption CREATE_FAILED CostCenter|NO PROGRAM / 000000 already exists in stack
arn:aws:cloudformation:us-east-1:465877038949:stack/sc-tag-options/f8245460-6dc8-11ec-a4e0-1289ac4902b3
```
> Revert "Fix tag option stacks (#871)"

- org-formation/650-identity-providers/_tasks.yaml
aws-infra and service-catalog-library repos deploy to the same location.  We consolidate the definition to reduce duplication.
depends on #859
> consolidate GH OIDC definitions

- org-formation/650-identity-providers/_tasks.yaml
DCC apps all deploy to the same accounts so we can consolidate the definition to reduce duplication.
depends on #859
> Consolidate GH OIDC defintions for DCC

- org-formation/650-identity-providers/_tasks.yaml
We no longer need the `simple_shiny` application deployed to the DnT Dev account. 
We no longer need the `s3-file-hosting` application deployed to the Synapse Dev account. 
This PR removes the ability for GitHub to deploy those repo's.
> remove simple-shiny deployment, no longer needed

- org-formation/650-identity-providers/_tasks.yaml
We are going to switch from using Travis to  GH actions to build and deploy packer images.
This configures a GH OIDC to allow packer to deploy AMI images from github repos to the org-sagebase-imagecentral account.
> [SC-380] GH OIDC to deploy AMIs to imagecentral account

- org-formation/650-identity-providers/_tasks.yaml
The `sage-bionetworks/synapser` repo' has a GitHub workflow which generates documentation and writes to a bucket.  Currently access is granted via an IAM user secret.  This PR will allow us to authorize the workflow using OIDC integration and remove the IAM user.
> IT-2111 Allow sage-bionetworks/synapser repo' to write documentation to [staging-]ran.sagebase.org buckets as part of build

- org-formation/650-identity-providers/_tasks.yaml
This sets up github OIDC to allow Sage-Bionetworks-IT/packer-rstudio repo to deploy to AWS org-sagebase-imagecentral account.
> GH OIDC for packer-rstudio repo

- org-formation/650-identity-providers/github-oidc-provider-access.njk
The default role session timeout is 1hr however some CI jobs take longer than that to run.  We setup a MaxSessionDuration parameter so users can pass in a custom timeout for their github OIDC sessions.
> MaxSessionDuration for GH OIDC session

- org-formation/050-costs/_tasks.yaml
The CostCategoryRulesMicroservice lambda parameter was removed[1] but wasn't removed in deployment of the lambda.  We remove it from the deployment to fix the CI deployment[2]
[1] https://github.com/Sage-Bionetworks-IT/lambda-finops-cost-rules/commit/73a87319e00b9e81cfc99d197b143461e7e8a990
[2] https://github.com/Sage-Bionetworks-IT/organizations-infra/actions/runs/5191378925/jobs/9359135735
> Remove CostCategoryRulesMicroservice parameter

- org-formation/077-macie/README.md
- org-formation/077-macie/_tasks.yaml
- org-formation/077-macie/macie.yaml
- org-formation/_tasks.yaml
We setup Macie[1] to scan for security and compliance risks. This setup enables Macie with it's default scanning settings. The configuration may require customizations which can be done with CustomDataIdentifier, AllowLists and Filters.
[1] https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html
> [IT-2883] Setup AWS Macie

- org-formation/600-access/_tasks.yaml
- org-formation/700-aws-sso/_tasks.yaml
The Athena policy was previously defined, in-line, in the IAM Role definition for the Synapse Prod account.
This PR factors out the in-line policy into a separately defined policy and applies it to two roles, one in Synapse dev' and another in Synapse prod'.
The PR also 'links' the Synapse dev' role to a JumpCloud user group, to allow SSO login to the AWS console to access Athena.
> PLFM-7740 Factored in-line policy for Athena access

- org-formation/700-aws-sso/_tasks.yaml
de-duplicate permission set name
The previous build seems to have failed because a second permission set overwrote the first using the same name and rendering the ID of the first one invalid.
> PLFM-7740: de-duplicate permission set name

- org-formation/700-aws-sso/_tasks.yaml
This PR removes sso admin access to a personal AWS account that we are deleting.
See Account Teardown at https://sagebionetworks.jira.com/wiki/spaces/IT/pages/745373697/Setup+AWS+Accounts .
> IT-2693: Remove sso access to personal AWS account

- org-formation/650-identity-providers/_tasks.yaml
- sceptre/strides-ampad-workflows/config/prod/github-oidc-nextflow-infra.yaml
This sets up github OIDC access for the
Sage-Bionetworks-Workflows/nextflow-infra repo.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/395
> GH OIDC for nextflow-infra repo

- org-formation/650-identity-providers/_tasks.yaml
The Sage-Bionetworks/service-catalog-library repo's GH action is throwing the following error..
```
delete failed: s3://bootstrap-awss3cloudformationbucket-19qromfd235z9/service-catalog-library/master/ec2/README.md
An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied
```
The error happens because the GH action attempts to replace files in the template bucket. This change is to address that error by providing object deletion access to the GH OIDC that deploys the files.
> enable object delete and multipart upload permissions

- org-formation/650-identity-providers/_tasks.yaml
The Github OIDC for deployment to cloudformation template is shared by multiple repos (example: aws-infra and service-catalog-library). All repos should have access to the entire repository (bucket).
> expand GH oidc permision for cfn deployment

- org-formation/800-redirects/_tasks.yaml
The schematica-infra deployment failure is causing the reference in this repo to break which is causing the CI for this repo to fail.  Remove the route53 record set until the schematica-infra deployment is fixed.
> temporarily remove SchematicDevAppDnsForward

- sceptre/strides-ampad-workflows/config/prod/github-oidc-nextflow-infra.yaml
- sceptre/strides-ampad-workflows/config/prod/github-oidc-provider.yaml
- sceptre/strides-ampad-workflows/config/prod/github-oidc-sage-bionetworks-it.yaml
Commit bdfc556 had setup github OIDC access for the Sage-Bionetworks-Workflows/nextflow-infra repo.  However that setup didn't work because the template used was not adequate and needed to be reverted in commit f6de736
Now we need to redo the setup for strides-ampad-workflows with the help of PR https://github.com/Sage-Bionetworks/aws-infra/pull/394
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/394
> GH OIDC for deployment to strides-ampad-workflows account

- org-formation/800-redirects/_tasks.yaml
Reverts Sage-Bionetworks-IT/organizations-infra#909
Schematic github action is now working in `schematic-infra`: https://github.com/Sage-Bionetworks/schematic-infra/actions/runs/5380883104
> Revert "temporarily remove SchematicDevAppDnsForward"

- org-formation/650-identity-providers/github-oidc-provider-access.njk
Github requires the AWS OIDC role to have explicit access to github environments as noted in
[GH issue 452](https://github.com/aws-actions/configure-aws-credentials/issues/452). Otherwise the following error will occur when attempting to assume the OIDC role in GH actions..
```
Error: Credentials could not be loaded, please check your action inputs: Could
not load credentials from any providers
```
This change enables GH OIDC access to GH environment.
> GH OIDC access to environments

- org-formation/650-identity-providers/_tasks.yaml
- sceptre/strides-ampad-workflows/config/prod/github-oidc-provider.yaml
- sceptre/strides/config/prod/github-oidc-sage-bionetworks-it.yaml
[GH recommends adding another
thumbprint](https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/) for actions integration with AWS.
> Update thumbprint list for GH OIDC

- org-formation/600-access/_tasks.yaml
This PR gives access to the *firehoselogs schemas in Athena. The policy is used by the SSO group in Synapse.
> PLFM-7908: Add access to *firehoselogs schemas

- org-formation/050-costs/_tasks.yaml
We've replaced the macro that generates rules with a lambda that writes the rules directly to S3. Remove the deprecated macro.
> Remove unused macro

- org-formation/600-access/_tasks.yaml
In PLFM-7886 we are evaluation AWS Quicksight as a data visualization tool for Athena tables, in the Synapse Dev account.  Quicksight uses a particular bucket naming pattern for the queries it saves. This PR adds the requested bucket names to the AWS policy used with Quicksight.
> PLFM-7886: add bucket permissions required by AWS Quicksight

- .github/workflows/main.yaml
The PR #923 forgot to update the role to deploy to strides account which caused
the GH action to fail.  This is the fix
> update role for GH deployment to strides account

- org-formation/050-costs/README.md
- org-formation/050-costs/_tasks.yaml
Canary deployment of a lambda to send monthly email notifications summarizing cloud spend and linking to confluence documentation on how to access AWS Cost Explorer.
Restrict the recipient list to Sage IT as a canary test and to review the content and formatting of the email.
Depends on Sage-Bionetworks-IT/lambda-finops-email-totals#5
> [IT-1532] Send monthly cloud-spend emails

- org-formation/050-costs/_tasks.yaml
Add cost category rules for inactive program codes so that we can track ongoing costs related inactive programs.
Depends on Sage-Bionetworks-IT/lambda-mips-api#19
> [IT-2984] Add rules for inactive codes

- org-formation/organization.yaml
- sceptre/scipool/templates/prod/lambda-budgets/budget-rules.yaml
Removing Larsson Omberg as a notification recipient.
Dccvalidator ownership has been moved into Anna Greenwood's team.
RECOVER SC access is overseen by Solly Sieberts.
> Remove Omberg as a notification recipient

- sceptre/scipool/config/develop/sc-product-scheduled-jobs.yaml
- sceptre/scipool/config/prod/sc-product-scheduled-jobs.yaml
- sceptre/scipool/config/strides/sc-product-scheduled-jobs.yaml
Update memory options for the service catalog scheduled jobs to fix an issue where jobs would be schedule but not run.
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/297
> [IT-3019] update SC scheduled jobs

- org-formation/050-costs/_tasks.yaml
We use AWS::Include in categories.yaml, but CloudFormation will only process stack updates if there are changes to the immediate template, it will not detect changes in the included template. Force org-formation to deploy the stack so that CloudFormation will always process the included template.
> [IT-2984] Force deployment of categories stack

- org-formation/050-costs/_tasks.yaml
Add parameter setting the email recipient for the admin cost report to Sage IT.
> [IT-2978] Send admin cost report to Sage IT

- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
This PR updates the version of service-catalog-library.
Hold until tag v1.2.6 is created.
Depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/301
> SC-383: Update service-catalog-library version

- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
This PR updates the product to v1.2.7 (includes bugfix from https://github.com/Sage-Bionetworks/service-catalog-utils/pull/23).
> SC-383: Bump version for bugfix

- org-formation/_scp.yaml
Remove all references to the deprecated 'aws-portal' actions.
> [IT-2607] Remove all references to 'aws-portal'

- org-formation/organization.yaml
Inherit platform tags on the scipool-dev account so that Sage IT is tagged as the account owner.
> Add AccountOwner tag to scipool-dev account

- sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml
Update the service catalog EC2 docker version to pick up the update from PR https://github.com/Sage-Bionetworks/service-catalog-library/pull/304
> [IT-2871] Update service catalog EC2 docker

- org-formation/650-identity-providers/_tasks.yaml
This PR is similar to #945, it fixes the failure to deploy in https://github.com/Sage-Bionetworks/service-catalog-library/pull/305 (job cannot assume role).
> SC-383: Allow OIDC from branch v1.1.45

- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
Service catalog did not pick up the change from https://github.com/Sage-Bionetworks/service-catalog-library/pull/306 (verified by launching a product on 1.1.45). Verified that the template has been updated in S3.
Usually we'd tag a new version but since 1.1.45 is now broken anyway so adding a random string in the description should force the update.
> SC-383: Force update

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
It is useful to have a security group that allows unrestricted access to port 22 for testing and setting up bastian hosts.  Not to mention that, by default, the AWS security group wizard will create a security group with this access when provisiong a public EC2 instance.
> [IT-3008] Supress Security hub rule

- org-formation/050-costs/_tasks.yaml
Stop restricting the cost summary report to only Sage IT, send monthly summary reports to all tagged owners.
> [IT-1532] Send AWS cost summary to all tagged owners 

- sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
This PR just updates the description to cause a deploy which will pick up the updated template with the RStudio Notebook AMI re-built from tag 2.1.3.
Depends on: https://github.com/Sage-Bionetworks/service-catalog-library/pull/307
> SC-383: Force deploy

- sceptre/scipool/config/bmgfki/sc-product-ec2-linux-jumpcloud-notebook.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-notebook.yaml
This PR just updates the description to cause a deploy to pick up the updated template with the RStudio Notebook AMI re-built from tag 2.1.3.
Depends on: https://github.com/Sage-Bionetworks/service-catalog-library/pull/307
> SC-383: Update notebook product 1.1.45 

- README.md
- org-formation/README.md
Add a table of contents describing the grouping of stacks in the subdirectories under `org-formation/`.
This is intended to make the stacks easier to navigate and to simplify the decision of where to add new stacks.
> Add Org-Formation Overview

- org-formation/050-costs/_tasks.yaml
- sceptre/scipool/config/develop/sc-tag-options.yaml
- sceptre/scipool/config/prod/sc-tag-options.yaml
Prioritize the RECOVER code so that it is listed near the top of the lambda output, ensuring that it is available in the Service Catalog drop-down menu.
Also update mips-api parameters to match name changes happening in the dependent PR.
Depends on Sage-Bionetworks-IT/lambda-mips-api#21
> [IT-3021] Prioritize the RECOVER code

- org-formation/700-aws-sso/_tasks.yaml
Following the info from AWS docs[1] to set permissions to allow the application manager role to start and run ECS tasks
[1] https://docs.aws.amazon.com/AmazonECS/latest/developerguide/security_iam_id-based-policy-examples.html#IAM_run_policies
> [IT-2922] Update application manager SSO role

- org-formation/700-aws-sso/_tasks.yaml
The built in `CloudWatchLogsReadOnlyAccess` does not provide enough permissions to view cloudwatch alarms however the `CloudWatchReadOnlyAccess` does provide appropriate permissions to view alarms.
> [IT-2920] Update application manager role policy

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
Buckets used for cost reporting can be public so we are suppressing the security hub notifications for those buckets.
> [IT-3000] Supress public bucket rule

- org-formation/050-costs/_tasks.yaml
Now that the full finops stack is working end-to-end, tag the lambdas with a 1.0 release and use it.
> Stablize finops lambdas on first release

- org-formation/650-identity-providers/_tasks.yaml
This PR adds OIDC for the [mtb repo](https://github.com/Sage-Bionetworks/mtb) in sageIT account (permissions to deploy artifacts to S3 buckets and create invalidations).
> Add OIDC for mtb repo

- org-formation/725-vpc-flow-logs/README.md
- org-formation/725-vpc-flow-logs/_tasks.yaml
- org-formation/725-vpc-flow-logs/aws-config-rule.yaml
- org-formation/725-vpc-flow-logs/bucket.yaml
- org-formation/README.md
Security hub says we should enable VPC flow logs.  The solution we are going to use to do that is outlined in the AWS blog post[1] on how to enable vpc flow logs automatically using aws config rules. Their implementation uses control tower, ours will use org-formation.
[1] https://aws.amazon.com/blogs/mt/how-to-enable-vpc-flow-logs-automatically-using-aws-config-rules/
> [IT-3090] Use AWS config to enable VPC flow logs

- org-formation/100-shared-dns/_tasks.yaml
- sceptre/sageit/config/prod/bridgedigital_health_r53_zone.yaml
This PR adds a hosted zone for 'bridgedigital.health' in the sageit account.
Once in, we can manually change the name servers at the registrar to use the zone.
> IT-3162: Add hosted zone in sageit

- org-formation/650-identity-providers/_tasks.yaml
- sceptre/strides/config/prod/github-oidc-sage-bionetworks.yaml
In anticipation of moving the service catalog login app to github actions we are setting up GH OIDC access for the repos.
The idea is to be able to allow the login app repos access to the AWS accounts it needs to deploy to (bmgfki, scipooldev, scipoolprod, and strides)
> Setup OIDC access to github for SC login app

- org-formation/650-identity-providers/_tasks.yaml
- sceptre/strides/config/prod/github-oidc-sage-bionetworks.yaml
We deploy the login app to AWS from only two branches develop or prod, one development account and three prod accounts.  Update the OIDC branches accordingly.
> Fix GH OIDC for synapse login app

- org-formation/650-identity-providers/_tasks.yaml
Allow packer-amazonlinux-docker[1] repo to deploy to imagecentral AWS account.
[1] https://github.com/Sage-Bionetworks-IT/packer-amazonlinux-docker
> Setup GH OIDC for packer repo

- org-formation/650-identity-providers/_tasks.yaml
Remove allowing a specific branch to deploy to imagecentral AWS account.  @xschildw set this up for testing which he has since completed.
> update GH OIDC for packer

- org-formation/700-aws-sso/_tasks.yaml
Allow SSO auditor users to view AWS Macie findings.
> [IT-2883] Allow access to AWS Macie

- sceptre/scipool/config/bmgfki/bootstrap.yaml
> [IT-3110] Remove service user

- sceptre/organizations/config/prod/bootstrap.yaml
> [IT-3100] remove service user

- sceptre/scicomp/config/prod/bootstrap.yaml
> [IT-3128] Remove service user

- sceptre/organizations/config/prod/bootstrap.yaml
> [IT-3099] Remove service user

- sceptre/admincentral/config/prod/bootstrap.yaml
> [IT-3165] remove service user

- sceptre/synapseprod/config/prod/snowflake-access.yaml
#990 failed because the account arn was invalid so I replaced it by mine. It is temporary to create the role, then the role arn is sent to Tom who in turns sends back an actual role and externalID.
> PLFM-8054: Use my account as temp

- sceptre/securitycentral/config/prod/bootstrap.yaml
> Remove service user

- org-formation/600-access/_tasks.yaml
Lets Synapse Athena users create workgroups, save queries and save query results as tables in the 'scratch' database.
> PLFM-7806: Additional Synapse Athena permissions

- sceptre/scipool/config/bmgfki/cfn-macro-ssm-param.yaml
- sceptre/scipool/config/bmgfki/sc-kms-key.yaml
- sceptre/scipool/config/develop/cfn-macro-ssm-param.yaml
- sceptre/scipool/config/develop/sc-kms-key.yaml
- sceptre/scipool/config/prod/cfn-macro-ssm-param.yaml
- sceptre/scipool/config/prod/sc-kms-key.yaml
- sceptre/scipool/config/strides/cfn-macro-ssm-param.yaml
- sceptre/scipool/config/strides/sc-kms-key.yaml
We are in the process of switch aws service accounts used by travis with github OIDC roles.  There are still things like lambdas that need assistance from service accounts to deploy resources into AWS.  This is to allow lamdas to use the GH OIDC roles.
> Replace service account

- .github/workflows/main.yaml
We want the CI to only deploy once per merge otherwise the deployments might get into a bad state.
From GH action docs, this change should do the following..
"When a concurrent job or workflow is queued, if another job or
workflow using the same concurrency group in the repository is
in progress, the queued job or workflow will be pending."
[1] https://docs.github.com/en/actions/using-jobs/using-concurrency
> Deploy one merge at a time

- org-formation/650-identity-providers/_tasks.yaml
This PR adds the repo [open-bridge-static](https://github.com/BridgeDigitalHealth/open-bridge-static) and associated permissions to deploy to staging targets to the existing open-bridge-web OIDC.
> IT-3162: Add repo and deployment target to existing OIDC

- sceptre/synapsedev/templates/SynapseCMK-template.json
This  PR (re-)enables key rotation for the synapse-dev-cmk key.
> IT-2789: Enable key rotation

- sceptre/scicomp/config/prod/bootstrap.yaml
This reverts commit 43f713e68ecbcfd74af3902d90623bd6d93fdbfb.
need to revert due to failure..
```
prod/bootstrap bootstrap AWS::CloudFormation::Stack UPDATE_ROLLBACK_IN_PROGRESS
Export us-east-1-bootstrap-CfServiceRoleArn cannot be deleted as it is in use by
bsmnmanifests and htan-synapse-sync-kms-key
```
> Revert "[IT-3128] Remove service user (#1011)"

- org-formation/700-aws-sso/_tasks.yaml
Create separate groups for finance auditors and security auditors. Once these new groups are in place and populated with users, the old auditor group can be deprecated and users removed.
> [IT-3224] Split finance and security auditor groups

- org-formation/700-aws-sso/_tasks.yaml
Now that we have separate groups and roles for finance auditors vs security auditors, remove the deprecated auditor group and role.
Depends on #1007
> [IT-3224] Remove deprecated Auditor group and role

- org-formation/650-identity-providers/_tasks.yaml
Sage-Bionetworks-IT/imagecentral-dashboard was using a service user to access AWS for CI builds.  That service user has been removed by PR #967 so now we setup the GH repo with OIDC access to AWS.
> setup GH OIDC for imagecentral-dashboard

- sceptre/scipool/config/develop/bootstrap.yaml
> [IT-2730] Remove service user

- sceptre/strides-ampad-workflows/templates/jumpcloud-idp.yaml
Give tower viewer role read only access to the strides-ampad account.
> [IT-3308] fix read only access for strides ampad

- org-formation/700-aws-sso/_tasks.yaml
I had changed `IncludeMasterAccount` from `true` to `false` to stop account specific roles from showing up under the Organizations account, but the change also removed the roles from the intended accounts.  I am unclear on how `IncludeMasterAccount` is supposed to work.  For now I am submitting this PR to undo the breaking change.
> IT-3322 undo breaking change

- org-formation/700-aws-sso/_tasks.yaml
There seem to be dependency issues from Organization PermissionSet on member account PermissionSets.  Unable to clean up or regenerate stacks.  So I am trying to remove *all* application-manager permission sets.
> IT-3322 temporarily removing all application-manager permission sets to fix broken build

- sceptre/synapsedev/config/prod/snowflake-access.yaml
This PR will create a new role for the snowflake access to Synapse dw bucket.
First called with fake externalID to get the role ARN.
Depends on https://github.com/Sage-Bionetworks/aws-infra/pull/398
> Create role for snoflake access to synapsedev data with fake extID to get roleArn

- sceptre/aws-opendata/config/prod/single-cell-human-blood-atlas.yaml
- sceptre/aws-opendata/templates/opendata-bucket.yaml
The `single.cell.human.blood.atlas.opendata.sagebase.org` bucket was manually deployed to the AWS opendata account previously.  This will put it under Sceptre/cloudformation IaC control.
depends on #1032
> [IT-3313] single.cell.human.blood.atlas.opendata bucket

- sceptre/aws-opendata/config/prod/ukbiobank-bucket.yaml
The `ukbiobank.opendata.sagebase.org` bucket was manually deployed to the AWS opendata account previously.  This will put it under Sceptre/cloudformation IaC control.
depends on #1054
> [IT-3319] ukbiobank bucket for aws opendata

- sceptre/synapsedev/config/prod/snowflake-access.yaml
This PR updates the trust relationship by specifying the actual externalID (stored in SSM parameter store).
> SynapesDev-Snowflake-Access: Actual id from SSM

- org-formation/650-identity-providers/_tasks.yaml
The first step to moving agora-data-manager CI from travis to GH action is to setup
GH action OIDC access on agora-data-manager to allow access to update the document
database.
> [IT-3230] Role for agora-data-manager repo

- README.md
- sceptre/scipool/config/develop/sc-product-ec2-linux-docker-notebook.yaml
- sceptre/scipool/templates/sc-product-ec2-linux-docker-notebook.j2
Add Dockerized Notebook defined in  [service-catalog-library](https://github.com/Sage-Bionetworks/service-catalog-library/pull/318) to Service Catalog portfolio.
Depends on: https://github.com/Sage-Bionetworks/service-catalog-library/pull/318
> IT-3317 Add dockerized notebook to SC portfolio

- org-formation/700-aws-sso/_tasks.yaml
Create a new S3 viewer group to allow the digital analytics team access to download objects from S3 buckets in the AWS recover accounts.
> [IT-3403] new s3 viewer group

- .github/workflows/aws-scipool.yaml
We setup service catalog action associations workarounds for scipool prod but forgot to setup the work around for bmfgki and strides accounts.  This enables the workaround for those accounts as well.
> [SC-219] Enable SC action association work around

- sceptre/scipool/config/develop/cfn-cr-alb-rule.yaml
updating ALB stack to  to v0.1.4.  This will decrease session timeout to one day.  The change is being applied to 'develop' for validation, after which it will be applied to prod, strides, and bmgfki.
> IT-3317: updating Notebook product ALB stack to v0.1.4 in develop

- .github/workflows/aws-deploy.yaml
- .github/workflows/aws-scipool.yaml
We used to use the Sceptre file handler[1] which required a step to create the `template/remote` folder as a temporary location to save downloaded cfn templates.  We no longer need that because we now use the Sceptre http handler[1] which handles downloading of templates for us.  It basically downloads templates to the `/tmp` folder.
[1] https://docs.sceptre-project.org/latest/docs/template_handlers.html#file
[2] https://docs.sceptre-project.org/latest/docs/template_handlers.html#http
> Update sceptre deployment commands

- sceptre/scipool/config/develop/cfn-cr-alb-rule.yaml
- sceptre/scipool/config/develop/sc-product-assoc-ec2-linux-docker-notebook.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-docker-notebook.yaml
In SC dev: 
- Adding product assoc', 
-  Updating SC Notebook ALB to '0.1.5';
- Updating Notebook to 'v1.3.5'
Depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-alb-rule/pull/16.  After merging that repo' must be tagged with `0.1.5`.
Depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/322.  After merging, that repo' must be tagged with 'v1.3.5'.
> IT-3317: In SC dev: Adding product assoc', updating SC Notebook and ALB

- org-formation/700-aws-sso/_tasks.yaml
Give S3 viewer role read only access to cloudwatch logs.
> [IT-3414] update SSO S3 viewer role

- .github/workflows/main.yaml
* We want to only deploy from master branch
* We do not want concurrent cloudformation deployments to AWS accounts.
* We also don't want to interrupt cloudformation deployments otherwise it
may get into a bad state.  Therefore we are disabling concurrency[1]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idconcurrency
> Disable GH action concurrency

- sceptre/scipool/config/develop/cfn-cr-alb-rule.yaml
- sceptre/scipool/config/develop/sc-product-assoc-ec2-linux-docker-notebook.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-docker-notebook.yaml
Depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-alb-rule/pull/18 which will also have to be tagged `0.1.7`
> Bump cfn-cr-alb-rule to 0.1.7 (develop only)

- org-formation/050-costs/_tasks.yaml
Add an S3 cache of upstream API responses to our MIP API for fault tolerance.
> [IT-3341] Update lambda-mips-api version

- sceptre/scipool/config/bmgfki/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/develop/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/prod/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/strides/sc-product-ec2-windows-jumpcloud.yaml
Update the service catalog windows product with fixes for the chocolately and jumpcloud agent installs
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/325
> [IT-3425] Update service catalog windows product

- org-formation/050-costs/_tasks.yaml
Update the email report lambda to a version that supports sending copies to additional recipients, and add a newly-created google group as an additional recipient.
Depends on Sage-Bionetworks-IT/lambda-finops-email-totals#19
> [IT-3386] Send a copy of cost reports to a new google group.

- sceptre/scipool/config/bmgfki/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/develop/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/prod/sc-product-ec2-windows-jumpcloud.yaml
- sceptre/scipool/config/strides/sc-product-ec2-windows-jumpcloud.yaml
Since it's possible for an AMI to disable IMDSv1, we are updating all of our setup scripts to use IMDSv2.
> [IT-3369] Update sc-ec2-windows-jumpcloud to use IMDSv2

- org-formation/050-costs/_tasks.yaml
Update lambda-finops-email-totals to a version that includes a section about unexpected CostCenterOther tags (i.e. when CostCenter is not `Other / 000001`).
> Release latest version of the finops email lambda

- org-formation/organization.yaml
With Amazon CloudWatch cross-account observability[1], we can monitor and troubleshoot applications that span multiple accounts within a Region.
The first step is to set up an AWS monitoring account.
[1] https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html
> [IT-3471] Bootstrap a cloudwatch monitoring account

- org-formation/740-cloudwatch-dashboard/CloudWatch-CrossAccountListAccountsRole-AccountList.yaml
- org-formation/740-cloudwatch-dashboard/CloudWatch-CrossAccountSharingRole-AccountList.yaml
- org-formation/740-cloudwatch-dashboard/Cloudwatch-Link-Management-Account.yaml
- org-formation/740-cloudwatch-dashboard/README.md
- org-formation/740-cloudwatch-dashboard/_tasks.yaml
Setup AWS Cloudwatch cross-account observability[1].  This feature will allow us to create a cloudwatch dashboard in one AWS account that monitors apps deployed to multiple AWS accounts.
Note: all of the templates used to setup cloudwatch dashboard is provided by AWS
[1] https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html
> [IT-3471] Setup a cross account cloudwatch dashboard

- org-formation/650-identity-providers/_tasks.yaml
Add OIDC for packer-winserver-2022 to deploy AMIs to imagecentral.
> [IT-3456] Add GH OIDC for packer-winserver-2022

- sceptre/aws-opendata/config/prod/CloudWatch-CrossAccountSharingRole-AccountList.yaml
- sceptre/aws-opendata/config/prod/Cloudwatch-Link-Management-Account.yaml
- sceptre/strides-ampad-workflows/config/prod/CloudWatch-CrossAccountSharingRole-AccountList.yaml
- sceptre/strides-ampad-workflows/config/prod/Cloudwatch-Link-Management-Account.yaml
- sceptre/strides/config/prod/CloudWatch-CrossAccountSharingRole-AccountList.yaml
- sceptre/strides/config/prod/Cloudwatch-Link-Management-Account.yaml
Link AWS accounts that are not in our organizations to the cloudwatch dashboard.
This is a 2nd attempt at PR #1106 which was reverted in commit 3bce57d.
This one contains some fixes to stack names and stack dependencies.
depends on Sage-Bionetworks/aws-infra#407
> [IT-3471] link non-org accounts to cloudwatch dashboard

- sceptre/strides-ampad-workflows/templates/aws-config.yaml
- sceptre/strides/templates/aws-config.yaml
* Removing config rule for accounts that are not in our organizations to be consistent with the member accounts in the organizations.
* Ignore pre-commit warning "W2001 Parameter LocalCloudtrailBucket not used".
> [IT-1826] Remove config rule for strides and strides-ampad

- org-formation/740-cloudwatch-dashboard/_tasks.yaml
- org-formation/740-cloudwatch-dashboard/cw-dashboards.njk
Create cloudwatch dashboards for agora develop, staging and prod in the monitoring account. This requires setting up beanstalk to send metrics to cloudwatch in the agora accounts.
depends on https://github.com/Sage-Bionetworks/agora2-infra/pull/25
> [IT-3471] Configure dashboards for Agora

- org-formation/050-costs/_tasks.yaml
Don't generate an empty resource table when all owned resources are in an owned account
> [IT-3553] Fix email formatting in certain cases

- sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker-notebook.yaml
- sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-docker-notebook.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-docker-notebook.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-docker-notebook.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml
Update products to remove the nano EC2 instance type as an option.
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/330
> [IT-3420] Update service catalog EC2 products

- sceptre/synapsedev/templates/SynapseCMK-template.json
Add AWS AppConfig permissions for stack builder
PR Checklist:
> SWC-6768: Add appconfig permissions for stack builder

- org-formation/300-account-defaults/_tasks.yaml
Deploy a lambda to terminate any ec2 instances over an hour old in the image central account.
> [IT-1729] Cleanup failed packer instances

- org-formation/060-cloudtrail/_tasks.yaml
- org-formation/060-cloudtrail/cloudtrail-trail.yaml
Previously to enable cloudtrail to send data to a central AWS account (logcentral) we need to setup cloudtrail in every member account to enable this configuration.
AWS has now introduced a new feature that allows enabling `organizations cloudtrail` without having to setup cloudtrail in every member account. Instead it just need to be enabled from an organizations account or from a deleaged admin account.
We are changing the cloudtrail setup to the latter option because it's much simpler.  The only caveat is that we need to first manually setup logcentral as an cloudtrail delegated admin account[1]
[1] https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-add-delegated-administrator.html
> [IT-2581] Refactor cloudtrail setup

- sceptre/scipool/templates/sc-enduser-iam.yaml
Updating provisioned products with changes to tags is failing with permissions errors. RestrictBucketDownloadRegionFunction updates fail on 'lambda:ListTags', and the associated roles fail on'iam:UntagResource'. Allow SC roles to list tags on any lambda, and to update tags on their own provisioned resources.
The 'aws:ResourceTag/foo' condition key lets us compare against the value of the 'foo' tag on the target resource. Here we are comparing the 'provisioningPrincipalArn' SC service tag value against the 'PrincipalArn' from the request.
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_tags.html#access_tags_control-resources https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-resourcetag …
> [IT-3554] Add additional Service Catalog permissions

- sceptre/synapseprod/templates/SynapseCMK-template.json
This PR adds AppConfig permissions to the Synapse Prod deployer role.
Same as #1124 for dev.
> PLFM-8399: Add AppConfig permissions to deployer role

- org-formation/075-security-hub/_tasks.yaml
- org-formation/075-security-hub/security-hub.yaml
The current stack fails to build with:
> Account is already subscribed to Security Hub
I wonder if this is because we changed `MasterAccount` to `SecurityCentralAccount` in  075-security-hub/_tasks.yaml, i.e., if the error is due to trying to run the stack in the designated Security Hub administrator account.
This PR reverts the change to try to fix the build.
> IT-3606 Reverting change to 075-security-hub/_tasks.yaml

- sceptre/synapsedev/templates/SynapseCMK-template.json
- sceptre/synapseprod/templates/SynapseCMK-template.json
PR Checklist:
Add parameter store permissions for stack builder to use to pull in AppConfig identifiers inside SWC
> SWC-6769: Add parameter store permissions for stack builder

- org-formation/075-security-hub/_tasks.yaml
- org-formation/075-security-hub/security-hub.yaml
We want the security-hub CF stack to be created in the delegated admin' account rather than in the Organizations account.
> IT-3606: switch security-hub account to SecurityCentralAccount

- sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml
Use our latest custom amazon linux AMI built from the latest AWS-provided AMI to ensure Service Catalog products have the latest package updates.
> [IT-3547] Update base Amazon Linux AMI

- org-formation/700-aws-sso/_tasks.yaml
Sometimes we may want to give non-IT members access to review
development work in the IT sandbox account.   This sets up
a Jumpcloud group to allow for that.
> Jumpcloud group for AWS ITSandbox account

- org-formation/650-identity-providers/_tasks.yaml
This PR adds new buckets and distributionIDs for deployment from synapse-monrepo.
> IT-3681: Add targets for deployment

- sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
- sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml
The latest version of the EC2 Linux product fails to connect via SSM, roll back the change from all environments except dev to debug.
> [IT-3697] Partial revert of 8e43df90017b1c4d6f11fe74e1cb437c12524d81

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
Suupress security hub finding for
"3.5 Ensure AWS Config is enabled in all regions"
> [IT-3619] Suppress securityhub finding

- sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
Test the latest AMI created by packer-amazonlinux-docker before tagging a new version by referencing the master AMI in the product template on the master branch of service-catalog-library and referencing that product template in the dev account here.
If the test works then packer-amazonlinux-docker will be tagged with a new version, the tagged AMI will be referenced in the product template and service-catalog-library will be tagged with a new version. Finally, new products will be created here from the newly tagged product template.
> [IT-3697] Test the latest docker AMI before tagging a new version

- sceptre/scipool/config/develop/sc-product-s3-private-enc.yaml
- sceptre/scipool/config/develop/sc-product-s3-synapse.yaml
Use the latest S3 templates, pulling in updated dependencies for the same region download lambda.
Depends on Sage-Bionetworks/service-catalog-library#333
> [IT-3547] Update S3 products

- sceptre/scipool/templates/sc-s3-launchrole.yaml
The current launch role is able to create and terminate products, but not update them.
> [IT-3658] Give the S3 launch role permission to update the nested lambda

- sceptre/scipool/config/develop/cfn-cr-synapse-tagger.yaml
Update cfn-cr-synapse-tagger lambda in dev' Service Catalog account, changing from v 0.1.3 to v 0.1.4.
> IT-3686: Update cfn-cr-synapse-tagger lambda in dev' Service Catalog account

- org-formation/organization.yaml
Four points requires us to apply their AWS account naming convention to our organizations account.
> [IT-3758] Update organziation account name

- org-formation/600-access/_tasks.yaml
Create Read Only access to EC2 and VPC in the Synapse Prod account for StackArmor.
> IT-3780 Add R/O access for StackArmor

- .github/workflows/deploy.yaml
- org-formation/600-access/_tasks.yaml
The role session name overruns the 64 character limit as the github run id gets larger.  This change ensures the role session name never exceeds 64 characters.   It uses the _suffix_ to make sure the entire run id is included for uniqueness sake.
> Limit role session name

- sceptre/aws-opendata/config/prod/brainseq-bucket.yaml
- sceptre/aws-opendata/config/prod/cfn-s3objects-macro.yaml
- sceptre/aws-opendata/config/prod/single-cell-human-blood-atlas.yaml
- sceptre/aws-opendata/config/prod/ukbiobank-bucket.yaml
- sceptre/aws-opendata/templates/opendata-bucket.j2
This adds the ability to create an Synapse owner.txt file when provisioning a Synapse bucket.
* Change cloudformation template to a jinja template.
* Install S3 objects macro[1] to aws-opendata account
* Use the macro to create and update the owner.txt file
To create the file add something like this to the Sceptre config:
```
sceptre_user_data:
SynapseIDs:
- "3489135" # Synapse team ID
```
[1] https://github.com/aws-cloudformation/aws-cloudformation-macros/tree/master/S3Objects
> [IT-3660] Automate creation of Synapse owner.txt file

- org-formation/650-identity-providers/_tasks.yaml
Setup Github OIDC to allow Github CI to deploy the Challenges application to AWS accounts from the Sage-Bionetworks-IT/OpenChallenges[1] repo.
It's only setup to deploy to ITSandbox account for now since that's where we are dev/testing it at this time.
[1] https://github.com/Sage-Bionetworks-IT/openchallenges
> [IT-3512] Github OIDC for OpenChallenges deployment

- org-formation/080-aws-config-inventory/README.md
- org-formation/080-aws-config-inventory/_tasks.yaml
- org-formation/080-aws-config-inventory/config.yaml
- org-formation/README.md
- org-formation/_tasks.yaml
This is a partial revert of 9f5bb53
We need to enabled AWS config service in every organization member account
to collect config data.  This will allow the aggregator account (logcentral)
to collect and aggregate the config data from member accounts, visualize
that data and store it in a central account.
> [IT-3619] Enable AWS config service

- org-formation/600-access/_tasks.yaml
Four points needs access to AWS usage reports to generate cost summery level reports.
from  four points...
```
Good morning.  I have accessed the account to complete our first month of billing. 
I just realized we don’t have access to the usage report that we need.
I will only be able to provide summary level reporting this month. 
Can we get the detail billing report and a CUR report setup for our use?  
I can provide details on what we need if needed.
```
* Give four points access to view usage from aws portal
* Give four points full access to bucket folder "cost-and-usage-reports.sagebase.org/4points" to allow sending their reports to that folder.  Setup this policy from  bcm-data-exports-access-examples[1] and example-bucket-policies-folders[2] docs.
[1] …
> [IT-3758] Give 4 points access to usage reports

- org-formation/600-access/_tasks.yaml
This is a fix for commit 96e340e93d8
* cannot set AWS pseudo parameters in org-formation yaml so we change it to '*'
* the policy was mixing up IAM and resource policies. iam policies do not support a principal parameter. principal is only allowed in resource policies. We remnoved the policies and moved them to the bucket policy.
> Fix 4point access policy

- sceptre/organizations/config/prod/fourpoints.yaml
- sceptre/organizations/templates/s3-cur-bucket.j2
Four point's use cases are broader than initialally anticipated when setting up a storage location for them in PRs #1189 and #1197
This unwinds changes in those PRs.  Instead of giving 4points access to a folder in an existing bucket we create a whole new bucket for them and give them read and write access to the new bucket.
> [IT-3758] Setup a bucket for four points

- sceptre/scipool/config/develop/sc-portfolio-scheduled-jobs.yaml
- sceptre/scipool/config/develop/sc-scheduled-jobs-launchrole.yaml
- sceptre/scipool/config/prod/sc-portfolio-scheduled-jobs.yaml
- sceptre/scipool/config/prod/sc-scheduled-jobs-launchrole.yaml
- sceptre/scipool/config/strides/sc-portfolio-scheduled-jobs.yaml
- sceptre/scipool/config/strides/sc-scheduled-jobs-launchrole.yaml
Sceptre deprecated `template_path` key. Update to fix build
> Fix sceptre

- org-formation/650-identity-providers/_tasks.yaml
Allow GitHub to deploy the Docker registry to the Synapse AWS accounts.
This is part of the effort to (1) automate the deployment of the Docker registry and (2) move to Fargate to avoid having to monitor/patch EC2s.
> PLFM-8554: Allow GitHub to deploy the Docker registry to the Synapse AWS accounts

- org-formation/710-tgw/_tasks.yaml
Previous PR (#1202) failed at accessing an output value from the infra VPC stack (' !CopyValue [!Join ["-", [!Ref primaryRegion, !FindInMap [TgwSpokesB, VpcName, !Ref CurrentAccount], 'PrivateSubnet']]] ') so we need the stack name in the map, not the vpc name.
> Should be stack name, not vpc name to copy output

- org-formation/650-identity-providers/_tasks.yaml
The deployment failed for #1208 because we execeeded the max length of the document (4096).
This PR combines the resource names further.
Stopgap solution as we'll run into this again...
> IT-3773: Fix length issue

- org-formation/650-identity-providers/_tasks.yaml
Use the policies from #1211 instead of the policy role for permissions of the Synapse Web Monorepo oidc role.
> IT-3773: Replaced policy doc by managed arns

- org-formation/650-identity-providers/_tasks.yaml
Setup github OIDC to allow github CI to deploy to openchallenges accounts.
depends on https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1213
depends on https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1216
> [IT-3891] Setup github CI deployments to Open Challege accounts

- org-formation/650-identity-providers/_tasks.yaml
This PR sets up OIDC role with permissions to push a docker image to a repo from the nbconvert GH repo, and create a lambda from that image.
> PLFM-8102: Add oidc perms to push image to repo and deploy lambda from image

- org-formation/650-identity-providers/_tasks.yaml
This PR fixes a wrong name for the Cloudformation policy, and updates the name of the lambda policy (other one is deprecated).
> PLFM-8102: Fix deployment

- sceptre/admincentral/templates/cfn-snippets-bucket.yaml
- sceptre/bridge/templates/bridge.yaml
- sceptre/bridge/templates/essentials.yaml
- sceptre/imagecentral/templates/ec2-image-builder.yaml
- sceptre/sageit/templates/admodeladexplorer-redirector.yaml
- sceptre/sageit/templates/s3webredirect.yaml
AWS has deprecated the use of ALCs for S3 buckets
so we remove AccessControl and keep OwnershipControls
```
AWS::S3::Bucket UPDATE_FAILED Resource handler returned message:
"Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced
setting
```
> fix bucket settings

- sceptre/admincentral/templates/cfn-snippets-bucket.yaml
- sceptre/bridge/templates/bridge.yaml
- sceptre/bridge/templates/essentials.yaml
- sceptre/imagecentral/templates/ec2-image-builder.yaml
- sceptre/sageit/templates/admodeladexplorer-redirector.yaml
- sceptre/sageit/templates/s3webredirect.yaml
This is a fix for PR #1220  which I tried to fix in PR #1225 but now encountered the following error..
```
develop/sc-product-ec2-linux-docker-notebook sc-product-ec2-linux-docker-notebook
AWS::CloudFormation::Stack UPDATE_IN_PROGRESS Transform AWS::Include failed with:
S3 URI must reference a valid S3 object to which you have access.
```
Which i think means that the bucket is still not setup as a public read bucket.
This fix is derived from the example in AWS docs to setup an S3 public bucket[1]
[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#aws-resource-s3-bucket--examples--Granting_public_access_to_S3_buckets
> Fix public read bucket

- org-formation/650-identity-providers/_tasks.yaml
This rstudio aws AMI is no longer used.  The repo[1] for it has been archived as well.
[1] https://github.com/Sage-Bionetworks-IT/packer-rstudio
> packer-rstudio has been deprecated

- org-formation/organization.yaml
This PR creates the AWS account to host the Synapse LLM infrastructure.
Note: dev account to be deleted per discussion.
> IT-3924: Add prod account

- org-formation/700-aws-sso/_tasks.yaml
This PR should fix the deployment error ' ERROR: Task SsoSynapseLlmProdAdmin validated failed. reason: unable to parse expression on attribute parameter principalId. Is there an error in the expression? {"Ref":"synapseLlmProdAdminGroup"} '
> IT-3924: case-sensitive

- org-formation/700-aws-sso/_tasks.yaml
This PR
- creates a 'developer' role in the SynapseLLM prod account based on the existing SSO developer permission set
- creates an 'llmdeveloper' permission set associated with an 'aws-llm-developers' JC group (following pattern seen for permission sets)
- creates a 'llm-developer' role in the SynapseLLM prod account based on the permission set created above
> IT-3924: Add developer and LLM developer roles to SynapseLLM account

- org-formation/600-access/_tasks.yaml
This PR adds cross account access to Bedrock in SynapseLlmProd from SynapseProd
> IT-3924: Add cross-account for SynapseProd

- org-formation/600-access/_tasks.yaml
This PR gives the Synapse Dev account the permission to access BedRock in the SynapseLLM prod account.
> IT-3924: Enable access to SynapseLLM prod from SynapseDev account

- org-formation/650-identity-providers/_tasks.yaml
A new cloudformation validation command was added to the deploy pipeline, but the github oidc role doesn't have permission to run the command `aws cloudformation validate-template`.
Grant `cloudformation:ValidateTemplate` access to the OIDC role used by our lambda projects.
> Fix lambda-finops-s3-cost-report deploy pipeline

- org-formation/700-aws-sso/_tasks.yaml
The PowerUserAccess policy does not allow access to IAM, From the docs[1].. `Provides full access to AWS services and resources, but does not allow management of Users and groups.`
Developers should be able to view AWS user and group info.
[1] https://docs.aws.amazon.com/aws-managed-policy/latest/reference/PowerUserAccess.html
> Give SSO developer role IAM read access

- org-formation/800-redirects/_tasks.yaml
Following [this](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2859302913/Admin+Tasks+for+CDK+Applications) guidance, we add the CNAME `docker.dev.sagebase.org` to direct traffic to the dev' Synapse Docker Registry.
> PLFM-8554: Add friendly CNAME to LB for dev' Synapse docker registry

- sceptre/scipool/config/bmgfki/lambda-bucket-cleanup.yaml
- sceptre/scipool/config/develop/lambda-bucket-cleanup.yaml
- sceptre/scipool/config/prod/lambda-bucket-cleanup.yaml
- sceptre/scipool/config/strides/lambda-bucket-cleanup.yaml
Version 1.0.3 includes an update from python 3.8 to python 3.11
depends on https://github.com/Sage-Bionetworks-IT/lambda-sc-bucket-cleanup/pull/13
> Update lambda-bucket-cleanup version

- org-formation/650-identity-providers/README.md
- org-formation/650-identity-providers/_tasks.yaml
- org-formation/650-identity-providers/microsoft-defender-cloud-roles.yaml
This PR is a continuation of PR https://github.com/Sage-Bionetworks/infra-utils/pull/66
This will setup resources to allow Microsoft Defender for cloud service to do security scans on our AWS accounts.  The cloudformation template was provided by StackArmor.
> [IT-3950] Deploy Microsoft Defender for cloud resources

- org-formation/700-aws-sso/_tasks.yaml
This PR adds a in-line policy to LLMDeveloper role that gives the permission to create objects in S3 (upload templates).
> IT-3988: Add permission to create object in S3

- org-formation/700-aws-sso/_tasks.yaml
The putObject permission was not enough, widen to allow any action but still restrict object prefix.
> IT-3988: Widen permissions

- org-formation/600-access/_tasks.yaml
This PR fixes a deployment issue in #1277 caused by a missing '!Ref'.
> IT-3988: Add missing ref

- package.json
Update to fix this message from the CI..
```
NOTICES         (What's this? https://github.com/aws/aws-cdk/wiki/CLI-Notices)
31885	(cli): Bootstrap stack outdated
Overview: The bootstrap stack in aws://***/us-east-1 is outdated.
We recommend at least version 21, distributed with CDK CLI
2.149.0 or higher. Please rebootstrap your environment by
runing 'cdk bootstrap aws://***/us-east-1'
Affected versions: bootstrap: <21
More information at: https://github.com/aws/aws-cdk/issues/31885
```
> Update aws cdk

- org-formation/800-redirects/_tasks.yaml
**Problem:**
1. Resources are expecting the `staging` URL for schematic remains as is
**Solution:**
1. Updating the source hostname to use `staging` and removing the other dns forwarding for the previous stack
> Point staging url for schematic to multi-container deployment stack

- org-formation/800-redirects/_tasks.yaml
Deployment of https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1290/files failed: https://github.com/Sage-Bionetworks-IT/organizations-infra/actions/runs/11919331993/job/33218806052
Due to:
```
DEBG: Stack sagebase-schematic-stage-cname in account 797640923903 (us-east-1) update starting... (797640923903 = SageITAccount)
ERROR: error updating CloudFormation stack sagebase-schematic-stage-cname in account 797640923903 (us-east-1). 
Resource is not in the state stackUpdateComplete (797640923903 = SageITAccount)
ERROR: Resource DnsRecord failed because [Tried to create resource record set [name='schematic-staging.api.sagebionetworks.org.', type='CNAME'] but it already exists].
ERROR: Stack sagebase-schematic-stage-cname in account 797640923903 (us-east-1) update failed. …
```
> Point to schematic staging (Replace)

- org-formation/800-redirects/_tasks.yaml
Since moving to the schematic multi-container deployment this stack is no longer needed and is being torn down
> Tear down DNS redirect for schematic-dev refactor

- org-formation/700-aws-sso/_tasks.yaml
As LLM developers are using features in the console, we'll keep getting permission errors. After discussion with John, we decided to up to PowerUserAccess, then track and scale down. We may still have to adjust IAM permissions if/as needed.
> IT-4016/IT-4017: Give PowerUser permissions and scale down later

- org-formation/800-redirects/_tasks.yaml
This PR updates the DNS redirect for Schematic Prod to use the new deployment stack. Part of deploying v24.11.2 to the production API.
> [SCHEMATIC-211] Updates Schematic Prod DNS redirect for new deployment stack

- org-formation/800-redirects/_tasks.yaml
This is to point the staging and prod subdomains for `*.sagedpe.org` to the staging and prod k8s clusters. The changes are modeled after the setup of the dev cluster and forwarding.
> [SCHEMATIC-139] Set up fowarding for Sage DPE staging/prod domain

- org-formation/800-redirects/_tasks.yaml
The certificate used for agora is validated for adknowledgeportal.org domain not the dev, stage, and prod sub domains therefore we can't use sub domains unless we redo the certificate.  for simplicity we rename to not use sub domains.
> Agora redirect dns name change

- org-formation/650-identity-providers/_tasks.yaml
Schematic was updated with a new deployment "GithubOidcSageBionetworksItSchematicInfraV2", therefore we can remove the old deployment OIDC resource.
> [IT-4025] Remove github OIDC for schematic

- org-formation/650-identity-providers/_tasks.yaml
This PR switches from specifying the permissions to using a role created by cdk bootstrap that allows assuming a set of policies covering these permissions (also created by cdk bootstrap).
> PLFM-8102: Use Admin Access

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
- org-formation/090-systems-manager/_tasks.yaml
Add suppression rules for cis-aws-foundations-benchmark/v/1.4.0.
Existing rules were for cis-aws-foundations-benchmark/v/1.2.0 but we've upgraded.
> IT-4077 Add suppression rules for cis-aws-foundations-benchmark/v/1.4.0

- sceptre/synapsedev/config/prod/vpc.yaml
> IT-4226: Update version

- sceptre/synapseprod/config/prod/synapse-ops-vpc-v2.yaml
This PR updates the ops VPC in synapseprod to add a vpce for opensearchserverless.
> IT-4226: Deploy vpce for opensearch in synapseprod

- org-formation/700-aws-sso/_tasks.yaml
Setup admin access to org-sagebase-codeocean account
depends on https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1317
> [IT-4228] Setup SSO access to AWS codeocean account

- org-formation/300-account-defaults/bedrock-agent-role.yaml
This PR adds the permission to call a lambda to the role assumed by the Bedrock agent
> IT-4212: Add permission to call lambda

- org-formation/650-identity-providers/_tasks.yaml
Allow Sage-Bionetworks-IT/aws-ami-monorepo to deploy cloudformation and generate AMI images in the AWS org-sagebase-imagecentral account
> [IT-3831] Update github OIDC access

- org-formation/650-identity-providers/_tasks.yaml
Instead of piggy backing on a packer role it's probably better to create a separate role for image builder deployments.
> [IT-3831] GH OIDC image builder deployments

- org-formation/650-identity-providers/_tasks.yaml
The roles needs full access to the cloudformation and image builder instead of EC2.
> Fix role to deploy image builder AMIs

- org-formation/090-systems-manager/_tasks.yaml
- org-formation/700-aws-sso/_tasks.yaml
Add `aws-dca-prod-admins` group, allowing members of JC group to have admin' access to DCA Prod account.
> IT-4237 Create SSO access for a JC aws-dca-prod-admins group 

- org-formation/650-identity-providers/_tasks.yaml
The image builder template can do all sorts of things, like create roles.  Therefore we need to up the permission when deploying it to imagecentral.
> [IT-3831] fix GH OIDC permissions for image builder

- org-formation/650-identity-providers/_tasks.yaml
We have setup a SageBionetworks-IT/codeocean-infra[1] repo to deploy the code ocean application to AWS.  This will allow the repo access to deploy resources to the AWS org-sagebase-codeocean-prod account.
[1] https://github.com/Sage-Bionetworks-IT/codeocean-infra
> [IT-4228] Setup github OIDC access for codeocean-infra

- org-formation/650-identity-providers/_tasks.yaml
Remove the role to allow GH actions to deploy OpenChallenges
to the org-sagebase-openchallenges-dev AWS account.
> [IT-4055] Remove role for OpenChallenges deployment

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
Ignore "CIS 2.2.1 Ensure EBS volume encryption is enabled" in the image-central account, we don't want it enabled by default since the volumes in this account are used to create public AMI images.
> [IT-4151] Ignore CIS 2.2.1 finding in image-central

- org-formation/700-aws-sso/_tasks.yaml
We switch from using packer to using the AWS image builder to build AMIs (in issue IT-3831).  This change requires AMI librarians to have a different set of access to build and deploy AMIs with cloudformation templates.
Note: This new least privileged policy was auto generated using the aws-leastprivilege[1] app.
[1] https://github.com/iann0036/aws-leastprivilege
> [IT-4244] update SSO ImageCentralAmiLibrarian policy

- org-formation/650-identity-providers/_tasks.yaml
This PR adds the S3 buckets and distributions for the 'standards' portal to the synapse-monorepo's OIDC deployment role
> Add oidc perms for standards portal

- package.json
Attempt to debug an issue in the deploy pipeline by printing the contents of the auto-generated CDK bootstrap template.
> debug: add output to CDK template generation

- package.json
The deploy pipeline is failing due to jq being unable to parse the output from the CDK CLI. Generating the template locally creates a valid JSON file with 1091 lines and prints a notice to stderr. In the deploy pipeline jq failes to parse line 1093. It seems that in the github-runner environmunt stderr is redirected to stdout, causing the notice to be written to the end of the file.
Disable printing CDK CLI notices in the deploy pipeline.
> bugfix: ignore notices from the CDK CLI

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
Bridge deployments can happen less frequently than 45 days, ignore findings related to credentials unused for 45 days.
> [IT-4091] Suppress CIS 1.12 in Bridge accounts

- org-formation/650-identity-providers/_tasks.yaml
The HEAD branch of the lambda-template project was changed from "master" to "main" as part of creating lambda-tag-patch-group for IT-3940, which was later deleted.
Allow lambda-template and future projects created from it to assume OIDC roles for deploying from a "main" branch.
> Allow lambda projects to deploy from "main" branch

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
suppress finding "S3 Block Public Access setting should be enabled at the bucket-level" for all accounts.
We can remediate this check by enabling all those settings however it would mean that all buckets in an AWS account would need to be private.  We have legittimate use case for public buckets in our AWS accounts therefore remediating this check does not make sense.
> [IT-4236] Suppress security hub finding

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
I recommend we suppress this finding:
5.1 Ensure no Network ACLs allow ingress from 0.0.0.0/0 to remote server administration ports
It’s typically normal to allow NACL ingress from all ports. This is in fact how the default AWS VPC is setup.
I think it’s already cumbersome to configure access in AWS, closing off NACL ports without an explicit reason would just makes it more cumbersome and confusing to configure access to resources.  There is an additional mechanism, security groups, that would need to be setup to allow access to resources.
> [IT-4190] Suppress security hub rule

- org-formation/600-access/_tasks.yaml
resolve security hub finding "1.12 Ensure credentials unused for 45 days or greater are disabled"
The Sage-Bionetworks/agora-infra repo has been deleted and this service user is no longer being used.
> [IT-4125] resolve security hub finding

- org-formation/650-identity-providers/_tasks.yaml
Create an github OIDC integration for Sceptre/sceptre-aws repo which deploys resources to run sceptre integration tests.
> [IT-4124] add github OIDC for Sceptre repo

- org-formation/600-access/_tasks.yaml
We switch to using github OIDC so removing the service user.
depends on https://github.com/Sceptre/sceptre-aws/pull/18
> [IT-4124] Remove service user

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
The account ID listed at the top Event scope is the security-central account. Match on the ID at the Finding scope to filter based on the account the finding was found in.
> [IT-4071] bugfix: match on the correct account ID

- org-formation/090-systems-manager/QuickSetup-PatchPolicy-Prod.yaml
- org-formation/090-systems-manager/QuickSetup-PatchPolicy.yaml
- org-formation/090-systems-manager/_tasks.yaml
Use SSM Quick Setup to create a Patch Policy that applies to all managed nodes in the Platform organizational unit (Synapse accounts and Bridge accounts).
User Guide:
https://docs.aws.amazon.com/systems-manager/latest/userguide/quick-setup-patch-manager.html 
AWS Blog:
https://aws.amazon.com/blogs/mt/deploy-aws-systems-manager-quick-setup-programmatically-across-your-aws-organization/
Examples:
https://github.com/aws-samples/aws-management-and-governance-samples/blob/master/AWSSystemsManager/Quick-Setup-API/patch-policy-examples/patch-policy-cfn-template.yaml
https://github.com/aws-samples/aws-management-and-governance-samples/blob/master/AWSSystemsManager/Quick-Setup-API/patch-policy-examples/default-patch-baselines.txt
> [IT-4287] Automate SSM patching for all instances in all accounts

- org-formation/090-systems-manager/QuickSetup-PatchPolicy.yaml
Cloudformation in complaining about the format, use single quotes to match https://github.com/aws-samples/aws-management-and-governance-samples/blob/master/AWSSystemsManager/Quick-Setup-API/patch-policy-examples/patch-policy-cfn-template.yaml
> bugfix: use single quotes instead of YAML flow

- org-formation/090-systems-manager/QuickSetup-PatchPolicy.yaml
- org-formation/090-systems-manager/_tasks.yaml
The 'PatchBaselineRegion' parameter is required but not documented at
https://docs.aws.amazon.com/quick-setup/latest/APIReference/API_ConfigurationDefinitionInput.html
The parameter can be found in the example
https://github.com/aws-samples/aws-management-and-governance-samples/blob/master/AWSSystemsManager/Quick-Setup-API/patch-policy-examples/patch-policy-cfn-template.yaml
> Add 'PatchBaselineRegion'

- org-formation/090-systems-manager/_tasks.yaml
Cloudformation is giving the error "Only the Management Account of an AWS Organization can create and manage Patch Policies configurations" despite the account being registered as a delegated administrator.
Deploy to the organization root account instead of the sysman account.
> [IT-3940] Deploy to the root account

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
This change adds the public S3 bucket created during https://sagebionetworks.jira.com/browse/DPE-1234 to the list of buckets that is excluded during the scan/flagging process per the comment here: https://github.com/Sage-Bionetworks-Workflows/eks-stack/pull/57#pullrequestreview-2695320548
> [DPE-1234] Exclude the `synapse-croissant-metadata` as a public S3 bucket

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
The buckets arn:aws:s3:::cfn-snippets-bucket-cloudformationsnippetsbucket-elu83sv8ocdz and arn:aws:s3:::sagebase-rules-microservice-outputbucket-17vzcnk2xnq0 should be public.
> [IT-4168] Suppress security hub findings

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
The arn:aws:s3:::sage-igenomes bucket should be public
> [IT-4100] Resolve security hub finding 2.1.5.2

- org-formation/650-identity-providers/_tasks.yaml
This PR adds a couple of buckets and distributions for the AMP-ALS portal to the permissions given to the OIDC role used to deploy from the Synapse monorepo.
> IT-4277: Add amp-als buckets and dists to synapse-monorepo OIDC permissions

- org-formation/700-aws-sso/_tasks.yaml
As instructed in our wiki[1], this will allow SSO read only users the ability
to search for Sage generated shared AMIs from any AWS account.
[1] https://sagebionetworks.jira.com/wiki/spaces/IT/pages/914882624/AWS+Image+Repository
> [IT-3831] Update SSO read only access

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
Don't require the Bridge service users to rotate access keys every 90 days. A lack of certainty around knowing all locations to update creates a risk of a prolonged outage with data loss.
Also refactor suppression for credentials unused for 45 days so that it is also restricted to the Bridge service users.
> [IT-4089] Suppress access-key rotation for service users

- sceptre/strides-ampad-workflows/templates/jumpcloud-idp.yaml
When the user provisions an EC2 instance with an instance profile they need the ability to pass permissions to an EC2 instance.
> [IT-4378] Give SSO user extra IAM permissions

- README.md
- sceptre/admincentral/README.md
- sceptre/bridge/README.md
- sceptre/imagecentral/README.md
- sceptre/itsandbox/README.md
- sceptre/logcentral/README.md
- sceptre/sageit/README.md
- sceptre/scicomp/README.md
- sceptre/synapsedev/README.md
- sceptre/synapseprod/README.md
We no longer use travis CI so remove references to it.
> remove references to travis-ci

- org-formation/090-systems-manager/QuickSetup-PatchPolicy.yaml
- org-formation/090-systems-manager/_tasks.yaml
A second attempt at creating a Patch Policy using SSM QuickSetup
to update all managed nodes in the organization. Add poorly-
documented parameters. Also create an S3 bucket for patch logs
(every member account must have write access to the bucket).
The local deployment roles were created automatically by SSM QuickSetup
by creating an empty patch policy in AWS Portal.
Documentation provided by AWS in a support case:
General process:
https://repost.aws/questions/QUscQKRgKDQ0O7gjhTuioxzw/do-i-need-to-be-in-the-managerment-account-to-use-system-manager-patch-manager-to-patch-instances-across-an-organization
https://docs.aws.amazon.com/systems-manager/latest/userguide/quick-setup-config-types.html
https://docs.aws.amazon.com/systems-manager/latest/userguide/quick-setup-patch-manager.html …
> [IT-4287] Use SSM QuickSetup to create a Patch Policy

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
Another attempt at PR #1399 which was reverted in PR #1402
My theory is that the `AWS::Events::Rule` has a character size limit
and PR #1401 bumped it over the limit.  This PR creates a separate
suppression rule.
> [IT-4166] suppress security hub finding 2.1.5.2

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
Fix the following AWS deployment failure[1] by using *:
```
ERROR: Resource SuppressFindingsForPublicBucketsRule2 failed because
Resource handler returned message: "Parameter EventPattern for rule
sagebase-securityhub-supp-SuppressFindingsForPublic-UQVAKg5lkGea
exceeds limit of 2048.
```
[1] https://github.com/Sage-Bionetworks-IT/organizations-infra/actions/runs/14889997994/job/41819446177
> [IT-4166] Shorten EventPattern parameter

- org-formation/740-cloudwatch-dashboard/_tasks.yaml
CloudWatch-CrossAccountSharingRole resource is being deployed multiple times which is causing failures during creation of new AWS accounts.
I believe what is happening is that the AWS cloudwatch service is creating a CloudWatch-CrossAccountSharingRole when we vend new AWS accounts thru our CI/CD.  Then org-formation is deploying the duplicate role later in the vending process which causes the failure.
Since AWS is already creating the required role I guess the fix would be to remove the deployment of that role from our org-formation setup.
> [IT-4347] Remove deployment of CloudWatch-CrossAccountSharingRole

- org-formation/800-redirects/_tasks.yaml
Set up DNS CNAME for `modeladexplorer` environments based on [this README](https://github.com/Sage-Bionetworks-IT/modeladexplorer-infra?tab=readme-ov-file#dns). `SourceHostedZoneId` taken from [this comment](https://sagebionetworks.jira.com/browse/IT-4426?focusedCommentId=250048).
> MG-182: setup DNS CNAME for modeladexplorer environments

- org-formation/650-identity-providers/_tasks.yaml
The legacy Agora repos have been archived.  Remove the Github OIDC role for them.
> [IT-4418] Remove Github OIDC for Agora

- sceptre/synapseprod/templates/SynapseCMK-template.json
This PR adds the permission to call ApiGateway to the deployer role in SynapseProd.
The role in SynapseDev already has the permission.
This is needed to deploy stack-546.
> IT-4450: Add perms for ApiGateway to deployment role

- org-formation/075-security-hub/security-hub.yaml
Use Security Hub automation rule[1] to suppress 2.1.5.2 findings in org-sagebase-sageit account.
This is also a partial fix for issue IT-4445
[1] https://docs.aws.amazon.com/securityhub/latest/userguide/examples-automation-rules.html#example-automation-rule-change-workflow
> [IT-4166] Suppress security hub findings

- org-formation/075-security-hub/security-hub.yaml
fix following deploying error:
```
ERROR: Resource SuppressSecHubFindingsForIam failed because Properties
validation failed for resource SuppressSecHubFindingsForIam with message:
[#/Criteria: extraneous key [Actions] is not permitted].
```
> Fix Security hub suppression rul GeneratorId value

- org-formation/075-security-hub/security-hub-suppress-infra.yaml
- org-formation/075-security-hub/security-hub.yaml
Move SuppressFindingsForBridgeAccounts to security hub's native automation rules system to suppress findings.
> [IT-4445] Move security suppression to navtive system

- org-formation/090-systems-manager/_tasks.yaml
Deploy lambda-tag-patch-group in all accounts to force inclusion of all supported resource types into our unified patch group.
> [IT-3940] Deploy lambda to tag patch group resources

- org-formation/650-identity-providers/_tasks.yaml
This PR creates an OIDC role with permissions to deploy the Synapse status lambda (https://github.com/Sage-Bionetworks/synapse-status-lambda/pull/1/files)  to the SynapseProd account.
> PLFM-7095: setup OIDC for synapse-status-lambda

- org-formation/090-systems-manager/patch-resource-group.yaml
Got this message from a failed deployment[1]:
```
ERROR: Resource TagBasedGroup failed because Resource handler returned
message: "Invalid request provided: Query not valid: One or more resource
types are not valid: AWS::OpsWorks::Instance 
```
AWS OpsWorks is no longer supported[2] and we never used it anyway so removing references to it.
[1] https://github.com/Sage-Bionetworks-IT/organizations-infra/actions/runs/16654510163/job/47135896313
[2] https://docs.aws.amazon.com/opsworks/latest/userguide/stacks-eol-faqs.html
> Remove references to AWS OpsWorks

- org-formation/800-redirects/_tasks.yaml
Use S3 and cloudfront to setup a redirect from
treat-ad.org to treatad.org
> [IT-4498] Setup redirect for apex domain

- org-formation/800-redirects/_tasks.yaml
- org-formation/800-redirects/s3-apex-redirector.yaml
This reverts commit 9129a0a4f3a099b79b38246249b00c25f56a4ec8.
This is a 2nd attempt at PR #1457 using a new S3 bucket redirector template.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/436
> [IT-4498] Another attempt at redirect for apex domain (#1459)

- org-formation/050-costs/_tasks.yaml
Update to latest version of lambda-mips-api to pull in the new `/balances` endpoint, and deploy lambda-finops-floqast-sftp to consume that endpoint on a daily basis and upload the result to FloQast via SFTP.
This version of lambda-mips-api renames the parameter `MipsOrganization` -> `MipOrganization` to align with the name of the service.
The new daily service runs at 8pm PDT (4am UTC)
> [IT-4485] Update lambda-mips-api and deploy lambda-finops-floqast-sftp

- org-formation/050-costs/_tasks.yaml
The deploy is failing because the category rules are too long.
The cost category rules have become too long due to a change in lambda-mips-api that includes even more inactive accounts. Only create rules for active accounts to unblock the deploy pipeline. Resources tagged with deprecated accounts will still create categories for the arbitrary tag value, but without deduplicating names.
> bugfix: only create categories for active accounts

- sceptre/scipool/config/develop/cfn-cr-synapse-tagger.yaml
- sceptre/scipool/config/prod/cfn-cr-synapse-tagger.yaml
- sceptre/scipool/config/strides/cfn-cr-synapse-tagger.yaml
Update teh cfn-cr-synapse-tagger lambda to include a refactored get_synapse_owner_id method.
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger/pull/63
> [IT-4483] Update cfn-cr-synapse-tagger lambda version
