templates/accounts.yaml

Give Mike access to organizations and billing.

Update access permissions for billing

---

.travis.yml

run sceptre deploys to each account on separate VMs

make travis deploy sceptre in parallel

---

.travis.yml

add workaround to dis-associate and re-associate SC actions.

fix sceptre scipool deploy

---

.github/workflows/aws-deploy.yaml

make pre-commit job run on every push and merge.
make deployments run only on merges to master

update GH workflow

---

sceptre/scipool/templates/sc-ec2vpc-launchrole.yaml
sceptre/scipool/templates/sc-enduser-iam.yaml
sceptre/scipool/templates/sc-s3-launchrole.yaml

This gives users the ability to *potentially* see if their SC updates
will cause data loss.

[SC-291] Give SC users access to cloudformation change sets

---

org-formation/300-account-defaults/kms-key.yaml
org-formation/300-account-defaults/organization-tasks.yaml

Bootstrap every AWS account with a kms key for IT to use.
The idea is to have this key available in every account in case
we need to setup secrets for IT to use.

create KMS key

---

sceptre/synapseprod/templates/SynapseCMK-template.json

Add STS permissions to deployer role in synapseprod account

Add STS permissions to deployer role

---

sceptre/scipool/templates/sc-product-s3-private-enc.yaml
sceptre/scipool/templates/sc-product-s3-synapse.yaml

Fix cloudformation yaml linter errors

Fix cloudformation yaml linter errors

---

org-formation/600-access/organization-tasks.yaml
org-formation/organization-tasks.yaml

Add an IAM service account to AWS sandbox for @thomasyu888 so he
can use it to deploy his app https://github.com/nlpsandbox/aws-cloudformation
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/272

Add a service user for NLP

---

sceptre/scipool/config/develop/docker-runner-efs.yaml
sceptre/scipool/config/prod/docker-runner-efs.yaml
sceptre/scipool/config/strides/docker-runner-efs.yaml

Setup a VPC for us to deploy EFS into during provisioning of
SC products.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/281

[SC-306] deploy VPC for EFS

---

sceptre/synapseprod/templates/accounts.yaml

[PLFM-6654] Temporary fix to give Bruce Access to Athena (until we replace IAM users).

PLFM-6654: Add Bruce to AnalyticsUsersGroup

---

org-formation/_parameters.yaml
org-formation/organization.yaml

Setup a budget for mobile health data engeering account.  Get notified
if the account cost exceed the expected threshold.
depends on #115

[IT-1101] budget notification for mobile health data engeering account

---

sceptre/synapsedev/templates/SynapseCMK-template.json

This PR adds a couple of perms to the deployer to allow setting up step functions

Add perms to deployer role to setup step fcts

---

sceptre/synapsedev/templates/accounts.yaml

This is for the dev bootstrap.

Adding William's IAM profile

---

org-formation/600-access/_tasks.yaml

PR Checklist:
To validate files run: `pre-commit run --all-files`

Add in NLP CI service account

---

sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-notebook.yaml

depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/245

use most recent tag that fixes policy reference issue (SC-260)

---

sceptre/synapsedev/templates/accounts.yaml
sceptre/synapsedw/templates/accounts.yaml
sceptre/synapseprod/templates/accounts.yaml

Removing IAM entity

---

sceptre/sandbox/config/prod/park-my-cloud.yaml

Apparently Michael Mason is still using Sage cloud resources.
Revert "[SC-148] Remove parkmycloud from sandbox (#125)"
This reverts commit 740b997870b6ca40dc5f0775a89a24e9eaa9cb10.
[SC-148]: https://sagebionetworks.jira.com/browse/SC-148

[IT-1200] Restore parkmycloud

---

.github/workflows/aws-deploy.yaml
.pre-commit-config.yaml

Add a pre-commit hooki[1] to validate GH actions workflows.
[1] https://github.com/sirosen/check-jsonschema

add pre-commit hook

---

org-formation/_tasks.yaml

Forgot to enable the deployment for AWS config on PR #122

Enable AWS Config

---

org-formation/700-aws-sso/_tasks.yaml

Setup to allow users in the JC aws-nlp-sandbox-admin group access
to the AWS sandbox account.

[IT-1178] Setup SSO access to AWS NLP Sandbox account

---

org-formation/700-aws-sso/_tasks.yaml

Setup to allow users in the JC aws-workflow-nextflow-admin group access
to the AWS workflow nextflow dev & prod accounts.

[IT-1178] Setup SSO access to AWS workflow nextflow account

---

org-formation/600-access/_tasks.yaml

Give Jon Ryser from GenUI access to our iAtlas account so he can deploy
the AWS resources for the iAtlas project.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/301

Give iAtlas collaborator access

---

sceptre/admincentral/templates/VPCPeer.yaml

This PR should fix the validation error in https://github.com/Sage-Bionetworks-IT/organizations-infra/runs/2603419390?check_suite_focus=true.

IT-1221: Add support for /20 CIDR

---

org-formation/600-access/_tasks.yaml
org-formation/organization.yaml

In this PR, I'm creating an AWS account for the HTAN project under `ScienceDevOU`, setting up access via JumpCloud, and provisioning a service account for use on our provisioner [repository](https://github.com/ncihtan/aws-htan-infra). Once this PR is open, I'll comment on [IT-1250](https://sagebionetworks.jira.com/browse/IT-1250) to obtain the JumpCloud metadata document, which I will add to this PR. 
I'm hoping to use this PR as a clean example of how to bootstrap an AWS account. This will simplify the [documentation](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2058878986/Bootstrapping+AWS+Project+Accounts). 
----
To validate files run: `pre-commit run --all-files`

[IT-1250] Bootstrap AWS account for HTAN project under ScienceDevOU

---

org-formation/700-aws-sso/_tasks.yaml

Setup SSO access for HTAN developer account
depends on #189

[IT-1250] HTAN SSO

---

org-formation/010-scps/_tasks.yaml

Re-enable service control policies that were temporarily commented out
in PR #153.

Re-enable SCPs

---

org-formation/organization.yaml

I'm adjusting the budget threshold to something a bit more reasonable. 
----
To validate files run: `pre-commit run --all-files`

Lower budget alarm threshold for htan-dev

---

org-formation/organization.yaml

Most account names have been updated, this PR just syncs the updated accounts names.

IT-1148: Updates to match actual account names

---

sceptre/synapsedw/templates/accounts.yaml
sceptre/synapseprod/templates/accounts.yaml

This PR removes Aaron's IAM user from synapseprod and synapsedw accounts.

IT-1294: remove-ahayden IAM user

---

sceptre/scipool/templates/sc-product-ec2-linux-docker.j2
sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-notebook.j2
sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-workflows.j2
sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud.j2
sceptre/scipool/templates/sc-product-ec2-windows-jumpcloud.j2
sceptre/scipool/templates/sc-product-s3-private-enc.j2
sceptre/scipool/templates/sc-product-s3-synapse.j2

Fix Default setting on parameters

Fix templates

---

sceptre/scipool/config/develop/cfn-cr-sc-bucket-policy.yaml
sceptre/scipool/config/prod/cfn-cr-sc-bucket-policy.yaml
sceptre/scipool/config/strides/cfn-cr-sc-bucket-policy.yaml

Update the custom resource that creates the bucket policy to conform
to the policy in issue IT-1295
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-bucket-policy/pull/4

[SC-312] Update cfn-cr-sc-bucket-policy version

---

sceptre/scipool/config/develop/sc-product-s3-synapse.yaml
sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
sceptre/scipool/config/strides/sc-product-s3-synapse.yaml

Update the synapse bucket product that contains the bucket configuration
to conform to the config defined in issue IT-1295
depends on https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/235

[SC-312] Update service catalog product

---

org-formation/700-aws-sso/_tasks.yaml

Add the following:
For nextflow-dev, viewer and developer groups
For nextflow-prod, a viewer group

Add additional SSO groups for nextflow accounts

---

org-formation/300-account-defaults/_tasks.yaml
org-formation/700-aws-sso/_tasks.yaml
org-formation/organization.yaml

Change account name from MobileHealthDataEngineering to include
`dev` in the name.

[IT-1354] Change AWS account name

---

.github/workflows/aws-deploy.yaml

Setup CI to run a linter[1] on jinja templates.
[1] https://github.com/drm/jinja2-lint.git

[IT-1332] lint jinja templates

---

org-formation/organization.yaml

Add a prod account for mobilehealth-toolbox ETL

Add mobilehealth data-engineering prod account

---

org-formation/700-aws-sso/_tasks.yaml

Add sso group for mobile health prod admins
Depends on #250

ETL-35 Add sso group for mobile health prod admins

---

org-formation/600-access/_tasks.yaml

CI accounts for mobile health data engineering
depends on #250

CI accounts for mobile health data engineering

---

sceptre/synapsedev/templates/accounts.yaml
sceptre/synapseprod/templates/accounts.yaml

IT-1345: Remove JKiang user

---

.github/workflows/aws-deploy.yaml

We forgot to remove this from CI as part of PR #241

[SC-350] Remove deprecated products

---

sceptre/admincentral/config/prod/peering-nextflow-dev.yaml
sceptre/admincentral/config/prod/peering-nextflow-prod.yaml

removes peering files for nextflow dev and prod accounts

Remove peering for nextflow accounts

---

.github/workflows/aws-deploy.yaml

Setup CI to deploy CFN templates to bmgfki account
depends on https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/260

[SC-307] Setup CI deployment to bmgfki account

---

sceptre/scipool/config/bmgfki/tgw-spoke-gatespoolvpc.yaml

Setup the gatespoolvpc as a spoke to the Sage transit gateway

[SC-307] Setup vpc for bmgfki as a transit gateway spoke

---

sceptre/admincentral/templates/cfn-service-catalog-snippets.yaml

* Fix references to TgwSecurityGroupId parameter
* Add parameters for bmgfki account
depends on #268

[SC-307] Update service catalog snippets for bmgfki

---

sceptre/scipool/templates/prod/lambda-budgets/budget-rules.yaml

remove budget for '2021 Hack for RARE Participants' team

IT-1380 remove budget for '2021 Hack for RARE Participants' team

---

sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-workflows.yaml
sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud.yaml

Added v1.1.21 to notebook product.  Allows more simultaneously open files on notebook product and reduces number of instance types on all EC2 products.

SC-318 added v1.1.21 to notebook product.  

---

sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/bmgfki/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-workflows.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud.yaml

having tested changes in dev, now apply to prod, strides, bmgf-ki
changes include:  allowing more concurrent open files in R-Studio instance and reducing number of instance types to 77 across EC2 products.

SC-318:  having tested changes in dev, now apply to prod, strides, bmgf-ki

---

org-formation/600-access/_tasks.yaml
org-formation/organization.yaml

[IT-1389] Create service accounts

---

org-formation/010-scps/_tasks.yaml
org-formation/organization.yaml

Setup a separate service catalog OU to de-couple the policies from
other accounts.

Service Catalog OU

---

sceptre/scipool/templates/bmgfki/lambda-budgets/budget-rules.yaml

Set the budget for BMGFKI service catalog users to $5000 per month.

[SC-307] Increase budget for BMGFKI users

---

sceptre/scipool/config/bmgfki/lambda-bucket-cleanup.yaml
sceptre/scipool/config/develop/lambda-bucket-cleanup.yaml
sceptre/scipool/config/prod/lambda-bucket-cleanup.yaml
sceptre/scipool/config/strides/lambda-bucket-cleanup.yaml

Deploy the SC bucket cleanup lambda to all SC accounts.
depends on PR https://github.com/Sage-Bionetworks-IT/lambda-sc-bucket-cleanup/pull/1

[SC-362] Install SC bucket cleanup lambda

---

sceptre/scipool/config/bmgfki/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-notebook.yaml

using new AMI in R-Studio notebook product in prod, strides, bmgf-ki

SC-318 using new AMI in R-Studio notebook product in prod, strides, bmgf-ki

---

org-formation/070-guard-duty/_tasks.yaml

Our security guy made a request to monitor all AWS scientific
accounts with guardduty.

[IT-1391] Enable guardduty on scientific accounts

---

org-formation/010-scps/_tasks.yaml

This will include changes in PR https://github.com/Sage-Bionetworks/aws-infra/pull/326
which will allow S3 read access to all regions.  This will be applied
to all AWS accounts in our ORG.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/326

Update all accounts with S3 read access

---

sceptre/scipool/config/develop/sc-product-scheduled-jobs.yaml
sceptre/scipool/templates/sc-product-scheduled-jobs.j2

Parameterize ProvisioningArtifactParameters to allow passing in new
versions.  Setup UpdateProductVersions to remove all previous versions
from product selection.

Fix scheuled jobs product

---

sceptre/scipool/config/develop/sc-product-scheduled-jobs.yaml

sc-batch-fargate.yaml v1.1.29 is broken so we need to remove it
otherwise it will fail the entire build.  Replacing it with v1.1.30

fix the SC scheduled jobs product

---

sceptre/scipool/config/bmgfki/sc-tag-options.yaml
sceptre/scipool/config/develop/sc-tag-options.yaml
sceptre/scipool/config/prod/sc-tag-options.yaml
sceptre/scipool/config/strides/sc-tag-options.yaml
sceptre/scipool/templates/sc-tag-options.j2

Add a service catalog CostCenter tag.  It is a required tag so users
will need to pick one cost center from the list when provisioning SC
products.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/327 https://github.com/Sage-Bionetworks/aws-infra/pull/329

[SC-373] Add a cost center tag option

---

sceptre/scipool/config/bmgfki/sc-tag-options.yaml
sceptre/scipool/config/develop/sc-tag-options.yaml
sceptre/scipool/config/prod/sc-tag-options.yaml
sceptre/scipool/config/strides/sc-tag-options.yaml
sceptre/scipool/templates/sc-tag-options.j2

This reverts commit 901c210fc838b76c8cd3d8db341df64e3abf83bf,
commit de61d4b1e54f9821f87e38d76a7c6a605511c560
and commit d4f7e6070bfff7df3ddf6909d91a6dfe8a7bd6d9
seeing this error in the build logs.
```
[2022-01-05 01:11:19] - /home/runner/work/organizations-infra/organizations-infra/sceptre/scipool/templates/sc-tag-options.j2:21:
Template error in 'top-level template code' => `{% for CostCenter in sceptre_user_data.CostCenters %}`
```

Revert "[SC-373] Add a cost center tag"

---

sceptre/scipool/config/develop/sc-product-scheduled-jobs.yaml

Update the schreduled jobs product with change from
PR https://github.com/Sage-Bionetworks/service-catalog-library/pull/270

[SC-306] Update scheduled jobs product

---

sceptre/scipool/config/bmgfki/PyPlate.yaml
sceptre/scipool/config/develop/PyPlate.yaml
sceptre/scipool/config/prod/PyPlate.yaml
sceptre/scipool/config/strides/PyPlate.yaml

Pin PyPlate macro to a specific version
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/333

Pin cloudformation PyPlate macro

---

sceptre/scipool/config/prod/scheduledjobsvpc.yaml

Take PR
https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/317
which was already installed and tested on scipooldev and apply it
to scipoolprod.

[SC-306] Setup a VPC for SC Scheduled Jobs product

---

sceptre/scipool/config/prod/sc-portfolio-scheduled-jobs.yaml
sceptre/scipool/config/prod/sc-product-scheduled-jobs.yaml
sceptre/scipool/config/prod/sc-scheduled-jobs-launchrole.yaml
sceptre/scipool/config/prod/sc-tag-options.yaml

Take PR
https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/325
which has already been installed and tested on scipooldev and install
it on scipoolprod.
Note: we are not installing this product to bmgfki or strides accounts
depends on https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/365

[SC-306] install schedule jobs product

---

sceptre/scipool/config/bmgfki/sc-product-s3-private-enc.yaml
sceptre/scipool/config/bmgfki/sc-product-s3-synapse.yaml
sceptre/scipool/config/develop/sc-product-s3-private-enc.yaml
sceptre/scipool/config/develop/sc-product-s3-synapse.yaml
sceptre/scipool/config/prod/sc-product-s3-private-enc.yaml
sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
sceptre/scipool/config/strides/sc-product-s3-private-enc.yaml
sceptre/scipool/config/strides/sc-product-s3-synapse.yaml

Update S3 product with PR https://github.com/Sage-Bionetworks/service-catalog-library/pull/272
which pins the cfn-cr-same-region-bucket-download dependency

Update S3 product

---

org-formation/710-tgw/vpc.yaml

Along with PR #392 we want to remove anything associated with
providing VPC outbound routes

Fix VPC update

---

org-formation/organization.yaml

Create a new AWS account for Agora project.

[IT-1663] New AWS account for Agora

---

org-formation/720-client-vpn/_tasks.yaml

* VpnEndpointRedirect depends on VPN successful setup
* replace static VPN endpoint with dynamic reference

[IT-1234] VPN dependency and reference

---

package-lock.json
package.json

It good practice to keep up to date with upstream version.

update org-formation version

---

org-formation/710-tgw/_tasks.yaml
org-formation/720-client-vpn/_tasks.yaml

* Setup Bridge VPCs in TGW
* Allow JC users to access VPCs in bridge VPCs thru the VPN

[IT-1234] Setup VPN access to Bridge

---

org-formation/700-aws-sso/_tasks.yaml

Adds viewer roles to digital health data engineering accounts as per ETL-102

Add viewer roles for digital health etl accounts

---

org-formation/700-aws-sso/_tasks.yaml

This sets up Admin and Developer access to org-sagebase-agora-prod
AWS account thru jumpcloud.  The matching groups in JC have already
been created.

[IT-1663] Setup JC access to agora AWS account

---

org-formation/700-aws-sso/_tasks.yaml

[x] Deny all actions on all resources
[x] Passes pre-commit

[IT-1674] Widen scope of cross-account deny

---

org-formation/700-aws-sso/_tasks.yaml

Provide our security auditors more access to cloud resources so
they can review more things in our AWS accounts.

[IT-1757] give our security guy access to security stuff

---

org-formation/700-aws-sso/_tasks.yaml

Revise to Inspector V2 and remove GD role, which is redundant

Update secaudit attached policies

---

org-formation/075-security-hub/README.md
org-formation/075-security-hub/_tasks.yaml
org-formation/075-security-hub/notifications.njk
org-formation/075-security-hub/security-hub.yaml

Setup security hub with notifications sent to endpoints.
Multiple protocols and endpoints can be configured.
This template is based on templates provided by
https://asecure.cloud/p/config_securityhub

[IT-607] Setup Security Hub

---

org-formation/720-client-vpn/_tasks.yaml

Give more specific Jumcloud groups accees to VPCs thru
the AWS VPN.

[IT-1234] Update JC groups for VPN access

---

org-formation/700-aws-sso/_tasks.yaml

[ x ] Adds AWS support ticket access and security hub read managed roles
[ x ] Passes precommit

Additional secaudit roles

---

org-formation/720-client-vpn/_tasks.yaml

This is a redo of commit b8164f5.  It failed last time then reverted
so we are retrying again.

redo update JC groups for VPN access

---

org-formation/organization.yaml

Our SDLC requires separating dev environments from prod
environments therefore we are creating a new AWS account
for agora dev environment.

[IT-1663] Setup an Agora dev AWS account

---

org-formation/700-aws-sso/_tasks.yaml

Setup integration with Jumpcloud to allow JC users access to the
org-sagebase-agora-dev account.

[IT-1663] Setup SSO for agora dev account

---

sceptre/scicomp/config/prod/maintenance.yaml
sceptre/scipool/config/bmgfki/maintenance.yaml
sceptre/scipool/config/develop/maintenance.yaml
sceptre/scipool/config/prod/maintenance.yaml
sceptre/scipool/config/strides/maintenance.yaml

Update cron duration in shared maintenance template
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/339

[IT-1742] Updated cron duration to 6 hours

---

org-formation/organization.yaml

Create a new account for running open source Sceptre[1] integration
tests.
[1] https://github.com/Sceptre/sceptre

[IT-1763] New aws account for Sceptre

---

sceptre/synapsedev/templates/accounts.yaml

Access key has been removed, this PR removes the user. Passed pre-commit locally.

IT-1616: Remove user

---

org-formation/720-client-vpn/_tasks.yaml

This should give devs access to the AWS VPN

IT-1842: Access to synapse developers

---

org-formation/710-tgw/_tasks.yaml
org-formation/710-tgw/tgw-spoke-synapse.njk
org-formation/720-client-vpn/_tasks.yaml

* Setup routes from synapseprod VPC to TGW hub VPC
* Allow JC users to access synapseprod VPC resources thru the VPN
Note that the synapse VPC is very unique so we need to handle it with
a custom nunjucks template.

[IT-1234] Setup TGW and VPN for synapseprod

---

org-formation/710-tgw/_tasks.yaml
org-formation/720-client-vpn/_tasks.yaml

* Setup routes from synapseprod VPC to TGW hub VPC
* Allow JC users to access synapseprod VPC resources thru the VPN

[IT-1234] Setup TGW and VPN for scipooldev and scipoolprod

---

sceptre/bridge/config/develop/BridgeServer2-vpc.yaml
sceptre/bridge/config/develop/bridge-aux.yaml
sceptre/bridge/config/prod/BridgeServer2-vpc.yaml
sceptre/itsandbox/config/prod/dustbunnyvpc.yaml
sceptre/sageit/config/prod/defaultvpc.yaml
sceptre/sandbox/config/prod/sandcastlevpc.yaml
sceptre/scicomp/config/prod/computevpc.yaml
sceptre/scicomp/config/prod/snowflakevpc.yaml
sceptre/scipool/config/bmgfki/gatespoolvpc.yaml
sceptre/scipool/config/develop/cesspoolvpc.yaml
sceptre/scipool/config/develop/scheduledjobsvpc.yaml
sceptre/scipool/config/prod/internalpoolvpc.yaml
sceptre/scipool/config/prod/scheduledjobsvpc.yaml
sceptre/scipool/config/strides/stridespoolvpc.yaml
sceptre/synapsedev/config/prod/vpc.yaml
sceptre/synapsedw/config/prod/vpc.yaml
sceptre/synapseprod/config/prod/synapse-ops-vpc-v2.yaml
sceptre/synapseprod/config/prod/vpc.yaml

Allow users to access resources in the VPCs from the AWS VPN
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/338

[IT-1234] Setup VPN access

---

org-formation/720-client-vpn/_tasks.yaml

Removed bridgdevs access to bridgeprod infra

IT-1234: no bridgedevs access to prod

---

sceptre/synapsedev/templates/SynapseCMK-template.json

PLFM-7262: Add iam perms, need to back down later

---

org-formation/710-tgw/_tasks.yaml
org-formation/720-client-vpn/_tasks.yaml

Attempt to access DW infra on VPN

IT-1850: Fix access to DW

---

sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/bmgfki/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/bmgfki/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/prod/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/strides/sc-product-ec2-windows-jumpcloud.yaml

This PR updates all EC2 products for every production service catalog.
These versions were manually tested in scipooldev with PR #471 and seem
to be working as expected.

[IT-1234] Update SC products

---

sceptre/synapseprod/templates/SynapseCMK-template.json

Looks like it got out of sync + add per changes in dev.

PLFM-7096: Fix perms

---

org-formation/600-access/_tasks.yaml

This change is intended to grant Matthias Courville developer access to the agora2-dev environment.

Grant Matthias Courville (GenUI) access to agora2-dev

---

org-formation/650-identity-providers/_tasks.yaml

Deploy OIDC to every AWS account to allow deployment from
organization-infra repo

[IT-1934] Deploy github OIDC

---

org-formation/organization.yaml

We are evaluating Saturn Cloud[1] as a possible solution to host
shiny apps.  We plan to run it on our own AWS so we need to
create an account to test and evaluate it's potential.
[1] https://saturncloud.io/

[IT-1960] New AWS account for saturn cloud

---

org-formation/060-cloudtrail/_tasks.yaml

Create a KMS key and use that key to encrypt cloudwatch
trail logs.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/347

[IT-1904] Encrypt cloudwatch trails

---

org-formation/060-cloudtrail/_tasks.yaml

Create a KMS key and use that key to encrypt cloudtrail
trail logs.
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/347
Note: This change was incorrectly done in PR #516. This is a redo.

[IT-1904] Encrypt cloudtrail

---

sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml

Update the docker product with a template that contains the latest
amazon linux AMI.
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/279

[SC-390] Update docker product

---

org-formation/organization.yaml

Create an AWS account for Vijay Yadav

[IT-1787] Personal AWS account

---

org-formation/700-aws-sso/_tasks.yaml

Setup SSO admin access for a personal aws account (8dxfh53)
This will allow Vijay access to his personal AWS account
depends on #511

[IT-1787] SSO for personal AWS account

---

sceptre/synapsedev/templates/accounts.yaml

This PR adds an IAM account for Peter Harvey.

IT-2014: Add IAM user in SynapseDev

---

sceptre/admincentral/config/prod/peering-nlpsandbox.yaml

This PR removes the admincentral side of the peering with nlpsandbox account. Don't merge until https://github.com/nlpsandbox/nlpsandbox-infra/pull/41 is merged.

IT-1874: Remove peering with nlpsandbox account

---

sceptre/scipool/config/strides/sc-portfolio-scheduled-jobs.yaml
sceptre/scipool/config/strides/sc-product-scheduled-jobs.yaml
sceptre/scipool/config/strides/sc-scheduled-jobs-launchrole.yaml
sceptre/scipool/config/strides/sc-tag-options.yaml
sceptre/scipool/config/strides/scheduledjobsvpc.yaml

Add the Scheduled Jobs product to the Service catalog in the
Strides AWS account.

[SC-388] Setup Scheduled jobs product in Strides

---

org-formation/040-budgets/cur.yaml

The last attempt to fix this used an invalid value.
PR Checklist:
[x] Describe and explain your intentions for this change
[x] Setup pre-commit and run the validators (info in README.md)

Fix typo: Public -> PublicRead

---

sceptre/scipool/config/bmgfki/sc-product-s3-private-enc.yaml
sceptre/scipool/config/bmgfki/sc-product-s3-synapse.yaml
sceptre/scipool/config/develop/sc-product-s3-private-enc.yaml
sceptre/scipool/config/develop/sc-product-s3-synapse.yaml
sceptre/scipool/config/prod/sc-product-s3-private-enc.yaml
sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
sceptre/scipool/config/strides/sc-product-s3-private-enc.yaml
sceptre/scipool/config/strides/sc-product-s3-synapse.yaml

Disable bucket ACLs in service catalog s3 products
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/280

[IT-2075] Update S3 products

---

sceptre/scipool/sc-tag-options/internal/Projects.json

per Pranav request, add a `recover` tag to the list of projects
for the service catalog.

Add a service catalog project tag

---

sceptre/scipool/config/bmgfki/cfn-cr-saml-provider.yaml
sceptre/strides-ampad-workflows/config/prod/cfn-cr-saml-provider.yaml
sceptre/strides/config/prod/cfn-cr-saml-provider.yaml

We want to pin just in case we need to revert back to a working version.

Pin cfn-cr-saml-provider lambda

---

org-formation/720-client-vpn/_tasks.yaml
sceptre/bridge/config/prod/bridge-ops.yaml

Pin to a specific template version in case we need to roll back
to a working version.

Pin template version

---

org-formation/_default_org_tags.yaml
org-formation/organization.yaml

Set 'Platform Infrastructure' as the default CostCenter tag, and
add necessary overrides.

[IT-1530] Add missing account CostCenter tags

---

.pre-commit-config.yaml
org-formation/_default_org_tags.yaml
org-formation/_platform_org_tags.yaml
org-formation/organization.yaml

Move the platform tag values to their own file, and use NO PROGRAM as the default.

[IT-1530] Change default tag values to NO PROGRAM

---

org-formation/300-account-defaults/_tasks.yaml

Update the ebs cleanup lambda to a version with a corrected cron schedule.

[IT-2051] Update ebs lambda

---

sceptre/synapseprod/config/prod/synapse-ops-vpc-v2.yaml

Same as #582, there are 2 infra VPCs (one of which needs to be deleted).

IT-2002: another vpc

---

sceptre/bridge/config/prod/maintenance.yaml
sceptre/scicomp/config/prod/maintenance.yaml

Forgot to remove obsolete patching mechanism in bridge and scicomp as part of PR #585

[IT-2089] Remove obsolete patching mechanism

---

sceptre/synapsedw/config/prod/vpc.yaml
sceptre/synapseprod/config/prod/synapse-ops-vpc-v2.yaml

Same as #589 in prod and dw accounts

IT-2030: Update infra vpc in synapseprod and dw

---

sceptre/bridge/config/develop/BridgeServer2-vpc.yaml

This PR updates the VPC in BridgeDev, same as #593.

IT-2030: Update vpc in BridgeDev

---

sceptre/bridge/config/develop/bridge-aux.yaml
sceptre/bridge/config/prod/BridgeServer2-vpc.yaml

This PR removes 10.1.0.0/16 from security groups. Same as #595 .

IT-2030: Finish Bridge vpn sg update

---

org-formation/700-aws-sso/_tasks.yaml

Test completed, removing the test policy.
This reverts commit 47263826a7e9c47a0f0f3de30e096b662c568729.

Revert "a policy to test out identity-central idea in IT-1967 (#597)"

---

org-formation/600-access/_tasks.yaml
org-formation/700-aws-sso/_tasks.yaml
sceptre/strides-ampad-workflows/templates/jumpcloud-idp.yaml
sceptre/strides/templates/jumpcloud-idp.yaml

Grant the viewer-plus role self-service access to the cost explorer, including creating/deleting reports and anomaly detection subscriptions.

[IT-1532] Grant access to the Cost Explorer

---

org-formation/600-access/_tasks.yaml

Fix a couple typos in the JSON syntax

Fix JSON syntax

---

org-formation/600-access/_tasks.yaml

Add braces needed to specify we have a list of objects.

Fix JSON syntax (again)

---

org-formation/600-access/_tasks.yaml
org-formation/700-aws-sso/_tasks.yaml
org-formation/_parameters.yaml

We need to use different parameters for managed policies managed by AWS vs managed by us. Update to use a template with support for the parameter used by custom managed policies.
depends-on: https://github.com/Sage-Bionetworks/aws-infra/pull/360

[IT-2268] Fix managed policies

---

org-formation/600-access/_tasks.yaml

We need to use a version of the managed-policy template with the PolicyName parameter added.

Use correct template version

---

sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/bmgfki/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/bmgfki/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/develop/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/prod/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/strides/sc-product-ec2-windows-jumpcloud.yaml

Update service catalog templates that deploy instances with attached volumes to propagate instance tags to those attached volumes.

[IT-2132] Update SC templates for tagging instance volumes

---

org-formation/730-cloudwatch-to-S3/CloudWatch2S3-main.yaml
org-formation/730-cloudwatch-to-S3/CloudWatch2S3-member.yaml
org-formation/_tasks.yaml

* Add 730-cloudwatch-to-S3 folder to the list of deployments.
* update version to 1.0.6
Forgot to do this in PR #621

[IT-1855] deploy resources in 730-cloudwatch-to-S3 folder

---

org-formation/060-cloudtrail/_tasks.yaml
org-formation/060-cloudtrail/cloudtrail-trail.yaml

This is a redo of PR #636 with fixes to templates that caused error in revert c7fa11213

[IT-2327] Enable cloudtrail log encryption

---

sceptre/scipool/config/bmgfki/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/develop/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/prod/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/strides/sc-product-ec2-windows-jumpcloud.yaml

Update the service catalog windows product to set the Jumpcloud powershell module version.
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/283

[SC-402] Update service catalog windows product

---

sceptre/scipool/config/bmgfki/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/develop/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/prod/sc-product-ec2-windows-jumpcloud.yaml
sceptre/scipool/config/strides/sc-product-ec2-windows-jumpcloud.yaml

Update the service catalog windows product
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/288

[SC-404] Update SC windows product

---

sceptre/scicomp/config/prod/sumologic-role.yaml

forgot to include this with commit 53a66da

remove sumologic integration

---

package-lock.json
package.json

This will make CI run with the latest 1.x version of org-formation

Use the latest compatible version of org-formation

---

sceptre/synapsedev/templates/accounts.yaml

This PR removes the IAM user for Peter Harvey and adds a user for Leon Li in the Synapse dev account.

Remove Peter and add Leon

---

sceptre/synapsedev/templates/accounts.yaml

Remove new AWS user to keep the CI running.
Related to https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/675 which failed to deploy.

remove synapsedev AWSIAMLeonLiUser

---

org-formation/700-aws-sso/_tasks.yaml

Add JC access to Genie BPC prod account as part of the account set up process.

IT-2398: Add JC access to Genie BPC Prod account

---

org-formation/700-aws-sso/_tasks.yaml

This PR is step 9 of [the account set up](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/745373697/Setup+AWS+Accounts) for the DCA prod account.

DCA-8: Set up viewer and viewer-plus access for DCA prod' account

---

sceptre/bridge/config/develop/BridgeServer2-vpc.yaml
sceptre/bridge/config/develop/bridge-aux.yaml
sceptre/bridge/config/prod/BridgeServer2-vpc.yaml
sceptre/bridge/templates/bridge.yaml
sceptre/itsandbox/config/prod/dustbunnyvpc.yaml
sceptre/sageit/config/prod/defaultvpc.yaml
sceptre/scicomp/config/prod/computevpc.yaml
sceptre/scicomp/config/prod/snowflakevpc.yaml

This PR removes more SGs that are flagged by SecurityHub

IT: Remove more BastianSGs

---

org-formation/700-aws-sso/_tasks.yaml

PR Checklist:
This follows instructions outlined in [step 3](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2058878986/Bootstrapping+AWS+Project+Accounts) to have the ability to access the DPE aws account via jumpcloud

[IBCDPE-460] Set up jumpcloud access to DPE prod account

---

org-formation/650-identity-providers/_tasks.yaml

Adding R/O role for SecurityHub-to-Jira script which will run as. GitHub action using OIDC integration.

IT-2599 Adding R/O role for SecurityHub-to-Jira

---

.github/workflows/aws-deploy.yaml
org-formation/200-baseline/_tasks.yaml
package.json

This PR should fix the deployment error caused by #706. Do I need something for the jq step?

IT-2591: Fix validation error

---

.github/workflows/aws-deploy.yaml
.github/workflows/validate.yaml

Update our version of node, and also update github actions to upgrade their versions of node as well.

[IT-2629] Update node version in aws-deploy

---

org-formation/050-costs/_tasks.yaml

Get ACM cert output from correct account

[IT-2954] Get ACM cert output from correct account

---

sceptre/synapsedw/config/prod/essentials.yaml
sceptre/synapseprod/config/prod/essentials.yaml

This PR pull in the changes to essentials.yaml (https://github.com/Sage-Bionetworks/aws-infra/pull/375).

Updated essentials.yaml version

---

org-formation/800-redirects/_tasks.yaml

Remove unneeded !Sub function

---

org-formation/800-redirects/_tasks.yaml

Now that this is correctly working for the dev stack, do the same thing for the prod stack.

[DCA-37] Add production DNS record for DCA app

---

sceptre/scipool/config/bmgfki/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-notebook.yaml

Update service catalog notebook product pick up the change to enable KMS key rotation
depends on PR https://github.com/Sage-Bionetworks/service-catalog-library/pull/289

[IT-2317] Update service catalog notebook product

---

sceptre/synapseprod/templates/accounts.yaml

This PR removes more IAM users (I'm the only one left).

IT-2393: Remove IAM accounts

---

org-formation/800-redirects/_tasks.yaml

Move the creation of the DNS record from CDK to org-formation.
Depends on: https://github.com/Sage-Bionetworks/schematic-infra/pull/10

[DCA-37] Create schematic-dev DNS record

---

org-formation/650-identity-providers/_tasks.yaml

This PR sets up the OIDC for AdminCentral account.
Ref: https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2806906984/Setup+Github+OIDC

IT-2672: Add aws-infra OIDC

---

org-formation/650-identity-providers/_tasks.yaml

This PR fixes the resource format error in #746 .

IT-2393: Fix resource fmt

---

org-formation/650-identity-providers/_tasks.yaml

PR Checklist:
[ x] Describe and explain your intentions for this change
This PR adds OIDC integration between the [dnt-infra](https://github.com/Sage-Bionetworks/dnt-infra) GitHub Repository and the `org-sagebase-dpe-prod` AWS account. This will allow us to have CI pipelines that update the AWS resources described in the repo automatically.
[x ] Setup pre-commit and run the validators (info in README.md)
pre-commit was set up and run successfully prior to opening this PR.

Bwmac/ibcdpe 467/dpe OIDC

---

org-formation/650-identity-providers/github-oidc-provider-access.njk

This PR should allow assuming the role on tag events.

IT-2672: Fix policy

---

org-formation/075-security-hub/security-hub-suppress-infra.yaml

Suppress findings about insecure HTTP access to public buckets.

[IT-2431] Suppress CIS 2.1.2 on public buckets

---

org-formation/800-redirects/_tasks.yaml

Add a CNAME record for the production schematic deployment

Add schematic-prod CNAME

---

org-formation/710-tgw/_tasks.yaml

Setup a route between the transit gateway and the orca-vpc in the AWS org-sagebase-dpe-prod account.

[IT-2722] Setup routes between TGW and orca VPC

---

org-formation/720-client-vpn/_tasks.yaml

Give sage staff access to the orca VPC from the sage VPN.
depends on #761

[IT-2722] Allow sage staff access to orca VPC

---

org-formation/organization.yaml

Create an account for SCCE members to explore AWS services.

[IT-2692] Create org-sagebase-scce-dev account

---

org-formation/700-aws-sso/_tasks.yaml

[IT-2692] Grant SSO access for SCCE dev account

---

org-formation/organization.yaml

[IT-2334] Remove sandbox account from organization

---

org-formation/600-access/_tasks.yaml
sceptre/synapseprod/templates/accounts.yaml

This PR creates a service IAM user to be used to setup a ReDash data source. See https://github.com/getredash/website/blob/master/src/pages/kb/data-sources/amazon-athena.md .

IT-2752: Add svc user for redash access

---

org-formation/600-access/_tasks.yaml

This PR fixes #772, the policy is a JSON document...

IT-2752: Policy in json

---

org-formation/600-access/_tasks.yaml

This PR fixes the ARN of the policy.

IT-2752: Fix role arn

---

org-formation/800-redirects/_tasks.yaml

Mapping Genie-BPC dev application URL to ALB

IT-2426 Mapping Genie-BPC dev application URL to ALB

---

org-formation/800-redirects/_tasks.yaml

Set up CNAME for Production Genie-BPC Shiny app'

IT-2398:  Set up CNAME for Production Genie-BPC Shiny app'

---

org-formation/700-aws-sso/_tasks.yaml

Create Application Manager group for Genie Prod account

IT-2759:  Create Application Manager group for Genie Prod account

---

org-formation/050-costs/_tasks.yaml
org-formation/800-redirects/_tasks.yaml

Rename the existing finops lambda to be under the new finops zone.
depends on: #775

[IT-2594] Rename existing finops lambda

---

org-formation/800-redirects/_tasks.yaml

The new record should be created in the new finops zone.

Use correct ZoneID

---

org-formation/050-costs/_tasks.yaml
org-formation/650-identity-providers/_tasks.yaml

Deploy two copies of the lambda at each dns name while migration takes place.

Perform blue-green migration of lambda-mips-api

---

.pre-commit-config.yaml

* Enable precommit validation of github actions
* update all linter versions

precommit update

---

org-formation/600-access/_tasks.yaml

This PR fixes the bucket name for the Athena data.

IT-2752: Fixed S3 bucket

---

org-formation/650-identity-providers/_tasks.yaml

This PR sets OIDC for the service-catalog-repo in AdminCentral account

IT-2735: OIDC for service-catalog-library repo

---

sceptre/scipool/templates/prod/lambda-budgets/budget-rules.yaml

Adding budget for RECOVER Service Catalog users
Larsson Omberg will be the 'community manager' and the budget will be $500/year.

IT-2767:  Adding budget for RECOVER Service Catalog users

---

org-formation/700-aws-sso/_tasks.yaml

Create Admin and Developer SSO groups for the new challenges and benchmarks development account.

[IT-2748] Create SSO groups for CnB Dev account

---

org-formation/organization.yaml

Adding AWS dev' and prod' accounts for deploying dccvalidator Shiny app's

IT-2770: Adding AWS dev' and prod' accounts for deploying dccvalidator Shiny app's

---

org-formation/800-redirects/_tasks.yaml

Add a CNAME record for the new cost-rules lambda.
depends on: Sage-Bionetworks-IT/lambda-finops-cost-rules#5

[IT-2460] Add DNS for lambda-finops-cost-rules

---

org-formation/100-shared-dns/_tasks.yaml
org-formation/650-identity-providers/_tasks.yaml

Generate DNS cert's for '*.app.sagebionetworks.org' in DCCValidator dev' and prod' accounts.
Set-up GitHub OIDC integration between all three infra' repo's and the DCCValidator dev' and prod' accounts.

IT-2770 GitHub OIDC and DNS cert's for DCC-Validator

---

org-formation/800-redirects/_tasks.yaml

IT-2770 Add CNAME for dccvalidator_1kD dev Shiny app.

IT-2770 Add CNAME for dccvalidator_1kD dev Shiny app

---

org-formation/800-redirects/_tasks.yaml

fixed mistake in CNAME definition for DccvalidatorDev Shiny app'

fixed mistake in CNAME definition for DccvalidatorDev Shiny app'

---

org-formation/800-redirects/_tasks.yaml

revert CNAME definition which broke build

revert CNAME definition which broke build

---

org-formation/800-redirects/_tasks.yaml

retrying the previously failed addition of dccvalidator CNAME

retrying the previously failed addition of dccvalidator CNAME

---

org-formation/800-redirects/_tasks.yaml

As an experiment, try hard coding the LoadBalancer CNAME for dccvalidator.

IT-2770 try hard coding the LoadBalancer CNAME for dccvalidator

---

org-formation/800-redirects/_tasks.yaml

Update the cname template to a version with corrected constraints.

Update cname template version

---

sceptre/sandbox/config/prod/essentials.yaml

The AWS sandbox account has already been remove.

remove sandbox artifacts

---

org-formation/800-redirects/_tasks.yaml

IT-2787 Create CNAMES for dccvalidator and dccmonitor applications (dev and prod stacks).

IT-2787 Create CNAMES for dccvalidator and dccmonitor applications

---

sceptre/itsandbox/config/prod/dustbunnyvpc.yaml

Test upgrading a vpc template to a version that has removed the Department and Project tags.

[IT-2703] Test removing tags from vpc

---

org-formation/050-costs/_tasks.yaml
org-formation/050-costs/categories.yaml

Switch from using a custom Transform to calling a lambda with
an org-formation function.
depends on: #807

[IT-2460] Migrate from custom transform to lambda 

---

org-formation/050-costs/_tasks.yaml
org-formation/050-costs/categories.yaml

This reverts commit 3db5db804cda021b94a0ea1e1fb7c61da2dca33e.

Revert "[IT-2369] Use lambda for Owner Email category"

---

org-formation/650-identity-providers/_tasks.yaml

PR Checklist:
Allow dpe-mwaa-deployment repo' to deploy to DPE accounts

IT-2805: Allow dpe-mwaa-deployment repo' to deploy to DPE accounts

---

org-formation/650-identity-providers/_tasks.yaml

This PR fixes the casing in #839 and adds OIDC for the BMFGKI account.

Fix refs to accounts + add OIDC for bmgfki

---

org-formation/700-aws-sso/_tasks.yaml

fixed database name ('datawarehouse'->'warehouse')

PLFM-7740 fixed database name ('datawarehouse'->'warehouse')

---

org-formation/800-redirects/_tasks.yaml

PR Checklist:
Related to the PR here: https://github.com/Sage-Bionetworks/schematic-infra/pull/29, I want to create an endpoint url for schematic staging instance.

Created an endpoint url for schematic staging instance

---

org-formation/800-redirects/_tasks.yaml

This PR reverts broken commit #847.

revert broken commit #847

---

org-formation/800-redirects/_tasks.yaml

PR Checklist:
Related to the PR here: https://github.com/Sage-Bionetworks/schematic-infra/pull/29

Added schematic staging instance and pointed to prod account

---

org-formation/800-redirects/_tasks.yaml

Reverts Sage-Bionetworks-IT/organizations-infra#849

Revert "Added schematic staging instance and pointed to prod account"

---

org-formation/650-identity-providers/_tasks.yaml

IT-2832: OIDC role for deploying s3-file-hosting to DnTDev account

IT-2832: OIDC role for deploying s3-file-hosting to DnTDev account

---

sceptre/sageit/templates/shiny_redirector.yaml

This PR adds 2 redirections for the dcc*-ad apps.

IT-2676: Add redirects for dcc-*-ad

---

org-formation/050-costs/categories.yaml

Since we don't have automated rules to deduplicate all codes in place yet, update the manual rules with additional codes that need deduplication.

[IT-2840] Update manual category rules

---

.github/workflows/main.yaml

The CI role names to assume will change due to PR #859.
update to the new role names
depends on #859

[IT-2768] Update role name for CI

---

sceptre/imagecentral/config/prod/essentials.yaml
sceptre/itsandbox/config/prod/essentials.yaml
sceptre/logcentral/config/prod/essentials.yaml
sceptre/sageit/config/prod/essentials.yaml
sceptre/synapsedev/config/prod/essentials.yaml
sceptre/synapsedw/config/prod/essentials.yaml
sceptre/synapseprod/config/prod/essentials.yaml

Fix for hard dependency issue in essentials template
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/387

[IT-2768] update essentials template

---

sceptre/imagecentral/config/prod/essentials.yaml
sceptre/itsandbox/config/prod/essentials.yaml
sceptre/logcentral/config/prod/essentials.yaml
sceptre/sageit/config/prod/essentials.yaml
sceptre/synapsedev/config/prod/essentials.yaml
sceptre/synapsedw/config/prod/essentials.yaml
sceptre/synapseprod/config/prod/essentials.yaml

Revert attempt to fix hard dependency issue in essentials template
This reverts "[IT-2768] update essentials template (#864)" and commit d7fab38
[IT-2768]: https://sagebionetworks.jira.com/browse/IT-2768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert to fix build

---

sceptre/scipool/config/develop/sc-tag-options.yaml
sceptre/scipool/config/prod/sc-tag-options.yaml

The lambda is not working due to a change in MIP Cloud, roll back to using the hard-coded files in aws-infra.
Partial revert of "[IT-2774] Update Service Catalog CostCenter tag list (#827)"
This partially reverts commit 8dbec5a4efd040afdaed1c5cc06224bcbe9ac8ce.
[IT-2774]: https://sagebionetworks.jira.com/browse/IT-2774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[IT-2851] Roll back to program-code files

---

.github/workflows/main.yaml
org-formation/650-identity-providers/_tasks.yaml

This reverts commit 05598749e8877f67b578e0021a1f8e21df0f4095.
Manually fixed dependency issues so temporary fix can be removed.

Revert "Temporary fix for GithubOidcSageBionetworksIt (#863)"

---

org-formation/organization.yaml

Create a personal AWS account for Elias

[IT-2838] Create new AWS account

---

org-formation/700-aws-sso/_tasks.yaml

Allow Elias access to his personal aws account as an admin.
depends on #875

[IT-2838] Setup SSO access for personal aws account

---

org-formation/800-redirects/_tasks.yaml

PR Checklist:
- Create a draft PR to add a DCA staging instance to the DCA prod AWS account.
- Linked PR in data_curator-infra https://github.com/Sage-Bionetworks/data_curator-infra/pull/92
- 

Add redirects for a DCA staging environment in the DCA prod AWS account.

---

org-formation/800-redirects/_tasks.yaml

The exported value has two occurrences of "staging-" in it

Fix dca staging stack name

---

sceptre/scipool/config/develop/sc-tag-options.yaml
sceptre/scipool/config/prod/sc-tag-options.yaml

MIP Support has resolved the issue preventing the lambda from logging in.
This reverts commit 599b702f90f28572c097f910b188dc20b942ef52.

Revert "[IT-2851] Roll back to program-code files"

---

org-formation/650-identity-providers/_tasks.yaml

Feedback from last CR: Make ProviderRoleName equal StackName

IT-2111: Make ProviderRoleName equal StackName

---

org-formation/650-identity-providers/_tasks.yaml

PR Checklist:
This will allow the synapserutils repo to push the package build into [staging-]ran.sagebase.org

Allow sage-bionetworks/synapserutils repo' to write documentation to [staging-]ran.sagebase.org buckets as part of build

---

org-formation/600-access/_tasks.yaml

PLFM-7740: Fill in Account ID

---

sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml

Update the notebook product in the service catalog.
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/292

[SC-383] Update notebook product

---

org-formation/organization.yaml

This PR removes the account from organizations.
Depends on #900 .

IT-2693: Remove account

---

sceptre/synapsedev/templates/accounts.yaml

This PR adds an IAM user to suport Peter's synapse stack in the dev account.

Add svc account for pharvey stack

---

sceptre/strides-ampad-workflows/config/prod/github-oidc-nextflow-infra.yaml
sceptre/strides-ampad-workflows/config/prod/github-oidc-sage-bionetworks-it.yaml

Pick up from template change in PR https://github.com/Sage-Bionetworks/aws-infra/pull/396
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/396

Update GH OIDC for strides ampad

---

sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml

Update the rstudio notebook product in scipooldev account for testing
depens on https://github.com/Sage-Bionetworks/service-catalog-library/pull/296

Update SC rstudio product for testing

---

.github/workflows/main.yaml

This PR updates the deployment workflow to use the role created in #904 
Depends on #904

IT-2736: OIDC follow-up

---

org-formation/_platform_org_tags.yaml

Add an AccountOwner tag to the platform accounts.

[IT-3012] Tag platform accounts with an owner

---

sceptre/scipool/config/develop/sc-product-scheduled-jobs.yaml
sceptre/scipool/config/prod/sc-product-scheduled-jobs.yaml
sceptre/scipool/config/strides/sc-product-scheduled-jobs.yaml

Update the service catalog schedule jobs product.
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/299

[IT-3019] update SC schedule jobs product

---

sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml

This PR updates the product version to 1.2.4 for the notebook product in scipooldev.

SC-383: New product version

---

sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml

This PR updates the product version for the Linux notebook product.
Depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/300 .

SC-383: Update product version

---

sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml

This PR picks up the transitive changes from https://github.com/Sage-Bionetworks/service-catalog-utils/pull/24 .

SC-383: Pickup simplified RE fix

---

sceptre/scipool/templates/prod/lambda-budgets/budget-rules.yaml

Change RECOVER Service Catalog budget from 500/yr to 250/yr

Change RECOVER Service Catalog budget from 500/yr to 250/yr

---

sceptre/scipool/config/develop/sc-product-ec2-linux-jumpcloud-notebook.yaml

update notebook product version and fix description in previous versions.
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/308

[SC-383] Update service catalog notebook product

---

org-formation/075-security-hub/security-hub-suppress-infra.yaml

This PR adds exceptions for CIS 4.1/4.2 (access to 22 and 3389 from 0.0.0.0/0). Also adds NOTIFIED to workflow status to catch findings that were manually changed.

IT-2997: Add rules in all accounts for CIS 4.1/4.2

---

org-formation/650-identity-providers/_tasks.yaml

Add OIDC role allowing the lambda repos to push artifacts to the bootstrap and essentials buckets.

[IT-3013] Add OIDC role for lambda deploys

---

sceptre/scipool/config/bmgfki/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-jumpcloud-notebook.yaml

The updated service catalog notebook product has been tested in the development environment, now we push it to the production environments.

[SC-383] Update SC notebook product

---

sceptre/scipool/config/bmgfki/lambda-budgets.yaml
sceptre/scipool/config/develop/lambda-budgets.yaml
sceptre/scipool/config/prod/lambda-budgets.yaml
sceptre/scipool/config/strides/lambda-budgets.yaml

Pull in dependabot security updates for lambda-budgets

[IT-2888] security update for lambda-budgets

---

sceptre/scipool/config/bmgfki/cfn-cr-alb-rule.yaml
sceptre/scipool/config/develop/cfn-cr-alb-rule.yaml
sceptre/scipool/config/prod/cfn-cr-alb-rule.yaml
sceptre/scipool/config/strides/cfn-cr-alb-rule.yaml

Pull in dependabot security updates for cfn-cr-alb-rule.

[IT-2887] Dependabot security updates for cfn-cr-alb-rule

---

org-formation/650-identity-providers/_tasks.yaml

This PR adds more S3 buckets to deploy to, and branches to deploy from, from testing a GH workflow in sageit account.

IT-3162: Add more permissions to deploy from GH in mtb repo

---

org-formation/_tasks.yaml

forgot to include the folder in PR #965

Include orgf vpc flow logs tasks

---

org-formation/725-vpc-flow-logs/aws-config-rule.yaml

The auto remediation failed with the following message in cloudtrail..
```
"errorMessage": "You are not authorized to perform this operation.
Encoded authorization failure
```
Attempt a fix by updating the role's permission

[IT-3090] fix VPC flow log role permissions

---

org-formation/650-identity-providers/_tasks.yaml

This PR updates the OIDC to reflect the new organization/repo name for the MTB project.

IT-3231: Change GH org/repo name

---

sceptre/strides-ampad-workflows/config/prod/essentials.yaml
sceptre/strides/config/prod/essentials.yaml

Fix commit 8814172 The accounts that are not in sage organization are setup slightly differently. we need to accomodate for that.

Fix removal of hard dependency

---

sceptre/strides-ampad-workflows/config/prod/essentials.yaml
sceptre/strides/config/prod/essentials.yaml

fix the stack reference and syntax for stsack_output_external

another fix of hard dependency removal

---

sceptre/scipool/config/strides/essentials.yaml

forgot to include this with commit 1ab23b2

yet another fix of hard dependency removal

---

sceptre/scipool/config/bmgfki/cfn-macro-ssm-param.yaml
sceptre/scipool/config/develop/cfn-macro-ssm-param.yaml
sceptre/scipool/config/prod/cfn-macro-ssm-param.yaml
sceptre/scipool/config/strides/cfn-macro-ssm-param.yaml

Update lambda to use parameterized roles
depends on https://github.com/Sage-Bionetworks-IT/cfn-macro-ssm-param/pull/12

Update cfn-macro-ssm-param lambda

---

sceptre/scipool/config/bmgfki/cfn-macro-ssm-param.yaml
sceptre/scipool/config/prod/cfn-macro-ssm-param.yaml
sceptre/scipool/config/strides/cfn-macro-ssm-param.yaml

Fix for commit 34dc522.  Update parameter name references

Fix paramter references

---

sceptre/imagecentral/config/prod/service-accounts.yaml

fix commit c147cb4, forgot to remove the sceptre template.

fix remove travis service account

---

sceptre/synapseprod/config/prod/snowflake-access.yaml

This PR sets up the actual value for the account ARN (the externalID has been updated in parameter store).

PLFM-8054: Actual value

---

sceptre/synapseprod/templates/SynapseCMK-template.json

This PR removes references to the IAM Admin role created by accounts.yaml so we can remove it in #996 .

PLFM-7169: Remove refs to role

---

sceptre/scipool/config/bmgfki/bootstrap.yaml

This is a redo of commit 253a5d0 which was reverted in commit 7058ab9 due to dependencies that were not removed yet.  We remove the dependencies in PR #997
depends on #997

[IT-3109] remove service user

---

sceptre/scipool/config/strides/cfn-cr-sc-actions-provider.yaml
sceptre/scipool/config/strides/cfn-macro-ssm-param.yaml
sceptre/scipool/config/strides/cfn-s3objects-macro.yaml
sceptre/scipool/config/strides/cfn-tag-instance-policy.yaml
sceptre/scipool/config/strides/sc-ec2vpc-launchrole.yaml
sceptre/scipool/config/strides/sc-enduser-iam.yaml
sceptre/scipool/config/strides/sc-kms-key.yaml
sceptre/scipool/config/strides/sc-s3-launchrole.yaml
sceptre/scipool/config/strides/sc-scheduled-jobs-launchrole.yaml
sceptre/scipool/config/strides/scheduledjobsvpc.yaml
sceptre/scipool/config/strides/stridespoolvpc.yaml

This is a fix for commit 58739034.  We removed bootstrap.yaml and essentials.yaml but forgot to remove the references to them.

Fix strides dependency

---

sceptre/scipool/config/develop/sc-tag-options.yaml
sceptre/scipool/config/prod/sc-tag-options.yaml

Prioritize the MC2 program codes in the Service Catalog drop-down menu.

[IT-3244] Make sure the MC2 codes are in the SC drop-down

---

sceptre/scipool/config/bmgfki/cfn-cr-alb-rule.yaml
sceptre/scipool/config/develop/cfn-cr-alb-rule.yaml
sceptre/scipool/config/prod/cfn-cr-alb-rule.yaml
sceptre/scipool/config/strides/cfn-cr-alb-rule.yaml

Update the cfn-cr-alb-rule lambda with a fix to remove hard dependency.
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-alb-rule/pull/14

Update cfn-cr-alb-rule lambda

---

org-formation/700-aws-sso/_tasks.yaml

Add required 'TemplatingContext' key

---

sceptre/synapseprod/templates/SynapseCMK-template.json

This PR enables key rotation on the prod stack.

IT-2789: Enable key rotation on prod

---

org-formation/650-identity-providers/_tasks.yaml

This PR adds permissions to prod buckets and distributions

IT-3162: More buckets added to OIDC for bridgedigitalhealth

---

org-formation/800-redirects/_tasks.yaml

PR Checklist:
Added schematic dev-refactor env and pointed to D&T dev account
Depends on: https://github.com/Sage-Bionetworks/schematic-infra/pull/76

Added schematic dev-refactor env and pointed to D&T dev account

---

sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/bmgfki/sc-product-ec2-linux-jumpcloud-notebook.yaml
sceptre/scipool/config/bmgfki/sc-product-ec2-windows-jumpcloud.yaml

Update EC2 instance types
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/311

[IT-3222] Update instance types

---

sceptre/synapseprod/templates/snowflake-access.yaml

PR Checklist:
[ *] Describe and explain your intentions for this change
[ *] Setup pre-commit and run the validators (info in README.md)

PLFM-8005: Allows snowflake to access synapse bucket inventory

---

sceptre/synapseprod/templates/snowflake-access.yaml

Reverting this as I am moving the inventory in the data warehouse folder directly

Revert "PLFM-8005: Allows snowflake to access synapse bucket inventory"

---

sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml

Update the base AMI in order to upgrade Python.
Depends on Sage-Bionetworks/service-catalog-library#313

[SC-409] Update docker base AMI in dev

---

sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml

Depends on Sage-Bionetworks/service-catalog-library#314

[SC-409] Test another AMI update in sc-dev

---

org-formation/700-aws-sso/_tasks.yaml

Now the build is broken.  I think this one last change needs to be undone.

IT-3322 undo breaking change

---

org-formation/700-aws-sso/_tasks.yaml

Part 2 of fixing the broken build.

IT-3322 re-adding  application-manager permission sets

---

org-formation/050-costs/_tasks.yaml

Update our MIP microservice lambda to a version that works around an issue we are seeing in the upstream API.

[IT-3316] Update MIP microservice

---

sceptre/synapsedev/config/prod/snowflake-access.yaml

This PR uses an updated template to fix the deployment failure in #548

snowflake-access-syndev-dw: use updated template

---

org-formation/650-identity-providers/_tasks.yaml

This PR fixes the deployment error for #559

IT-3334: Fix typo

---

sceptre/synapsedev/templates/accounts.yaml

Creating an IAM account for myself as part of the onboarding process. Let me know if I missed something required. 
PR Checklist:

Add IAM User for Luke Moenning

---

sceptre/synapsedev/templates/accounts.yaml

This PR deletes two IAM svc user used by developer builds

IT-3393: Delete IAM users

---

org-formation/600-access/_tasks.yaml

Remove GenUI access to iAtlas AWS account.

[IT-3329] Remove GenUI access

---

.github/workflows/check.yaml
.github/workflows/deploy.yaml

This is a refactor for a cleaner and more efficient CI workflow
* check - quick validates before deployment
* deploy - deploy to AWS only when merging or pushing to the master branch

Refactor Github actions workflow

---

org-formation/050-costs/_tasks.yaml

Update the MIP microservice to a version that enables KMS key rotation.

[IT-3121] Update MIP microservice version

---

sceptre/scipool/config/bmgfki/cfn-cr-sc-bucket-policy.yaml
sceptre/scipool/config/develop/cfn-cr-sc-bucket-policy.yaml
sceptre/scipool/config/prod/cfn-cr-sc-bucket-policy.yaml
sceptre/scipool/config/strides/cfn-cr-sc-bucket-policy.yaml

Work around a timeout encountered in a nested CFN stack by increasing the timeout of the nested stack.

[SC-410] Increase cfn-cr-sc-bucket-policy timeout

---

sceptre/scipool/config/bmgfki/sc-product-s3-private-enc.yaml
sceptre/scipool/config/bmgfki/sc-product-s3-synapse.yaml
sceptre/scipool/config/develop/sc-product-s3-private-enc.yaml
sceptre/scipool/config/develop/sc-product-s3-synapse.yaml
sceptre/scipool/config/prod/sc-product-s3-private-enc.yaml
sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
sceptre/scipool/config/strides/sc-product-s3-private-enc.yaml
sceptre/scipool/config/strides/sc-product-s3-synapse.yaml

Fix a deploy error in RestrictBucketDownloadRegionFunction.
Depends on Sage-Bionetworks/service-catalog-library#327

[IT-3466] Update cfn-cr-same-region-bucket-download lambda

---

sceptre/scipool/config/develop/sc-product-ec2-windows-jumpcloud-test.yaml

Create a product in SC for testing a new windows AMI. 
This product will be removed once testing is complete.
Depends on Sage-Bionetworks/service-catalog-library#329

[IT-3456] Test Windows OS upgrade

---

.github/workflows/check.yaml
.pre-commit-config.yaml
sceptre/scipool/templates/sc-product-ec2-linux-docker-notebook.j2
sceptre/scipool/templates/sc-product-ec2-linux-docker.j2
sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-workflows.j2
sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud.j2
sceptre/scipool/templates/sc-product-ec2-windows-jumpcloud.j2
sceptre/scipool/templates/sc-product-s3-private-enc.j2
sceptre/scipool/templates/sc-product-s3-synapse.j2
sceptre/scipool/templates/sc-product-scheduled-jobs.j2

* Replace existing jinja linter with aristanetworks/j2lint[1] linter
* fix linter warnings/errors
[1] https://github.com/aristanetworks/j2lint

[IT-3396] Use a better jinja linter

---

org-formation/600-access/_tasks.yaml
org-formation/700-aws-sso/_tasks.yaml

The first step to removing an AWS account is to remove access.

[IT-3534] Remove access to NlpSandboxAccount

---

org-formation/organization.yaml

Remove the AWS NlpSandboxAccount
depends on #1118

[IT-3534] Remove NlpSandbox account

---

sceptre/synapsedev/templates/accounts.yaml

PR to create Jin Jun Oh a service account to run from Jenkins
PR Checklist:
[x] Describe and explain your intentions for this change
[x] Setup pre-commit and run the validators (info in README.md)

Add IAM service account for Jin Jun Oh

---

sceptre/scipool/templates/sc-product-ec2-linux-docker-notebook.j2
sceptre/scipool/templates/sc-product-ec2-linux-docker.j2
sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud-workflows.j2
sceptre/scipool/templates/sc-product-ec2-linux-jumpcloud.j2
sceptre/scipool/templates/sc-product-ec2-windows-jumpcloud.j2
sceptre/scipool/templates/sc-product-s3-private-enc.j2
sceptre/scipool/templates/sc-product-s3-synapse.j2
sceptre/scipool/templates/sc-product-scheduled-jobs.j2

Add a product constraint allowing SC users to update tags on their provisioned products.

[IT-3554] Allow SC Enduser roles to tag resources

---

org-formation/050-costs/_tasks.yaml

Rephrase the note about updating cost center tags to be imperative.

[IT-3554] Update finops email lambda to a version with an improved message.

---

README.md
sceptre/scipool/templates/sc-enduser-iam.j2

Variable scoping doesn't allow updating a variable within an if block. Also, Sceptre is interpreting the input as a boolean value, not a string.

[IT-3554] Fix jinja logic

---

sceptre/synapsedev/config/prod/snowflake-access.yaml

switch to jinja template to accept multiple bucket Arn and Prefix
depends on https://github.com/Sage-Bionetworks/aws-infra/pull/413

[IT-3559] Update to use new snowflake access template

---

org-formation/075-security-hub/_tasks.yaml

run all SecHub stacks as SecurityCentralAccount

IT-3606: run all SecHub stacks as SecurityCentralAccount

---

org-formation/075-security-hub/_tasks.yaml
org-formation/075-security-hub/security-hub.yaml

reverting broken change to SecHub configuration

IT-3606 reverting broken change to SecHub configuration

---

sceptre/scipool/templates/sc-ec2vpc-launchrole.yaml
sceptre/scipool/templates/sc-scheduled-jobs-launchrole.yaml

More permission errors have been uncovered while updating service catalog product tags, add the needed permissions.

[IT-3554] Add more SC launch role permissions

---

sceptre/aws-opendata/config/prod/brainseq-bucket.yaml
sceptre/aws-opendata/config/prod/newproject-bucket.yaml

[IBCSPRT-251, IBCDPE-937] Add Brainseq AOD bucket

---

org-formation/700-aws-sso/_tasks.yaml
org-formation/organization.yaml

* Promote robert to SCCE dev account owner which means he will have admin access
* Give all developers in every account full access to AWS bedrock.

[IT-3683] Give users access to AWS bedrock

---

org-formation/075-security-hub/README.md
org-formation/README.md

* update docs referencing how AWS config was setup
* update docs referencing how AWS securityhub was setup

[IT-3619] Update aws config Docs

---

org-formation/organization.yaml

Provision a personal AWS account for Susheel

[IT-3675] Personal AWS account for Susheel

---

org-formation/725-vpc-flow-logs/_tasks.yaml

This is causing GH action deployment failure so we are gonna temporarily disable until we find an alternative solution.

[IT-3721] Temporarily disable VPC flow logs

---

org-formation/700-aws-sso/_tasks.yaml

Give Susheel access to his personal AWS account.
depends on #1160

[IT-3675] Setup SSO access for personal aws account

---

org-formation/800-redirects/_tasks.yaml

PR Checklist:
Add DCA testing instance where users can test new configurations on production schematic and DCA
Related to FDS-2028: https://sagebionetworks.jira.com/browse/FDS-2028

add dca testing instance

---

sceptre/scipool/config/bmgfki/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/prod/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/strides/sc-product-ec2-linux-docker.yaml

Use the correct base image with SSM pre-installed, and ensure that the SSM user has sudo access.

[IT-3697] Fix SSM access to docker SC product

---

sceptre/scipool/config/bmgfki/cfn-cr-synapse-tagger.yaml
sceptre/scipool/config/develop/cfn-cr-synapse-tagger.yaml
sceptre/scipool/config/prod/cfn-cr-synapse-tagger.yaml
sceptre/scipool/config/strides/cfn-cr-synapse-tagger.yaml

Update cfn-cr-synapse-tagger lambda in prod, STRIDES and BMGF-ki  Service Catalog accounts

IT-3686: Update cfn-cr-synapse-tagger lambda in prod, STRIDES and BMGF-ki  Service Catalog accounts

---

org-formation/600-access/_tasks.yaml

Setup a FPTMinimumAccess role to allow Four Points to access our Organizations account.  They need
access to billing info.

[IT-3758] Setup cross account access to Organizations

---

org-formation/700-aws-sso/_tasks.yaml

IT-3757: Remove INCLUDE chop JC groups

---

.github/PULL_REQUEST_TEMPLATE.md
org-formation/700-aws-sso/_tasks.yaml
org-formation/organization.yaml

PR Checklist:
Remove CHOP AWS account
See #1167 
depends on #1168

IT-3757: Remove chop aws

---

sceptre/scipool/config/bmgfki/sc-product-s3-private-enc.yaml
sceptre/scipool/config/bmgfki/sc-product-s3-synapse.yaml
sceptre/scipool/config/prod/sc-product-s3-private-enc.yaml
sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
sceptre/scipool/config/strides/sc-product-s3-private-enc.yaml
sceptre/scipool/config/strides/sc-product-s3-synapse.yaml

Update the S3 products to use the latest version of the region restriction lambda in the rest of the environments.

[IT-3547] Update S3 products

---

sceptre/synapsedev/templates/SynapseCMK-template.json

PLFM-8425: Allows api gateway deployment

---

sceptre/scipool/config/develop/sc-product-ec2-linux-docker-notebook.yaml

IT-3421:  Update notebook product in 'dev' Service Catalog to include automated container update in support of security patching.

IT-3421:  Update notebook product in dev Service Catalog

---

sceptre/synapsedev/templates/SynapseCMK-template.json

This PR adds permissions to bedrock for the stackBuilder

Add bedrock perm

---

sceptre/organizations/templates/s3-cur-bucket.j2

Four points tried to setup CUR reports and noticed that the service requires a `condition` setting.

[IT-3758] Tweak permissions for four points

---

.github/workflows/aws-deploy.yaml
.github/workflows/aws-scipool.yaml

Reverts Sage-Bionetworks-IT/organizations-infra#1200
Sceptre v4.5.2 fixed issue https://github.com/Sceptre/sceptre/issues/1506

Revert "Fix build"

---

org-formation/700-aws-sso/_tasks.yaml

Setup a role to allow developers access to the htan dev account.

Setup SSO for developers in htan dev account

---

org-formation/650-identity-providers/_tasks.yaml

This PR reverts the earlier changes from #1208 and #1209 to get builds going...

IT-3773: revert change while fixing

---

org-formation/650-identity-providers/_tasks.yaml

This PR splits the inline policy from #1208 into 3 managed policies along the types of resources (bucket, file, distributions).

IT-3773: Add managed policies

---

org-formation/organization.yaml

Create an AWS account for openchallenges development environment.

[IT-3891] Create AWS account for openchallenges dev

---

org-formation/700-aws-sso/_tasks.yaml

Allow jumpcloud users admin access to OpenChallenges DEV account.
depends on #1213

[IT-3891] Setup jumpcloud admin access to openchallenges dev account

---

org-formation/organization.yaml

Create an AWS account for openchallenges production environment.

[IT-3891] Create AWS account for openchallenges prod

---

org-formation/700-aws-sso/_tasks.yaml

Allow jumpcloud users admin access to OpenChallenges Prod account.
depends on #1216

[IT-3891] Setup jumpcloud admin access to openchallenges prod account

---

org-formation/organization.yaml

This PR creates an account to host the Synapse LLM development environment.

IT-3924: Create dev account for Synapse LLM

---

org-formation/700-aws-sso/_tasks.yaml

Requires #1231 
This PR creates a role to give full access to BedRock and associates it to the developer group in the SynapseLLM prod account.

IT-3294: Add role

---

sceptre/scipool/config/develop/sc-product-scheduled-jobs.yaml

Update the Scheduled Job product with the latest version of lambda-batch-trigger.

[IT-3547] Periodic update of SC products

---

org-formation/700-aws-sso/_tasks.yaml

This PR should fix the deployment error.

IT-3924: fix-deployment : Add missing templating context

---

org-formation/700-aws-sso/_tasks.yaml

No idea why this keeps failing, remove to unblock ci and will try again tomorrow.

IT-3924: Remove llmdev role to unblock ci

---

org-formation/700-aws-sso/_tasks.yaml

It's actually failing on the 2nd (dependent) script...

IT-3924: Remove llm admin role

---

sceptre/scipool/config/prod/sc-product-scheduled-jobs.yaml
sceptre/scipool/config/strides/sc-product-scheduled-jobs.yaml

Periodic update of the batch product in service catalog

[IT-3547] Promote batch update to prod/strides

---

sceptre/scipool/config/bmgfki/cfn-macro-ssm-param.yaml
sceptre/scipool/config/develop/cfn-macro-ssm-param.yaml
sceptre/scipool/config/prod/cfn-macro-ssm-param.yaml
sceptre/scipool/config/strides/cfn-macro-ssm-param.yaml

depends on https://github.com/Sage-Bionetworks-IT/cfn-macro-ssm-param/pull/24

[IT-3807] Update cfn-macro-ssm-param lambda

---

sceptre/strides-ampad-workflows/config/prod/lambda-finops-s3-cost-report.yaml
sceptre/strides/config/prod/lambda-finops-s3-cost-report.yaml

Send an email report summarizing costs by service and costs by S3 usage type to STRIDES admins.
Depends on Sage-Bionetworks-IT/lambda-finops-s3-cost-report#1

[IT-3068] Send S3 cost report to STRIDES admins

---

sceptre/scipool/config/bmgfki/cfn-cr-sc-bucket-policy.yaml
sceptre/scipool/config/develop/cfn-cr-sc-bucket-policy.yaml
sceptre/scipool/config/prod/cfn-cr-sc-bucket-policy.yaml
sceptre/scipool/config/strides/cfn-cr-sc-bucket-policy.yaml

depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-bucket-policy/pull/18

[IT-3804] Update cnf-cr-sc-bucket-policy lambda

---

sceptre/scipool/config/bmgfki/cfn-cr-sc-actions-provider.yaml
sceptre/scipool/config/develop/cfn-cr-sc-actions-provider.yaml
sceptre/scipool/config/prod/cfn-cr-sc-actions-provider.yaml
sceptre/scipool/config/strides/cfn-cr-sc-actions-provider.yaml

depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-actions-provider/pull/25

[IT-3806] Update cfn-cr-sc-actions-provider lambda

---

sceptre/scipool/config/bmgfki/cfn-cr-alb-rule.yaml
sceptre/scipool/config/develop/cfn-cr-alb-rule.yaml
sceptre/scipool/config/prod/cfn-cr-alb-rule.yaml
sceptre/scipool/config/strides/cfn-cr-alb-rule.yaml

depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-alb-rule/pull/22

[IT-3809] Update cfn-cr-alb-rule lambda

---

sceptre/scipool/config/bmgfki/cfn-cr-synapse-tagger.yaml
sceptre/scipool/config/develop/cfn-cr-synapse-tagger.yaml
sceptre/scipool/config/prod/cfn-cr-synapse-tagger.yaml
sceptre/scipool/config/strides/cfn-cr-synapse-tagger.yaml

depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger/pull/46

[IT-3811] Update cfn-cr-synapse-tagger lambda

---

sceptre/scipool/config/bmgfki/cfn-cr-sc-product-provider.yaml
sceptre/scipool/config/develop/cfn-cr-sc-product-provider.yaml
sceptre/scipool/config/prod/cfn-cr-sc-product-provider.yaml
sceptre/scipool/config/strides/cfn-cr-sc-product-provider.yaml

depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-product-provider/pull/13

[IT-3815] Update cfn-cr-sc-product-provider lambda

---

sceptre/scipool/config/bmgfki/sc-product-s3-private-enc.yaml
sceptre/scipool/config/bmgfki/sc-product-s3-synapse.yaml
sceptre/scipool/config/develop/sc-product-s3-private-enc.yaml
sceptre/scipool/config/develop/sc-product-s3-synapse.yaml
sceptre/scipool/config/prod/sc-product-s3-private-enc.yaml
sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
sceptre/scipool/config/strides/sc-product-s3-private-enc.yaml
sceptre/scipool/config/strides/sc-product-s3-synapse.yaml

depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/339

[IT-3812] Update service catalog S3 products

---

sceptre/admincentral/config/prod/cfn-s3objects-macro.yaml
sceptre/aws-opendata/config/prod/cfn-s3objects-macro.yaml
sceptre/sageit/config/prod/cfn-s3objects-macro.yaml
sceptre/scicomp/config/prod/cfn-s3objects-macro.yaml
sceptre/scipool/config/bmgfki/cfn-s3objects-macro.yaml
sceptre/scipool/config/develop/cfn-s3objects-macro.yaml
sceptre/scipool/config/prod/cfn-s3objects-macro.yaml
sceptre/scipool/config/strides/cfn-s3objects-macro.yaml

Update the lambda to use python 3.11
depends on https://github.com/Sage-Bionetworks-IT/cfn-s3objects-macro/pull/18

Update cfn-s3objects-macro lambda

---

sceptre/scipool/config/bmgfki/lambda-budgets.yaml
sceptre/scipool/config/develop/lambda-budgets.yaml
sceptre/scipool/config/prod/lambda-budgets.yaml
sceptre/scipool/config/strides/lambda-budgets.yaml

Update the lambda to use python 3.11
depends on https://github.com/Sage-Bionetworks-IT/lambda-budgets/pull/27

Update lambda-budget lambda

---

org-formation/650-identity-providers/microsoft-defender-cloud-roles.yaml

[IT-3950] Updated Defender for Cloud template

---

org-formation/050-costs/_tasks.yaml

Apply dependency updates to the finops lambdas to address dependabot findings.
Jira IT-3818 IT-3819 IT-3820

Address dependabot findings in finops lambdas

---

org-formation/650-identity-providers/_tasks.yaml

This PR adds the dev bucket to the policies for the oidc deployment role.

IT-3849: Add new deployment bucket for dev.accounts.synapse.org

---

org-formation/090-systems-manager/_tasks.yaml

Run nessus script installation daily, not hourly

Run nessus script installation daily, not hourly

---

org-formation/650-identity-providers/_tasks.yaml

This PR allows deployment from the develop branch (to be used on the SynapseDev account).

IT-3934: Add dev branch

---

org-formation/700-aws-sso/_tasks.yaml

This PR should fix the deployment issue in #1282 . Looked at the how it was done for SsoSynapseDWDevAthenaUser just below it.

IT-3988: Fix ref to cust policy

---

org-formation/090-systems-manager/_tasks.yaml
sceptre/scipool/config/develop/sc-product-ec2-linux-docker-notebook.yaml

Update SC notebook product version to 1.4.8 in dev'.
Once tested, we will update in the other Service Catalog instances (prod, strides, bmgf-ki)

it-4004: Update SC notebook product version to 1.4.8 in dev'

---

org-formation/organization.yaml

Create a new personal AWS account

[IT-3980] Personal AWS account for Mieko

---

org-formation/700-aws-sso/_tasks.yaml

Setup SSO access for personal AWS account.
depends on #1285

[IT-3980] Configure SSO access for personal aws account

---

org-formation/800-redirects/_tasks.yaml

We had setup a redirect for dev.sagedpe.org as part of work for IT-3931 however it was done manually.  This PR will do it with cloudformation and put it under CI control.

[IT-4024] Setup a redirect to sagedpe.org apps

---

sceptre/strides-ampad-workflows/config/prod/lambda-finops-s3-cost-report.yaml
sceptre/strides/config/prod/lambda-finops-s3-cost-report.yaml

Add the account ID to the cost report email.

[IT-3068] Bump version of s3-cost-report lambda

---

org-formation/650-identity-providers/_tasks.yaml

Create github OIDC access to allow CI deployments from github actions.

[IT-3995] Setup github OIDC for agora-infra-v3

---

org-formation/700-aws-sso/_tasks.yaml

Setup developer access to AWS org-sagebase-openchallenges-dev account.

[IT-4031] Add openchallenges developer SSO access

---

sceptre/synapsedev/templates/SynapseCMK-template.json

PLFM-8614: Add aoss permissions to deployer

---

sceptre/synapsedev/config/prod/vpc.yaml

This PR deploys a vpc endpoint  for opensearch in synapse dev

IT-4226: Deploy vpce for opensearch in syndev

---

org-formation/organization.yaml

Create new AWS account to run codeocean application

[IT-4228] New AWS account

---

org-formation/090-systems-manager/_tasks.yaml
org-formation/700-aws-sso/_tasks.yaml

Add TemplatingContext to invocation of aws-sso.njk

IT-4237: Add TemplatingContext to invocation of aws-sso.njk

---

org-formation/700-aws-sso/_tasks.yaml

Forgot to add the most important policy in commit 627e8c6

[IT-4244] Add policy to SsoImageCentralAmiLibrarian SSO role

---

sceptre/bridge/templates/aws-default-vpc.yaml

Block all SSH and RPD traffic on public networks used by Bridge.

[IT-4171] Block SSH/RPD on public Bridge networks

---

org-formation/090-systems-manager/QuickSetup-PatchPolicy.yaml

bugfix: should be an array, not an object

---

org-formation/090-systems-manager/_tasks.yaml

CFN says this needs to be us-east-1

---

org-formation/075-security-hub/security-hub-suppress-infra.yaml

Add several Bridge buckets to the list for suppressing findings related to public buckets.

[IT-4072] Suppress findings for public Bridge buckets

---

org-formation/650-identity-providers/_tasks.yaml
org-formation/700-aws-sso/_tasks.yaml

1st step to decommisioning aws account is to remove access to users.

[IT-4315] Remove access to codeocean account.

---

org-formation/organization.yaml

[IT-4315] Remove codeocean aws account from organization

---

sceptre/bridge/templates/bridge.yaml

Block public ACLs for the Cloudtrail bucket and the legacy Config bucket.

[IT-4072] Block public ACLs for more Bridge buckets

---

org-formation/075-security-hub/security-hub-suppress-infra.yaml

Add more Bridge buckets used for public web hosting to the suppression list.

[IT-4072] Additional public Bridge buckets

---

sceptre/imagecentral/templates/ec2-image-builder.yaml

Block public ACLs for imagebuilder logs bucket

[IT-4193] Resolve securityhub finding

---

org-formation/organization.yaml

Create a new non prod AWS account for Gen AI innovation center work.

[IT-4330] New AWS account

---

org-formation/700-aws-sso/_tasks.yaml

Setup SSO user access to AWS GenAiIcDev account.
depends on #1368

[IT-4330] Setup access to AWS account

---

sceptre/scipool/config/bmgfki/sc-product-s3-private-enc.yaml
sceptre/scipool/config/bmgfki/sc-product-s3-synapse.yaml
sceptre/scipool/config/develop/sc-product-s3-private-enc.yaml
sceptre/scipool/config/develop/sc-product-s3-synapse.yaml
sceptre/scipool/config/prod/sc-product-s3-private-enc.yaml
sceptre/scipool/config/prod/sc-product-s3-synapse.yaml
sceptre/scipool/config/strides/sc-product-s3-private-enc.yaml
sceptre/scipool/config/strides/sc-product-s3-synapse.yaml

Update service catalog S3 products
depends on https://github.com/Sage-Bionetworks/service-catalog-library/pull/341

[IT-4074] Update service catalog

---

org-formation/730-cloudwatch-to-S3/CloudWatch2S3-bucket.yaml

Enable block public ACLs for cloudwatch data logs bucket

[IT-4096] Resolve securityhub finding

---

org-formation/organization.yaml

I did not see any specific JC group access for this account, so I think we just need to remove it from the organization.
Depends in #1374

PLFM-8789: Remove the synapsedw account from org

---

org-formation/600-access/_tasks.yaml

Give Gen AI AWS team restricted access to our `org-sagebase-genaiic` account for ongoing collaboration with Sage scientists.

[IT-4355] Create a role for Gen AI collaborators

---

org-formation/050-costs/_tasks.yaml

[IT-4374] bugfix: strip invalid characters in lambda-mips-api

---

sceptre/scipool/config/develop/sc-product-ec2-linux-docker-notebook.yaml
sceptre/scipool/config/develop/sc-product-ec2-linux-docker.yaml
sceptre/scipool/config/develop/sc-product-ec2-windows-jumpcloud.yaml

This PR updates the SC products to 1.4.10 which adds the policy for SSM patching to the instance role

IT-4369: Update svc-catalog-lib-version for dev

---

org-formation/075-security-hub/security-hub-suppress-infra.yaml

Try re-arranging list to fix failed deployment[1]
[1] https://github.com/Sage-Bionetworks-IT/organizations-infra/actions/runs/14865437772/job/41740960852

Fix deployment

---

org-formation/650-identity-providers/_tasks.yaml

Create github OIDC access to allow CI deployments from github actions.

MG-182: setup github OIDC for modeladexplorer-infra

---

org-formation/710-tgw/_tasks.yaml
org-formation/720-client-vpn/_tasks.yaml
org-formation/740-cloudwatch-dashboard/_tasks.yaml

Remove AWS resources specific to the old Agora elastic beanstalk infrastructure environment.

[IT-4418] Remove resources for old Agora

---

org-formation/075-security-hub/security-hub-suppress-infra.yaml
org-formation/075-security-hub/security-hub.yaml

Move SuppressFindingsForPublicBucketsRule to use native security hub automation rules.

[IT-4445] Move security hub rule to native system

---

org-formation/075-security-hub/security-hub-suppress-infra.yaml
org-formation/075-security-hub/security-hub.yaml

Move SuppressFindingsForPublicImagesRule to use native security hub automation rules.

[IT-4445] Move security hub SuppressFindingsForPublicImagesRule

---

org-formation/100-shared-dns/_tasks.yaml

Remove hosted zone for bridgedigital.health

[IT-4026] Remove hosted zone for bridgedigital.health

---

org-formation/300-account-defaults/_tasks.yaml

Bump version of lambda-ebs-cleanup to address a security finding.

[IT-4454] Bump lambda-ebs-cleanup version

---

org-formation/650-identity-providers/_tasks.yaml
org-formation/700-aws-sso/_tasks.yaml
org-formation/organization.yaml

Remove access to BMGF-Ki account and removing the account as well.
depends on #1443

[IT-4529] Remove bmgfki account

---

org-formation/700-aws-sso/_tasks.yaml

Setup SSO user access to AWS org-sagebase-bixarena account.
depends on #1447

[IT-4546] Setup access to AWS account

---

org-formation/650-identity-providers/_tasks.yaml

Create github OIDC access to allow CI deployments from github actions.
depends on #1448

[IT-4546] setup github OIDC for bixarena-infra

---

package-lock.json
package.json

`npm update` to update libraries
This fixes dependabot issues:
* https://github.com/Sage-Bionetworks-IT/organizations-infra/security/dependabot/15
* https://github.com/Sage-Bionetworks-IT/organizations-infra/security/dependabot/14
* https://github.com/Sage-Bionetworks-IT/organizations-infra/security/dependabot/17

[IT-4553] Update libraries

---

org-formation/800-redirects/_tasks.yaml

This reverts commit aa3dd85f6229ab104f425a155a6c43e1f12f9ecd.
Revert due to error..
```
ERROR: Resource WebsiteBucket failed because Resource handler returned message:
"Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting
```

Revert "[IT-4498] Setup redirect for apex domain (#1457)"
